#nullable enable // autogenerated

using System;
using System.Collections.Generic;
using PVZEngine.Modifiers;
using Tools;

namespace PVZEngine.Level
{
    public class ModifiableProperties
    {
        public ModifiableProperties(IModifiablePropertyTarget target, params IModifierProvider[] providers)
        {
            Target = target;
            Providers = providers;
            foreach (var provider in providers)
            {
                provider.OnModifiedPropertyNeedsUpdate += OnModifiedPropertyNeedsUpdateCallback;
            }
        }

        #region 设置属性
        public void SetProperty<T>(PropertyKey<T> name, T? value)
        {
            var beforeValue = GetProperty<T>(name);
            if (properties.SetProperty(name, value))
            {
                UpdateModifiedProperty<T>(name, beforeValue);
            }
        }
        public void SetPropertyObject(IPropertyKey name, object? value)
        {
            var beforeValue = GetPropertyObject(name);
            if (properties.SetPropertyObject(name, value))
            {
                UpdateModifiedPropertyObject(name, beforeValue);
            }
        }
        public bool RemoveProperty(IPropertyKey name)
        {
            var beforeValue = GetPropertyObject(name);
            if (properties.RemovePropertyObject(name))
            {
                UpdateModifiedPropertyObject(name, beforeValue);
                return true;
            }
            return false;
        }
        #endregion

        #region 获取属性
        public bool TryGetPropertyObject(IPropertyKey name, out object? result, bool ignoreBuffs = false)
        {
            if (!ignoreBuffs)
            {
                if (modifiedProperties.TryGetPropertyObject(name, out var value))
                {
                    result = value;
                    return true;
                }
            }
            if (properties.TryGetPropertyObject(name, out var prop))
            {
                result = prop;
                return true;
            }
            if (fallbackCaches.TryGetValue(name, out var fallbackCache))
            {
                result = fallbackCache;
                return true;
            }
            if (Target.GetFallbackProperty(name, out var fallback))
            {
                AddFallbackCache(name, fallback);
                result = fallback;
                return true;
            }
            result = name.DefaultValue;
            AddFallbackCache(name, result);
            return false;
        }
        public bool TryGetProperty<T>(PropertyKey<T> name, out T? result, bool ignoreBuffs = false)
        {
            if (TryGetPropertyObject(name, out var obj, ignoreBuffs))
            {
                if (obj.TryToGeneric<T>(out result))
                {
                    return true;
                }
            }
            result = name.DefaultValue;
            return false;
        }
        public T? GetProperty<T>(PropertyKey<T> name, bool ignoreBuffs = false)
        {
            if (TryGetProperty<T>(name, out var result, ignoreBuffs))
            {
                return result;
            }
            return name.DefaultValue;
        }
        public object? GetPropertyObject(IPropertyKey name, bool ignoreBuffs = false)
        {
            if (TryGetPropertyObject(name, out var result, ignoreBuffs))
            {
                return result;
            }
            return name.DefaultValue;
        }
        #endregion

        #region 后备缓存
        public void AddFallbackCache(IPropertyKey key, object? value)
        {
            fallbackCaches.Add(key, value);
        }
        public bool RemoveFallbackCache(IPropertyKey key)
        {
            return fallbackCaches.Remove(key);
        }
        public void ClearFallbackCaches()
        {
            fallbackCaches.Clear();
        }
        public IPropertyKey[] GetPropertyNames()
        {
            return properties.GetPropertyNames();
        }
        #endregion

        #region 修改器
        public void UpdateAllModifiedProperties(bool triggersEvaluation)
        {
            foreach (var provider in Providers)
            {
                foreach (var key in provider.GetModifiedProperties())
                {
                    var beforeValue = GetPropertyObject(key);
                    UpdateModifiedPropertyObject(key, beforeValue, triggersEvaluation);
                }
            }
        }
        public void UpdateModifiedPropertyObject(IPropertyKey name, object? beforeValue, bool triggersEvaluation = true)
        {
            var baseValue = GetPropertyObject(name, ignoreBuffs: true);

            modifierContainerBuffer.Clear();
            foreach (var provider in Providers)
            {
                provider.GetModifiersForProperty(name, modifierContainerBuffer);
            }

            var value = baseValue;
            if (modifierContainerBuffer.Count > 0)
            {
                value = modifierContainerBuffer.CalculateProperty(baseValue);
                modifiedProperties.SetPropertyObject(name, value);
            }
            else
            {
                modifiedProperties.RemovePropertyObject(name);
            }
            CallPropertyChanged(name, beforeValue, value, triggersEvaluation);
        }
        public void UpdateModifiedProperty<T>(PropertyKey<T> name, T? beforeValue, bool triggersEvaluation = true)
        {
            var baseValue = GetProperty<T>(name, ignoreBuffs: true);

            modifierContainerBuffer.Clear();
            foreach (var provider in Providers)
            {
                provider.GetModifiersForProperty(name, modifierContainerBuffer);
            }

            var value = baseValue;
            if (modifierContainerBuffer.Count > 0)
            {
                value = modifierContainerBuffer.CalculateProperty<T>(baseValue);
                modifiedProperties.SetProperty(name, value);
            }
            else
            {
                modifiedProperties.RemoveProperty(name);
            }
            CallPropertyChanged(name, beforeValue, value, triggersEvaluation);
        }
        private void CallPropertyChanged(IPropertyKey name, object? beforeValue, object? afterValue, bool triggersEvaluation)
        {
            RemoveFallbackCache(name);
            Target.OnPropertyChanged(name, beforeValue, afterValue, triggersEvaluation);
        }
        #endregion

        #region 序列化
        public SerializableModifiableProperties ToSerializable()
        {
            return new SerializableModifiableProperties()
            {
                properties = properties.ToSerializable()
            };
        }
        public void LoadFromSerializable(SerializableModifiableProperties? seri)
        {
            if (seri != null)
            {
                properties.LoadFromSerializable(seri.properties);
            }
        }
        #endregion

        void OnModifiedPropertyNeedsUpdateCallback(IPropertyKey name)
        {
            var beforeValue = GetPropertyObject(name);
            UpdateModifiedPropertyObject(name, beforeValue);
        }

        public IModifiablePropertyTarget Target { get; }
        public IModifierProvider[] Providers { get; }
        private Dictionary<IPropertyKey, object?> fallbackCaches = new Dictionary<IPropertyKey, object?>(new PropertyKeyComparer());
        private List<ModifierSourceItem> modifierContainerBuffer = new List<ModifierSourceItem>();
        private PropertyDictionary properties = new PropertyDictionary();
        private PropertyDictionary modifiedProperties = new PropertyDictionary();
    }
    [Serializable]
    public class SerializableModifiableProperties
    {
        public SerializablePropertyDictionary? properties;
    }
}
