#nullable enable // autogenerated

using MVZ2.Vanilla.Enemies;
using PVZEngine.Buffs;
using PVZEngine.Definitions;
using PVZEngine.Modifiers;

namespace MVZ2.GameContent.Buffs.Enemies
{
    [AutoBuffDefinition(VanillaBuffNames.Enemy.flagzombieEnemySpeed)]
    public class FlagZombieEnemySpeedBuff : BuffDefinition
    {
        public FlagZombieEnemySpeedBuff(string nsp, string name) : base(nsp, name)
        {
            AddModifier(new FloatModifier(VanillaEnemyProps.SPEED, NumberOperator.Add, 1f));
        }
    }
}
