#nullable enable // autogenerated

using System.Xml;
using MVZ2.IO;
using MVZ2Logic.Resources;

namespace MVZ2.Metas
{
    public class BlueprintFunctionMeta
    {
        public BlueprintFunctionMeta(string id)
        {
            ID = id;
        }

        public string ID { get; private set; }
        public SpriteReference? Tag { get; private set; }
        public static BlueprintFunctionMeta? FromXmlNode(XmlNode node, string defaultNsp)
        {
            var id = node.GetAttribute("id");
            if (string.IsNullOrEmpty(id))
            {
                Log.LogError("The ID of a BlueprintFunctionMeta is invalid.");
                return null;
            }

            var icon = node?.GetAttributeSpriteReference("icon", defaultNsp);
            return new BlueprintFunctionMeta(id)
            {
                Tag = icon,
            };
        }
    }
}
