#nullable enable // autogenerated

using System.Collections.Generic;
using PVZEngine.Entities;
using PVZEngine.Level;
using UnityEngine;

namespace PVZEngine.Collisions.Level
{
    public interface ICollisionSystem
    {
        void Update();
        void InitEntity(Entity entity);
        void UpdateEntityDetection(Entity entity);
        void UpdateEntityPosition(Entity entity);
        void UpdateEntitySize(Entity entity);
        void DestroyEntity(Entity entity);
        IEntityCollider? CreateCustomCollider(Entity entity, ColliderConstructor info);
        bool RemoveCollider(Entity entity, string name);
        IEntityCollider? GetCollider(Entity entity, string name);
        void GetCurrentCollisions(Entity entity, List<EntityCollision> collisions);


        ISerializableCollisionSystem ToSerializable();
        void LoadFromSerializable(LevelEngine level, ISerializableCollisionSystem seri);


        IEntityCollider[] OverlapBox(Vector3 center, Vector3 size, OverlapParams param);
        void OverlapBoxNonAlloc(Vector3 center, Vector3 size, OverlapParams param, List<IEntityCollider> results);
        IEntityCollider[] OverlapSphere(Vector3 center, float radius, OverlapParams param);
        void OverlapSphereNonAlloc(Vector3 center, float radius, OverlapParams param, List<IEntityCollider> results);
        IEntityCollider[] OverlapCapsule(Vector3 point0, Vector3 point1, float radius, OverlapParams param);
        void OverlapCapsuleNonAlloc(Vector3 point0, Vector3 point1, float radius, OverlapParams param, List<IEntityCollider> results);
    }

    public struct OverlapParams
    {
        public int faction;
        public int hostileMask;
        public int friendlyMask;
        public bool includeIgnored;

        public OverlapParams(int faction, int hostileMask, int friendlyMask, bool includeIgnored = false)
        {
            this.faction = faction;
            this.hostileMask = hostileMask;
            this.friendlyMask = friendlyMask;
            this.includeIgnored = includeIgnored;
        }
        public static OverlapParams Hostile(int faction, int mask, bool includeIgnored = false)
        {
            return new OverlapParams(faction, mask, 0, includeIgnored);
        }
        public static OverlapParams Friendly(int faction, int mask, bool includeIgnored = false)
        {
            return new OverlapParams(faction, 0, mask, includeIgnored);
        }
        public static OverlapParams AnyFaction(int mask, bool includeIgnored = false)
        {
            return new OverlapParams(0, mask, mask, includeIgnored);
        }
    }
}
