#nullable enable // autogenerated

using MVZ2.Vanilla.Callbacks;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Properties;
using PVZEngine;
using PVZEngine.Buffs;
using PVZEngine.Callbacks;
using PVZEngine.Level;
using Tools;
using UnityEngine;

namespace MVZ2.GameContent.Buffs.Contraptions
{
    [BuffDefinition(VanillaBuffNames.Contraption.ruaWizard)]
    public class RUAWizardBuff : BuffDefinition
    {
        public RUAWizardBuff(string nsp, string name) : base(nsp, name)
        {
            AddTrigger(VanillaLevelCallbacks.POST_ENTITY_SHOT, PostContraptionShotCallback);
        }
        public override void PostAdd(Buff buff)
        {
            base.PostAdd(buff);
            buff.SetProperty(PROP_TIMER, new FrameTimer(MAX_TIMEOUT));
            buff.SetProperty(ADD_DIAGONAL, -1);
        }
        public override void PostUpdate(Buff buff)
        {
            base.PostUpdate(buff);
            var contraption = buff.GetEntity();
            if (contraption == null)
                return;
            var timer = buff.GetProperty<FrameTimer>(PROP_TIMER);
            if (timer.RunToExpiredOrNull())
                buff.Remove();
        }
        private void PostContraptionShotCallback(VanillaLevelCallbacks.PostEntityShootParams param, CallbackResult result)
        {
            var entity = param.source;
            var proj = param.projectile;
            if (entity == null)
                return;
            if (!entity.HasBuff<RUAWizardBuff>())
                return;
            var buff = entity.GetFirstBuff<RUAWizardBuff>()!;
            var diag = buff.GetProperty<int>(ADD_DIAGONAL);
            proj.StartChangingLane(proj.GetLane() + diag);
            diag *= -1;
            buff.SetProperty(ADD_DIAGONAL, diag);
        }
        public static readonly VanillaBuffPropertyMeta<FrameTimer> PROP_TIMER = new VanillaBuffPropertyMeta<FrameTimer>("Timer");
        public static readonly VanillaBuffPropertyMeta<int> ADD_DIAGONAL = new VanillaBuffPropertyMeta<int>("AddDiagonal");
        public const int MAX_TIMEOUT = 900;
        public Vector3 DIAGONAL_1 = Vector3.forward * 10;
        public Vector3 DIAGONAL_2 = Vector3.back * 10;
    }
}
