#nullable enable // autogenerated

using MVZ2.GameContent.Projectiles;
using MVZ2.Vanilla.Audios;
using MVZ2.Vanilla.Contraptions;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Properties;
using MVZ2Logic.Level;
using PVZEngine;
using PVZEngine.Entities;
using PVZEngine.Level;
using Tools;
using UnityEngine;

namespace MVZ2.GameContent.Contraptions
{
    [EntityBehaviourDefinition(VanillaContraptionNames.smallDispenser)]
    public class SmallDispenser : DispenserFamily
    {
        public SmallDispenser(string nsp, string name) : base(nsp, name)
        {
        }

        public override void Init(Entity entity)
        {
            base.Init(entity);
            InitShootTimer(entity);
            SetRepeatTimer(entity, new FrameTimer(15));
        }
        protected override void UpdateAI(Entity entity)
        {
            base.UpdateAI(entity);
            if (!entity.IsEvoked())
            {
                ShootTick(entity);
                int repeatCount = GetRepeatCount(entity);
                if (repeatCount > 0)
                {
                    var repeatTimer = GetRepeatTimer(entity);
                    if (repeatTimer.RunToExpiredAndNotNull(entity.GetAttackSpeed()))
                    {
                        Shoot(entity);
                        SetRepeatCount(entity, repeatCount - 1);
                        repeatTimer.Reset();
                    }
                }
                return;
            }
        }
        public override void OnShootTick(Entity entity)
        {
            int count = 1;
            if (entity.RNG.Next(2) == 0)
                count = 2;
            SetRepeatCount(entity, count);
            var repeatTimer = GetRepeatTimer(entity);
            if (repeatTimer != null)
            {
                repeatTimer.ResetTime(5);
                repeatTimer.Frame = 0;
            }
        }
        public override Entity? Shoot(Entity entity)
        {
            var projectile = base.Shoot(entity);
            if (projectile != null)
            {
                projectile.Timeout = Mathf.CeilToInt(entity.GetRange() / entity.GetShotVelocity().magnitude);
            }
            return projectile;
        }

        protected override void OnEvoke(Entity entity)
        {
            base.OnEvoke(entity);
            var velocity = Vector3.right * 3;
            if (entity.IsFacingLeft())
            {
                velocity.x *= -1;
            }
            entity.ShootProjectile(VanillaProjectileID.largeSnowball, velocity);
            entity.PlaySound(VanillaSoundID.odd);
        }
        public static FrameTimer? GetRepeatTimer(Entity entity) => entity.GetBehaviourField<FrameTimer>(PROP_REPEAT_TIMER);
        public static void SetRepeatTimer(Entity entity, FrameTimer timer) => entity.SetBehaviourField(PROP_REPEAT_TIMER, timer);
        public static int GetRepeatCount(Entity entity) => entity.GetBehaviourField<int>(PROP_REPEAT_COUNT);
        public static void SetRepeatCount(Entity entity, int count) => entity.SetBehaviourField(PROP_REPEAT_COUNT, count);
        public static readonly VanillaEntityPropertyMeta<FrameTimer> PROP_EVOCATION_TIMER = new VanillaEntityPropertyMeta<FrameTimer>("EvocationTimer");
        public static readonly VanillaEntityPropertyMeta<FrameTimer> PROP_REPEAT_TIMER = new VanillaEntityPropertyMeta<FrameTimer>("RepeatTimer");
        public static readonly VanillaEntityPropertyMeta<int> PROP_REPEAT_COUNT = new VanillaEntityPropertyMeta<int>("RepeatCount");
    }
}
