#nullable enable // autogenerated

using MVZ2.GameContent.Models;
using MVZ2.Vanilla.Models;
using MVZ2.Vanilla.Properties;
using MVZ2Logic.Models;
using PVZEngine.Buffs;
using PVZEngine.Definitions;
using PVZEngine.Entities;
using PVZEngine.Modifiers;
using Tools;

namespace MVZ2.GameContent.Buffs.Contraptions
{
    [AutoBuffDefinition(VanillaBuffNames.Entity.crescentAntiGravity)]
    public class CrescentAntiGravityBuff : BuffDefinition
    {
        public CrescentAntiGravityBuff(string nsp, string name) : base(nsp, name)
        {
            AddModifier(new FloatModifier(EngineEntityProps.GRAVITY, NumberOperator.Set, -0.05f));
            AddModelInsertion(LogicModelHelper.ANCHOR_CENTER, VanillaModelKeys.levitationStars, VanillaModelID.levitationStars);
        }
        public override void PostAdd(Buff buff)
        {
            base.PostAdd(buff);
            buff.SetProperty(PROP_TIMER, new FrameTimer(90));
        }

        public override void PostUpdate(Buff buff)
        {
            base.PostUpdate(buff);

            var timer = buff.GetProperty<FrameTimer>(PROP_TIMER);
            if (timer == null || timer.Expired)
            {
                buff.Remove();
            }
            else
                timer.Run();
        }
        public static readonly VanillaBuffPropertyMeta<FrameTimer> PROP_TIMER = new VanillaBuffPropertyMeta<FrameTimer>("Timer");
        public const int MAX_TIMEOUT = 150;
    }
}
