#nullable enable // autogenerated

using System.Linq;
using MVZ2.GameContent.Effects;
using MVZ2.GameContent.Enemies;
using MVZ2.Vanilla.Audios;
using MVZ2.Vanilla.Callbacks;
using MVZ2.Vanilla.Contraptions;
using MVZ2.Vanilla.Entities;
using MVZ2Logic;
using PVZEngine;
using PVZEngine.Callbacks;
using PVZEngine.Entities;
using PVZEngine.Level;
using Tools;
using UnityEngine;

namespace MVZ2.GameContent.Contraptions
{
    [EntityBehaviourDefinition(VanillaContraptionNames.goldenApple)]
    public class GoldenApple : ContraptionBehaviour
    {
        public GoldenApple(string nsp, string name) : base(nsp, name)
        {
            AddTrigger(VanillaLevelCallbacks.POST_ENEMY_MELEE_ATTACK, PostEnemyMeleeAttackCallback);
        }
        public override void Init(Entity entity)
        {
            base.Init(entity);
        }
        protected override void UpdateLogic(Entity entity)
        {
            base.UpdateLogic(entity);
            entity.SetModelProperty("Evoked", entity.IsEvoked());
        }
        protected override void OnEvoke(Entity entity)
        {
            base.OnEvoke(entity);
            entity.SetEvoked(true);
            entity.PlaySound(VanillaSoundID.sparkle);
        }

        private void PostEnemyMeleeAttackCallback(VanillaLevelCallbacks.EnemyMeleeAttackParams param, CallbackResult result)
        {
            var enemy = param.enemy;
            var target = param.target;
            if (!target.IsEntityOf(VanillaContraptionID.goldenApple))
                return;
            if (!target.IsHostile(enemy))
                return;
            if (target.IsAIFrozen())
                return;
            var callbackParam = new EntityCallbackParams(enemy);
            enemy.Level.Triggers.RunCallback(VanillaLevelCallbacks.POST_ENTITY_REINCARNATE, callbackParam);
            if (target.IsEvoked())
            {
                var mutant = target.Spawn(VanillaEnemyID.mutantZombie, enemy.Position)?.Let(e =>
                {
                    e.CharmPermanent(target.GetFaction(), new EntitySourceReference(target));
                });
                enemy.Spawn(VanillaEffectID.mindControlLines, enemy.GetCenter());
                enemy.Neutralize();
                enemy.Remove();
                enemy.PlaySound(VanillaSoundID.charmed);
                enemy.PlaySound(VanillaSoundID.odd);
            }
            else
            {
                var level = target.Level;
                var rng = target.RNG;
                var unlockedEnemies = Global.Saves.GetUnlockedEnemies();
                var validEnemies = unlockedEnemies.Where(id =>
                {
                    if (!Global.Almanac.IsEnemyInAlmanac(id))
                        return false;
                    if (transformFilter.Contains(id))
                        return false;
                    if (enemy.IsEntityOf(id))
                        return false;
                    return true;
                });
                if (validEnemies.Count() <= 0)
                    return;
                var enemyID = validEnemies.Random(rng);
                var offset = higherSpawnPositionFilter.Contains(enemyID) ? SPAWN_POSITION_ADDTION : Vector3.zero;
                var random = target.SpawnWithParams(enemyID, enemy.Position + offset)?.Let(e =>
                {
                    e.CharmPermanent(target.GetFaction(), new EntitySourceReference(target));
                });
                enemy.Spawn(VanillaEffectID.mindControlLines, enemy.GetCenter());
                enemy.Neutralize();
                enemy.Remove();
                enemy.PlaySound(VanillaSoundID.charmed);
                enemy.PlaySound(VanillaSoundID.floop);
            }
            target.Remove();
        }
        private static NamespaceID[] transformFilter = new NamespaceID[]
        {
            VanillaEnemyID.flagZombie,
            VanillaEnemyID.dullahan,
            VanillaEnemyID.hellChariot,
            VanillaEnemyID.mutantZombie,
            VanillaEnemyID.megaMutantZombie,
            VanillaEnemyID.rallyZombie,
        };
        public static NamespaceID[] higherSpawnPositionFilter = new NamespaceID[]
        {
            VanillaEnemyID.undeadFlyingObject,
            VanillaEnemyID.flyingPirate,
        };

        private static readonly Vector3 SPAWN_POSITION_ADDTION = new Vector3(0, 20, 0);
    }
}
