#nullable enable // autogenerated

using MVZ2.GameContent.Detections;
using MVZ2.GameContent.Projectiles;
using MVZ2.Vanilla.Audios;
using MVZ2.Vanilla.Detections;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Projectiles;
using MVZ2.Vanilla.Properties;
using MVZ2Logic.Entities;
using PVZEngine;
using PVZEngine.Definitions;
using PVZEngine.Entities;
using Tools;
using UnityEngine;

namespace MVZ2.GameContent.Contraptions
{
    [AutoEntityBehaviourDefinition(VanillaContraptionNames.stoneDropper)]
    public class StoneDropper : DispenserFamily
    {
        public StoneDropper(string nsp, string name) : base(nsp, name)
        {
        }

        public override void Init(Entity entity)
        {
            base.Init(entity);
            SetRNG(entity, new RandomGenerator(entity.RNG.Next()));
            InitShootTimer(entity);
        }
        protected override void UpdateAI(Entity entity)
        {
            base.UpdateAI(entity);
            if (!entity.IsEvoked())
            {
                ShootTick(entity);
                return;
            }
        }
        public override Entity? Shoot(Entity entity)
        {
            if (entity.RNG.Next(4) == 0)
            {
                var rng = GetRNG(entity);
                NamespaceID id = VanillaProjectileID.boulder;
                float multiplier = BOULDER_DAMAGE_MULTIPLIER;
                if (rng != null && rng.Next(5) == 0)
                {
                    id = VanillaProjectileID.bounceBoulder;
                    multiplier = BOUNCY_BOULDER_DAMAGE_MULTIPLIER;
                }
                var param = entity.GetShootParams();
                param.projectileID = id;
                param.damage = entity.GetDamage() * multiplier;
                return entity.ShootProjectile(param);
            }
            return base.Shoot(entity);
        }
        protected override void OnEvoke(Entity entity)
        {
            base.OnEvoke(entity);
            var rng = entity.RNG;
            for (int i = 0; i < 30; i++)
            {
                var xspeed = entity.GetFacingX() * rng.Next(10f, 18f);
                var yspeed = rng.Next(30f);
                var zspeed = rng.Next(-1.5f, 1.5f);
                var param = entity.GetShootParams();
                param.projectileID = VanillaProjectileID.boulder;
                param.damage = entity.GetDamage() * BOULDER_DAMAGE_MULTIPLIER;
                param.velocity = new Vector3(xspeed, yspeed, zspeed);
                entity.ShootProjectile(param);
            }
            for (int i = -1; i <= 1; i++)
            {
                var xspeed = 15f;
                var yspeed = 10f;
                var param = entity.GetShootParams();
                param.projectileID = VanillaProjectileID.bounceBoulder;
                param.damage = entity.GetDamage() * BOUNCY_BOULDER_DAMAGE_MULTIPLIER;
                param.velocity = new Vector3(xspeed, yspeed, 0);
                entity.ShootProjectile(param)?.Let(e =>
                {
                    int makeupCount = 0;
                    var lane = entity.GetLane() + i;
                    if (lane >= 0 && lane < entity.Level.GetMaxLaneCount())
                    {
                        e.StartChangingLane(lane);
                    }
                    else
                    {
                        makeupCount++;
                        e.Velocity *= 1 + (MAKE_UP_VELOCITY_MULTIPLIER_INCREAMENT * makeupCount);
                    }
                });
            }
            entity.PlaySound(VanillaSoundID.launch);
        }
        protected override Detector GetDetector()
        {
            return new DispenserDetector()
            {
                ignoreHighEnemy = true,
                projectileID = VanillaProjectileID.boulder,
            };
        }
        public static RandomGenerator? GetRNG(Entity boss) => boss.GetBehaviourField<RandomGenerator>(PROP_RNG);
        public static void SetRNG(Entity boss, RandomGenerator value) => boss.SetBehaviourField(PROP_RNG, value);
        public static readonly VanillaEntityPropertyMeta<RandomGenerator> PROP_RNG = new VanillaEntityPropertyMeta<RandomGenerator>("RNG");
        public const float BOULDER_DAMAGE_MULTIPLIER = 2;
        public const float BOUNCY_BOULDER_DAMAGE_MULTIPLIER = 10;
        public const float MAKE_UP_VELOCITY_MULTIPLIER_INCREAMENT = 0.2f;
    }
}
