#nullable enable // autogenerated

using MVZ2.GameContent.Enemies;
using MVZ2.GameContent.Fragments;
using MVZ2.Vanilla.Audios;
using MVZ2.Vanilla.Effects;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Properties;
using MVZ2Logic.Level;
using PVZEngine.Entities;
using PVZEngine.Level;
using UnityEngine;

namespace MVZ2.GameContent.Effects
{
    [EntityBehaviourDefinition(VanillaEffectNames.ghostChain)]
    public class GhostChain : EffectBehaviour
    {

        #region 公有方法
        public GhostChain(string nsp, string name) : base(nsp, name)
        {
        }
        #endregion
        public override void Init(Entity entity)
        {
            base.Init(entity);
            entity.PlaySound(VanillaSoundID.chainsTrap);
            stateMachine.Init(entity);
            stateMachine.StartState(entity, STATE_EXPAND);
        }
        public override void Update(Entity entity)
        {
            base.Update(entity);
            CheckRemove(entity);
            var parent = entity.Parent;
            if (!parent.ExistsAndAlive())
            {
                return;
            }
            entity.Position = parent.GetCenter();
            stateMachine.UpdateAI(entity);
            stateMachine.UpdateLogic(entity);

            var targetID = GetPossessingEntity(entity);
            var target = targetID?.GetEntity(entity.Level);
            entity.SetAnimationFloat("Distance", GetDistance(entity));
            if (target.ExistsAndAlive())
            {
                entity.SetModelProperty("Dest", target.GetCenter());
            }
        }
        public static void CheckRemove(Entity entity)
        {
            var parent = entity.Parent;
            var targetID = GetPossessingEntity(entity);
            var target = targetID?.GetEntity(entity.Level);
            if (!parent.ExistsAndAlive() || !target.ExistsAndAlive())
            {
                entity.CreateFragmentAndPlay(VanillaFragmentID.ghostChain, 50);
                entity.PlaySound(VanillaSoundID.chainsBreak);
                entity.Remove();
            }
            else if (Ghost.ShouldExitPossess(parent, target))
            {
                entity.CreateFragmentAndPlay(VanillaFragmentID.ghostChain, 50);
                entity.PlaySound(VanillaSoundID.chainsBreak);
                entity.Remove();
            }
        }
        public static EntityID? GetPossessingEntity(Entity entity) => entity.GetBehaviourField<EntityID>(PROP_TARGET_ENTITY);
        public static void SetPossessingEntity(Entity entity, EntityID? value) => entity.SetBehaviourField(PROP_TARGET_ENTITY, value);
        public static void SetDistance(Entity entity, float value) => entity.SetProperty(PROP_DESTINATION, value);
        public static float GetDistance(Entity entity) => entity.GetProperty<float>(PROP_DESTINATION);
        public static readonly VanillaEntityPropertyMeta<EntityID> PROP_TARGET_ENTITY = new VanillaEntityPropertyMeta<EntityID>("target_entity");
        public static readonly VanillaEntityPropertyMeta<float> PROP_DESTINATION = new VanillaEntityPropertyMeta<float>("dest");
        public const int STATE_EXPAND = VanillaEffectStates.GHOST_CHAIN_EXPAND;
        public const int STATE_TRAP = VanillaEffectStates.GHOST_CHAIN_TRAP;
        public const int STATE_SUBTRACT = VanillaEffectStates.GHOST_CHAIN_SUBTRACT;

        public EntityStateMachine stateMachine = new GhostChainStateMachine();
        public class GhostChainStateMachine : EntityStateMachine
        {
            public GhostChainStateMachine()
            {
                AddState(new ExpandState());
                AddState(new TrapState());
                AddState(new SubstractState());
            }
        }
        public class ExpandState : EntityStateMachineState
        {
            public ExpandState() : base(STATE_EXPAND)
            {
            }

            // 锁链伸出
            public override void OnEnter(EntityStateMachine machine, Entity entity)
            {
                base.OnEnter(machine, entity);
                var timer = machine.GetStateTimer(entity);
                timer.ResetTime(10);
            }

            public override void OnUpdateLogic(EntityStateMachine machine, Entity entity)
            {
                base.OnUpdateLogic(machine, entity);
                var timer = machine.GetStateTimer(entity);
                timer.Run(machine.GetSpeed(entity));

                var scaleMultiplier = timer.GetPassedPercentage();
                var targetID = GetPossessingEntity(entity);
                var target = targetID?.GetEntity(entity.Level);
                var distance = 140f;
                if (target.ExistsAndAlive())
                {
                    distance = Vector3.Distance(entity.Position, target.GetCenter());
                }
                SetDistance(entity, distance * scaleMultiplier);

                if (timer.Expired)
                {
                    machine.StartState(entity, STATE_TRAP);
                }
            }
        }
        public class TrapState : EntityStateMachineState
        {
            public TrapState() : base(STATE_TRAP)
            {
            }

            // 锁链缠绕怪物
            public override void OnEnter(EntityStateMachine machine, Entity entity)
            {
                base.OnEnter(machine, entity);
                var timer = machine.GetStateTimer(entity);
                timer.ResetTime(30);
                entity.Level.AddLoopSoundEntity(VanillaSoundID.chainsRattle, entity.ID);
            }

            public override void OnUpdateLogic(EntityStateMachine machine, Entity entity)
            {
                base.OnUpdateLogic(machine, entity);
                var timer = machine.GetStateTimer(entity);
                timer.Run(machine.GetSpeed(entity));
                var targetID = GetPossessingEntity(entity);
                var target = targetID?.GetEntity(entity.Level);
                var distance = 140f;
                if (target.ExistsAndAlive())
                {
                    distance = Vector3.Distance(entity.Position, target.GetCenter());
                }
                SetDistance(entity, distance);
                if (timer.Expired)
                {
                    machine.StartState(entity, STATE_SUBTRACT);
                }
            }
        }
        public class SubstractState : EntityStateMachineState
        {
            public SubstractState() : base(STATE_SUBTRACT)
            {
            }

            // 锁链收回并使幽灵附身此怪物
            public override void OnEnter(EntityStateMachine machine, Entity entity)
            {
                base.OnEnter(machine, entity);
                var timer = machine.GetStateTimer(entity);
                timer.ResetTime(5);
            }
            public override void OnExit(EntityStateMachine machine, Entity entity)
            {
                base.OnExit(machine, entity);
            }

            public override void OnUpdateLogic(EntityStateMachine machine, Entity entity)
            {
                base.OnUpdateLogic(machine, entity);
                var timer = machine.GetStateTimer(entity);
                timer.Run(machine.GetSpeed(entity));

                var targetID = GetPossessingEntity(entity);
                var target = targetID?.GetEntity(entity.Level);
                if (target.ExistsAndAlive())
                {
                    SetDistance(entity, Vector3.Distance(entity.Position, target.GetCenter()));
                }

                var parent = entity.Parent;
                if (timer.Expired)
                {
                    entity.Remove();
                    if (parent.ExistsAndAlive() && target.ExistsAndAlive())
                    {
                        Ghost.ActivatePossession(parent);
                        parent.SetCenter(target.GetCenter());
                    }
                }
            }
        }
    }
}