#nullable enable // autogenerated

namespace PVZEngine.Level
{
    public interface IModifiablePropertyTarget
    {
        /// <summary>
        /// 在属性表中不存在某一属性时，退化而返回的某些数值。
        /// </summary>
        /// <param name="name">属性键。</param>
        /// <param name="value">返回的数值。</param>
        /// <returns>是否成功返回。</returns>
        bool GetFallbackProperty(IPropertyKey name, out object? value);
        /// <summary>
        /// 在某个属性发生变动时触发的回调。
        /// </summary>
        /// <param name="name">属性键。</param>
        /// <param name="beforeValue">该属性之前的值。</param>
        /// <param name="afterValue">该属性之后的值。</param>
        /// <param name="triggersEvaluation">是否会触发某些属性的重新评估。如最大生命值变化后，当前生命值等比例缩放。</param>
        void OnPropertyChanged(IPropertyKey name, object? beforeValue, object? afterValue, bool triggersEvaluation);
    }
}
