#nullable enable // autogenerated

using System.Linq;
using MVZ2.GameContent.Buffs.Projectiles;
using MVZ2.GameContent.Contraptions;
using MVZ2.Vanilla.Callbacks;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Projectiles;
using PVZEngine.Buffs;
using PVZEngine.Callbacks;
using PVZEngine.Definitions;
using PVZEngine.Entities;
using UnityEngine;

namespace MVZ2.GameContent.Projectiles
{
    [AutoEntityBehaviourDefinition(VanillaProjectileNames.arrowBundle)]
    public class ArrowBundle : EntityBehaviourDefinition
    {
        public ArrowBundle(string nsp, string name) : base(nsp, name)
        {
            AddTrigger(VanillaLevelCallbacks.POST_PROJECTILE_HIT, PostHitEntityCallback);
        }
        private void PostHitEntityCallback(VanillaLevelCallbacks.PostProjectileHitParams param, CallbackResult result)
        {
            var hitResult = param.hit;
            var projectile = hitResult.Projectile;
            if (!projectile.Definition.HasBehaviour(this))
                return;
            var damageOutput = param.damage;
            if (damageOutput == null)
                return;
            var other = hitResult.Other;
            var lane = projectile.GetLane();
            for (int i = 0; i < 2; i++)
            {
                var laneOffset = i * 2 - 1;
                var l = Mathf.Clamp(lane + laneOffset, 0, projectile.Level.GetMaxLaneCount() - 1);
                var shootParam = projectile.GetShootParams();
                shootParam.projectileID = VanillaProjectileID.arrow;
                shootParam.position = projectile.GetCenter();
                shootParam.pivot = VanillaEntityProps.SHOT_PIVOT_BOTTOM;
                shootParam.velocity = projectile.Velocity;
                other.ShootProjectile(shootParam)?.Let(p =>
                {
                    p.StartChangingLane(l);
                    if (projectile.HasBuff<HellfireIgnitedBuff>())
                    {
                        bool cursed = projectile.GetBuffs<HellfireIgnitedBuff>().Any(b => HellfireIgnitedBuff.GetCursed(b));
                        var behaviour = p.Definition?.GetBehaviour<IHellfireIgniteBehaviour>();
                        behaviour?.Ignite(p, projectile, cursed);
                    }
                });
            }
        }
    }
}
