#nullable enable // autogenerated

using System.Linq;
using MVZ2.GameContent.Buffs;
using MVZ2.Vanilla.Audios;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Properties;
using MVZ2Logic;
using MVZ2Logic.Artifacts;
using MVZ2Logic.Level;
using PVZEngine;
using PVZEngine.Buffs;
using PVZEngine.Entities;
using Tools;
using UnityEngine;

namespace MVZ2.GameContent.Artifacts
{
    [ArtifactDefinition(VanillaArtifactNames.endlessGate)]
    public class EndlessGate : ArtifactDefinition
    {
        public EndlessGate(string nsp, string name) : base(nsp, name)
        {
        }
        public override void PostAdd(Artifact artifact)
        {
            base.PostAdd(artifact);
            var timer = new FrameTimer(Ticks.FromSeconds(COOLDOWN_SECONDS))
            {
                Frame = 0
            };
            artifact.SetProperty(PROP_ACTIVE_COOLDOWN, timer);
        }
        public override void PostUpdate(Artifact artifact)
        {
            base.PostUpdate(artifact);
            var timer = artifact.GetProperty<FrameTimer>(PROP_ACTIVE_COOLDOWN);
            bool active = timer.RunToExpiredAndNotNull();
            artifact.SetGlowing(active);
            if (timer != null)
            {
                artifact.SetDisplayText(Mathf.FloorToInt(Ticks.ToSeconds(timer.Frame)).ToString() + "s");
                if (timer.Expired)
                {
                    artifact.SetDisplayText(string.Empty);
                }
            }

            if (active)
            {
                var xOrderedMobsTake1 = artifact.Level.FindEntities(e => e.Type == EntityTypes.ENEMY && !e.IsDead && e.IsHostileEntity()).OrderBy(e => e.Position.x).Take(1);
                foreach (var enemy in xOrderedMobsTake1)
                {
                    var bound = enemy.GetBounds();
                    if (bound.min.x < TRIGGER_X)
                    {
                        enemy.PlaySound(VanillaSoundID.revertWarp);
                        enemy.AddBuff(VanillaBuffID.Enemy.endlessGate);
                        artifact.Highlight();
                        timer?.Reset();
                    }
                }
            }
        }
        public const float TRIGGER_X = 260;
        public const int COOLDOWN_SECONDS = 40;
        public static readonly VanillaArtifactPropertyMeta<FrameTimer> PROP_ACTIVE_COOLDOWN = new VanillaArtifactPropertyMeta<FrameTimer>("active_cooldown");
    }
}


