#nullable enable // autogenerated

using MVZ2.GameContent.Contraptions;
using MVZ2.GameContent.Seeds;
using MVZ2.Vanilla.Callbacks;
using MVZ2.Vanilla.Contraptions;
using MVZ2Logic.Blueprints;
using MVZ2Logic.Callbacks;
using MVZ2Logic.Level;
using MVZ2Logic.Modding;
using PVZEngine;
using PVZEngine.Callbacks;
using PVZEngine.Entities;
using PVZEngine.Level;

namespace MVZ2.GameContent.GlobalCallbacks
{
    [ModGlobalCallbacks]
    public class BlueprintGlobalCallbacks : VanillaGlobalCallbacks
    {
        public override void Apply(Mod mod)
        {
            mod.AddTrigger(LogicLevelCallbacks.POST_USE_ENTITY_BLUEPRINT, PostUseEntityBlueprintCallback);
            mod.AddTrigger(LogicCallbacks.GET_BLUEPRINT_STYLE, GetBlueprintStyleCallback);
            mod.AddTrigger(LogicCallbacks.GET_BLUEPRINT_FUNCTION, GetBlueprintFunctionCallback);
        }
        private void PostUseEntityBlueprintCallback(LogicLevelCallbacks.PostUseEntityBlueprintParams param, CallbackResult callbackResult)
        {
            var output = param.placeOutput;
            var entity = output.entity;
            var seed = param.blueprint;
            var definition = param.definition;
            var heldData = param.heldData;
            if (entity == null)
                return;
            if (heldData.IsInstantTrigger() && entity.CanTrigger())
            {
                entity.Trigger();
            }
            if (heldData.IsInstantEvoke() && entity.CanEvoke() && entity.Level.GetStarshardCount() > 0 && !entity.Level.IsStarshardDisabled())
            {
                entity.Level.AddStarshardCount(-1);
                entity.Evoke();
                entity.Level.Triggers.RunCallbackFiltered(VanillaLevelCallbacks.POST_USE_STARSHARD, new EntityCallbackParams(entity), entity.GetDefinitionID());
            }
            if (seed != null)
            {
                var drawnFromPool = seed.GetDrawnConveyorSeed();
                if (NamespaceID.IsValid(drawnFromPool))
                {
                    if (output.increaseTakenConveyorSeed)
                    {
                        entity.AddTakenConveyorSeed(drawnFromPool);
                    }
                    else
                    {
                        entity.Level.PutSeedToConveyorDiscardPile(drawnFromPool);
                    }
                }
                seed.SetDrawnConveyorSeed(null);
            }
        }
        private void GetBlueprintStyleCallback(LogicCallbacks.GetBlueprintStyleParams param, CallbackResult result)
        {
            var definition = param.blueprintDefinition;
            var seedID = definition.GetID();
            if (seedID == LogicBlueprintID.FromEntity(VanillaContraptionID.commandBlock) || param.isCommandBlock)
            {
                result.SetValue(LogicBlueprintStyles.commandBlock);
            }
            else if (definition.IsUpgradeBlueprint())
            {
                result.SetValue(LogicBlueprintStyles.upgrade);
            }
        }
        private void GetBlueprintFunctionCallback(LogicCallbacks.GetBlueprintFunctionParams param, CallbackResult result)
        {
            var definition = param.blueprintDefinition;
            var function = definition.GetFunction();
            if (function == VanillaBlueprintFunctions.shooter) result.SetValue(LogicBlueprintFunctions.shooter);
            else if (function == VanillaBlueprintFunctions.producer) result.SetValue(LogicBlueprintFunctions.producer);
            else if (function == VanillaBlueprintFunctions.defender) result.SetValue(LogicBlueprintFunctions.defender);
            else if (function == VanillaBlueprintFunctions.assistance) result.SetValue(LogicBlueprintFunctions.assistance);
            else if (function == VanillaBlueprintFunctions.melee) result.SetValue(LogicBlueprintFunctions.melee);
            else if (function == VanillaBlueprintFunctions.bomb) result.SetValue(LogicBlueprintFunctions.bomb);
            else if (function == VanillaBlueprintFunctions.combustor) result.SetValue(LogicBlueprintFunctions.combustor);
            else if (function == VanillaBlueprintFunctions.sharpener) result.SetValue(LogicBlueprintFunctions.sharpener);
            else if (function == VanillaBlueprintFunctions.enchanted) result.SetValue(LogicBlueprintFunctions.enchanted);
            else if (function == VanillaBlueprintFunctions.potion) result.SetValue(LogicBlueprintFunctions.potion);
            else if (function == VanillaBlueprintFunctions.armed) result.SetValue(LogicBlueprintFunctions.armed);
            else if (function == VanillaBlueprintFunctions.buzzer) result.SetValue(LogicBlueprintFunctions.buzzer);
            else if (function == VanillaBlueprintFunctions.frosty) result.SetValue(LogicBlueprintFunctions.frosty);
            else if (function == VanillaBlueprintFunctions.flourish) result.SetValue(LogicBlueprintFunctions.flourish);
            else if (function == VanillaBlueprintFunctions.monster) result.SetValue(LogicBlueprintFunctions.monster);
            else result.SetValue(LogicBlueprintFunctions.undefined);
        }
    }
}
