#nullable enable // autogenerated

using MVZ2.GameContent.Damages;
using MVZ2.GameContent.Effects;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Properties;
using MVZ2Logic.Grids;
using PVZEngine.Damages;
using PVZEngine.Definitions;
using PVZEngine.Entities;

namespace MVZ2.GameContent.Enemies
{
    [AutoEntityBehaviourDefinition(VanillaEntityBehaviourNames.hurtInWater)]
    public class HurtInWaterBehaviour : EntityBehaviourDefinition
    {
        public HurtInWaterBehaviour(string nsp, string name) : base(nsp, name)
        {
        }
        public override void Update(Entity entity)
        {
            base.Update(entity);
            var interval = entity.GetProperty<int>(PROP_BURN_INTERVAL);
            if (entity.IsTimeInterval(interval) && (entity.IsInWater() || entity.Level.EntityExists(e => e.IsEntityOf(VanillaEffectID.rain))))
            {
                var effects = new DamageEffectList(VanillaDamageEffects.SELF_DAMAGE, VanillaDamageEffects.IGNORE_ARMOR, VanillaDamageEffects.MUTE);
                entity.TakeDamage(entity.GetProperty<float>(PROP_BURN_DAMAGE), effects, entity);
            }
        }
        public static readonly VanillaEntityPropertyMeta<int> PROP_BURN_INTERVAL = new VanillaEntityPropertyMeta<int>("burn_interval", 15);
        public static readonly VanillaEntityPropertyMeta<float> PROP_BURN_DAMAGE = new VanillaEntityPropertyMeta<float>("burn_damage", 20f);
    }
}
