#nullable enable // autogenerated

using System.Linq;
using MVZ2.GameContent.Enemies;
using MVZ2.Vanilla.Audios;
using MVZ2.Vanilla.Callbacks;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Properties;
using MVZ2Logic.Entities;
using MVZ2Logic.Level;
using PVZEngine;
using PVZEngine.Callbacks;
using PVZEngine.Definitions;
using PVZEngine.Entities;
using Tools;

namespace MVZ2.GameContent.Obstacles
{
    [AutoEntityBehaviourDefinition(VanillaObstacleNames.grave)]
    public class Grave : ObstacleBehaviour
    {
        public Grave(string nsp, string name) : base(nsp, name)
        {
            AddTrigger(VanillaLevelCallbacks.POST_ENEMY_FAINT, PostEnemyFaintCallback);
        }
        public override void Init(Entity entity)
        {
            base.Init(entity);
            SetReviveCooldown(entity, TimerHelper.NewSecondTimer(1));
        }
        public override void Update(Entity entity)
        {
            base.Update(entity);
            var cooldown = GetReviveCooldown(entity);
            if (cooldown.RunToExpiredAndNotNull())
            {
                ReviveEnemy(entity, VanillaEnemyID.zombieSpectre);
            }
            SetActive(entity, GetSouls(entity) >= 2);
            entity.SetAnimationBool("Active", IsActive(entity));
        }
        private void PostEnemyFaintCallback(EntityCallbackParams param, CallbackResult result)
        {
            var entity = param.entity;
            if (entity.IsEntityOf(VanillaEnemyID.zombieSpectre))
                return;
            var level = entity.Level;
            var graves = level.FindEntities(e => e.Definition.HasBehaviour(this) && e.GetLane() == entity.GetLane() && entity.IsFriendly(e));
            var chosenGrave = graves.RandomTake(1, entity.RNG);
            foreach (var grave in chosenGrave)
            {
                AddSoul(grave);
            }
        }
        private void ReviveEnemy(Entity grave, NamespaceID id)
        {
            var cooldown = GetReviveCooldown(grave);
            if (!IsActive(grave))
                return;
            var pos = grave.Position;
            grave.SpawnWithParams(id, pos)?.Let(e =>
            {
                RemoveSoul(grave);
                e.PlaySound(VanillaSoundID.revived);
            });
            cooldown?.Reset();
        }
        public static FrameTimer? GetReviveCooldown(Entity entity) => entity.GetBehaviourField<FrameTimer>(PROP_REVIVE_COOLDOWN);
        public static void SetReviveCooldown(Entity entity, FrameTimer timer) => entity.SetBehaviourField(PROP_REVIVE_COOLDOWN, timer);
        public static int GetSouls(Entity entity) => entity.GetBehaviourField<int>(PROP_SOUL_COUNT);
        public static void SetSouls(Entity entity, int timer) => entity.SetBehaviourField(PROP_SOUL_COUNT, timer);
        public static void AddSoul(Entity entity) => SetSouls(entity, GetSouls(entity) + 1);
        public static void RemoveSoul(Entity entity) => SetSouls(entity, GetSouls(entity) - 2);
        public static bool IsActive(Entity entity) => entity.GetBehaviourField<bool>(PROP_ACTIVE);
        public static void SetActive(Entity entity, bool value) => entity.SetBehaviourField(PROP_ACTIVE, value);
        private static readonly VanillaEntityPropertyMeta<bool> PROP_ACTIVE = new VanillaEntityPropertyMeta<bool>("active");
        private static readonly VanillaEntityPropertyMeta<FrameTimer> PROP_REVIVE_COOLDOWN = new VanillaEntityPropertyMeta<FrameTimer>("ReviveCooldown");
        private static readonly VanillaEntityPropertyMeta<int> PROP_SOUL_COUNT = new VanillaEntityPropertyMeta<int>("soul_count");
    }
}
