#nullable enable // autogenerated

using MVZ2.GameContent.Shells;
using PVZEngine.Buffs;
using PVZEngine.Definitions;
using PVZEngine.Entities;
using PVZEngine.Modifiers;

namespace MVZ2.GameContent.Buffs.Bosses
{
    [AutoBuffDefinition(VanillaBuffNames.Boss.lockedChestTempered)]
    public class LockedChestTemperedBuff : BuffDefinition
    {
        public LockedChestTemperedBuff(string nsp, string name) : base(nsp, name)
        {
            AddModifier(new NamespaceIDModifier(EngineEntityProps.SHELL, SetOperator.Set, VanillaShellID.metal));
        }
    }
}
