#nullable enable // autogenerated

using System.Collections.Generic;
using MVZ2.GameContent.Buffs;
using PVZEngine.Auras;
using PVZEngine.Buffs;
using PVZEngine.Entities;
using PVZEngine.Level;

namespace MVZ2.GameContent.Enemies
{
    [EntityBehaviourDefinition(VanillaEnemyNames.rallyZombie)]
    public class RallyZombie : FlagZombie
    {
        public RallyZombie(string nsp, string name) : base(nsp, name)
        {
            AddAura(new FlagAura());
        }
        public class FlagAura : AuraEffectDefinition
        {
            public FlagAura() : base(VanillaBuffID.Enemy.flagzombieEnemySpeed, 5)
            {
            }

            public override void GetAuraTargets(AuraEffect auraEffect, List<IBuffTarget> results)
            {
                var source = auraEffect.Source;
                var level = source.GetLevel();
                var entity = source.GetEntity();
                if (entity == null)
                    return;
                if (entity.IsDead)
                    return;
                detectBuffer.Clear();
                level.FindEntitiesNonAlloc(e => e.IsFriendly(entity) && e.Type == EntityTypes.ENEMY, detectBuffer);
                foreach (var cherish in detectBuffer)
                {
                    results.Add(cherish);
                }
            }
            private List<Entity> detectBuffer = new List<Entity>();
        }
    }
}
