#nullable enable // autogenerated

using System.Linq;
using MVZ2.GameContent.Buffs.Enemies;
using MVZ2.GameContent.Damages;
using MVZ2.Vanilla.Audios;
using MVZ2.Vanilla.Callbacks;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Properties;
using MVZ2.Vanilla.Shells;
using MVZ2Logic.Entities;
using PVZEngine.Buffs;
using PVZEngine.Callbacks;
using PVZEngine.Damages;
using PVZEngine.Definitions;
using PVZEngine.Modifiers;
using UnityEngine;

namespace MVZ2.GameContent.Buffs.Projectiles
{
    [AutoBuffDefinition(VanillaBuffNames.Projectile.teslaCoilElectrify)]
    public class TeslaCoilElectrifiedBuff : BuffDefinition
    {
        public TeslaCoilElectrifiedBuff(string nsp, string name) : base(nsp, name)
        {
            AddModifier(new BooleanModifier(LogicEntityProps.IS_LIGHT_SOURCE, true));
            AddModifier(new Vector3Modifier(LogicEntityProps.LIGHT_RANGE, NumberOperator.Add, PROP_LIGHT_RANGE_ADDITION));
            AddModifier(ColorModifier.Override(LogicEntityProps.LIGHT_COLOR, new Color(0, 0.7f, 1)));
            AddTrigger(VanillaLevelCallbacks.POST_PROJECTILE_HIT, PostProjectileHitCallback);
        }
        public override void PostAdd(Buff buff)
        {
            base.PostAdd(buff);
            UpdateLightRange(buff);
        }
        public override void PostUpdate(Buff buff)
        {
            base.PostUpdate(buff);
            UpdateLightRange(buff);
        }
        private void UpdateLightRange(Buff buff)
        {
            var entity = buff.GetEntity();
            float scale = 1;
            if (entity != null)
            {
                var scaledSize = entity.GetScaledSize();
                var scaleVec = scaledSize / DEFAULT_SCALE;
                scale = Mathf.Max(scaleVec.x, scaleVec.y, scaleVec.z);
            }
            buff.SetProperty(PROP_LIGHT_RANGE_ADDITION, Vector3.one * 20 * scale);
        }
        private void PostProjectileHitCallback(VanillaLevelCallbacks.PostProjectileHitParams param, CallbackResult result)
        {
            var hit = param.hit;
            var projectile = hit.Projectile;
            var target = hit.Other;
            var shield = hit.Shield;
            var armorSlot = shield != null ? shield.Slot : null;
            float additionalDamage = projectile.GetDamage();
            var buffs = projectile.GetBuffs(this);
            bool playSound = false;
            foreach (var buff in buffs)
            {
                var output = target.TakeDamage(additionalDamage, new DamageEffectList(VanillaDamageEffects.LIGHTNING), projectile, armorSlot);
                if (output == null)
                    continue;
                var insulator = output.GetAllResults().Any(e => e?.ShellDefinition?.IsInsulator() ?? false);
                if (armorSlot == null && !insulator)
                {
                    var eBuff = target.NewBuff<ElectricChainBuff>();
                    eBuff.SetProperty(ElectricChainBuff.PROP_DAMAGE, projectile.GetDamage() * (1 - ElectricChainBuff.DMG_DECAY));
                    eBuff.SetProperty(ElectricChainBuff.PROP_FACTION, projectile.GetFaction());
                    target.AddBuff(eBuff);
                    playSound = true;
                }
            }
            if (playSound)
            {
                target.PlaySound(VanillaSoundID.redLightning);
            }
        }
        public static readonly VanillaBuffPropertyMeta<Vector3> PROP_LIGHT_RANGE_ADDITION = new VanillaBuffPropertyMeta<Vector3>("light_range_addition");
        public const float DEFAULT_SCALE = 32;
    }
}
