#nullable enable // autogenerated

using System.Linq;
using MVZ2.GameContent.Entities;
using MVZ2.GameContent.Obstacles;
using MVZ2.Vanilla.Audios;
using MVZ2.Vanilla.Enemies;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Properties;
using MVZ2Logic.Entities;
using MVZ2Logic.Level;
using PVZEngine.Definitions;
using PVZEngine.Entities;
using Tools;

namespace MVZ2.GameContent.Enemies
{
    [AutoEntityBehaviourDefinition(VanillaEnemyNames.graveWarden)]
    public class GraveWarden : AIEntityBehaviour
    {
        public GraveWarden(string nsp, string name) : base(nsp, name)
        {
        }
        public override void Init(Entity entity)
        {
            base.Init(entity);
        }
        protected override void UpdateAI(Entity enemy)
        {
            base.UpdateAI(enemy);
            switch (enemy.State)
            {
                case STATE_PLACE:
                    UpdatePlace(enemy);
                    break;
                default:
                    UpdateNotPlace(enemy);
                    break;
            }
        }
        private void UpdatePlace(Entity enemy)
        {
            var timer = GetPlaceTimer(enemy);
            if (timer == null)
            {
                timer = new FrameTimer(PLACE_GRAVE_FRAMES);
                SetPlaceTimer(enemy, timer);
            }
            if (timer.RunToExpired(enemy.GetAttackSpeed()))
            {
                PlaceGrave(enemy);
                timer.Reset();
            }
        }
        private void UpdateNotPlace(Entity enemy)
        {
            var timer = GetPlaceTimer(enemy);
            if (timer != null)
            {
                timer.Reset();
            }
        }
        protected override void UpdateLogic(Entity entity)
        {
            base.UpdateLogic(entity);
            entity.SetModelProperty("NoGrave", IsNoGrave(entity));
        }
        public static void PlaceGrave(Entity enemy)
        {
            var grid = enemy.GetGrid();
            if (grid == null)
                return;
            enemy.PlaySound(VanillaSoundID.stone);
            enemy.SpawnWithParams(VanillaObstacleID.grave, grid.GetEntityPosition());
            SetNoGrave(enemy, true);
        }
        public static bool CanPlaceGrave(Entity enemy)
        {
            if (IsNoGrave(enemy))
                return false;
            var grid = enemy.GetGrid();
            if (grid == null)
                return false;
            if (grid.GetEntities().Any(e => e.Type == EntityTypes.OBSTACLE))
                return false;
            return true;
        }
        public const int PLACE_GRAVE_FRAMES = 30;
        public static bool IsNoGrave(Entity enemy) => enemy.GetProperty<bool>(PROP_NO_GRAVE);
        public static void SetNoGrave(Entity enemy, bool value) => enemy.SetProperty(PROP_NO_GRAVE, value);
        public static FrameTimer? GetPlaceTimer(Entity enemy) => enemy.GetBehaviourField<FrameTimer>(PROP_PLACE_TIMER);
        public static void SetPlaceTimer(Entity enemy, FrameTimer? value) => enemy.SetBehaviourField(PROP_PLACE_TIMER, value);
        public static readonly VanillaEntityPropertyMeta<bool> PROP_NO_GRAVE = new VanillaEntityPropertyMeta<bool>("no_grave");
        public static readonly VanillaEntityPropertyMeta<FrameTimer> PROP_PLACE_TIMER = new VanillaEntityPropertyMeta<FrameTimer>("place_timer");
        public const int STATE_PLACE = VanillaEnemyStates.GRAVE_WARDEN_PLACE;
    }
        
}
