#nullable enable // autogenerated

using MVZ2.GameContent.Damages;
using MVZ2.GameContent.Effects;
using MVZ2.GameContent.Entities;
using MVZ2.Vanilla.Audios;
using MVZ2.Vanilla.Enemies;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Properties;
using MVZ2Logic.Contents.Enemies;
using MVZ2Logic.Entities;
using MVZ2Logic.Level;
using PVZEngine.Damages;
using PVZEngine.Definitions;
using PVZEngine.Entities;
using PVZEngine.Modifiers;

namespace MVZ2.GameContent.Enemies
{
    [AutoEntityBehaviourDefinition(VanillaEnemyNames.zombieCatCart)]
    public class ZombieCatCart : AIEntityBehaviour, IDestroyBySpikesEntityBehaviour, IDeathEffectsBehaviour
    {
        public ZombieCatCart(string nsp, string name) : base(nsp, name)
        {
            AddModifier(new FloatModifier(VanillaEnemyProps.SPEED, NumberOperator.Multiply, PROP_SPEED_MULTIPLIER));
        }
        protected override void UpdateAI(Entity entity)
        {
            base.UpdateAI(entity);
            var passenger = entity.GetRideablePassenger();
            if (passenger == null || (passenger.IsDead && !passenger.AssumeAlive()))
            {
                if (!IsMotoring(entity) && entity.ExistsAndAlive())
                {
                    entity.PlaySound(VanillaSoundID.motor);
                }
                SetMotoring(entity, true);
            }
        }
        protected override void UpdateLogic(Entity entity)
        {
            base.UpdateLogic(entity);
            float speedMultiplier = 1f;
            if (IsMotoring(entity))
            {
                speedMultiplier = 6f;
            }
            entity.SetProperty(PROP_SPEED_MULTIPLIER, speedMultiplier);
            entity.SetAnimationFloat("AnimationSpeed", entity.IsAIFrozen() ? 0 : speedMultiplier);
            entity.SetModelProperty("Motor", IsMotoring(entity));
        }
        public override void PostCollision(EntityCollision collision, int state)
        {
            base.PostCollision(collision, state);
            if (state == EntityCollisionHelper.STATE_EXIT)
                return;
            if (!collision.Collider.IsForMain())
                return;
            var other = collision.Other;
            var cart = collision.Entity;
            if (!cart.IsHostile(other))
                return;

            if (other.IsVulnerableEntity())
            {
                if (!IsMotoring(cart))
                {
                    HellChariot.Crush(cart, collision.OtherCollider);
                }
                else if (other.GetVehicleInteraction() != VehicleInteraction.IGNORE)
                {
                    var crushDamageEffects = new DamageEffectList(VanillaDamageEffects.GRIND);
                    other.TakeDamage(cart.GetDamage() * 18, crushDamageEffects, cart);
                    var selfDamageEffects = new DamageEffectList(VanillaDamageEffects.SELF_DAMAGE, VanillaDamageEffects.INSTA_KILL);
                    cart.Die(selfDamageEffects, cart);
                }
            }
        }
        public override void PostDeath(Entity entity, DeathInfo info)
        {
            base.PostDeath(entity, info);
            if (!entity.WillRemoveOnDeath(info))
            {
                if (IsMotoring(entity))
                {
                    Explosion.Spawn(entity, entity.GetCenter(), 60);
                    entity.PlaySound(VanillaSoundID.largeExplosion);
                }
                entity.Spawn(VanillaEffectID.boneParticles, entity.GetCenter());
                entity.Remove();
            }
        }
        public bool CanBeDestroyedBySpikes(Entity entity, Entity source)
        {
            return entity.ExistsAndAlive();
        }
        public void DestroyBySpikes(Entity entity, Entity source)
        {
            var killEffects = new DamageEffectList(VanillaDamageEffects.INSTA_KILL);
            entity.Die(killEffects, source);
        }
        public void DeathEffects(Entity entity, DeathInfo info)
        {
            for (var i = 0; i < entity.RNG.Next(1, 5); i++)
            {
                entity.SpawnWithParams(VanillaEnemyID.wispFly, entity.GetCenter());
            }
        }
        public static bool IsMotoring(Entity entity) => entity.GetBehaviourField<bool>(FIELD_MOTOR);
        public static void SetMotoring(Entity entity, bool value) => entity.SetBehaviourField(FIELD_MOTOR, value);
        public static readonly VanillaEntityPropertyMeta<float> PROP_SPEED_MULTIPLIER = new VanillaEntityPropertyMeta<float>("SpeedMultiplier");
        private static readonly VanillaEntityPropertyMeta<bool> FIELD_MOTOR = new VanillaEntityPropertyMeta<bool>("motor");
    }
}
