#nullable enable // autogenerated

using MVZ2.Vanilla.Entities;
using PVZEngine.Callbacks;
using PVZEngine.Damages;
using PVZEngine.Definitions;

namespace MVZ2.GameContent.Bosses
{
    [AutoEntityBehaviourDefinition(VanillaEntityBehaviourNames.bossResistance_TheGiant)]
    public partial class BossResistance_TheGiant : BossResistance
    {
        public BossResistance_TheGiant(string nsp, string name) : base(nsp, name)
        {
        }
        public override void PreTakeDamage(DamageInput damageInfo, CallbackResult result)
        {
            var entity = damageInfo.Entity;
            var malleable = TheGiant.GetMalleable(entity);
            bool phase1 = TheGiant.GetPhase(entity) == TheGiant.PHASE_1;
            if (malleable >= 0)
            {
                damageInfo.Multiply(1 - malleable / (phase1 ? TheGiant.MAX_MALLEABLE_DAMAGE : TheGiant.MAX_MALLEABLE_DAMAGE_PHASE_2_3));
            }
            base.PreTakeDamage(damageInfo, result);
        }
    }
}
