#nullable enable // autogenerated

using MVZ2.GameContent.Effects;
using MVZ2.Vanilla.Entities;
using PVZEngine.Callbacks;
using PVZEngine.Damages;
using PVZEngine.Entities;
using PVZEngine.Level;
using UnityEngine;

namespace MVZ2.GameContent.Bosses
{
    [EntityBehaviourDefinition(VanillaEntityBehaviourNames.bossResistance_Seija)]
    public partial class BossResistance_Seija : BossResistance
    {
        public BossResistance_Seija(string nsp, string name) : base(nsp, name)
        {
        }
        public override void PreTakeDamage(DamageInput damageInfo, CallbackResult result)
        {
            var boss = damageInfo.Entity;
            var jizo = Seija.GetJizo(boss);
            if (jizo.ExistsAndAlive())
            {
                jizo.TakeDamageSourced(damageInfo.Amount, damageInfo.Effects, damageInfo.Source);
                boss.Spawn(VanillaEffectID.smokeCluster, boss.GetCenter())?.Let(e =>
                {
                    e.SetSize(Vector3.one * 80);
                    e.SetTint(new Color(0.5f, 0.5f, 0.5f, 0.5f));
                });
                result.SetFinalValue(false);
                return;
            }
            if (damageInfo.Amount >= 600)
            {
                if (Seija.CanUseFabric(boss))
                {
                    Seija.UseFabric(boss);
                }
                else if (Seija.CanUseLantern(boss))
                {
                    Seija.UseLantern(boss);
                }
            }
            if (boss.State == Seija.STATE_FABRIC || boss.State == Seija.STATE_LANTERN)
            {
                result.SetFinalValue(false);
                return;
            }
            base.PreTakeDamage(damageInfo, result);
        }
    }
}
