#nullable enable // autogenerated

using System.Collections.Generic;
using MVZ2.GameContent.Buffs;
using MVZ2.Vanilla.Callbacks;
using MVZ2Logic.Artifacts;
using MVZ2Logic.Definitions;
using MVZ2Logic.Level;
using PVZEngine.Auras;
using PVZEngine.Buffs;
using PVZEngine.Callbacks;

namespace MVZ2.GameContent.Artifacts
{
    [AutoArtifactDefinition(VanillaArtifactNames.create)]
    public class Create : ArtifactDefinition
    {
        public Create(string nsp, string name) : base(nsp, name)
        {
            AddAura(new StarshardAura());
            AddTrigger(VanillaLevelCallbacks.POST_STARSHARD_RECHARGE, PostStarshardRechargeCallback);
        }
        private void PostStarshardRechargeCallback(SeedPackCallbackParams param, CallbackResult result)
        {
            var seed = param.seedPack;
            var level = seed.Level;
            var artifacts = level.GetArtifacts();
            foreach (var artifact in artifacts)
            {
                if (artifact == null)
                    continue;
                if (artifact.Definition != this)
                    continue;
                artifact.Highlight();
            }
        }
        public class StarshardAura : AuraEffectDefinition
        {
            public StarshardAura() : base(VanillaBuffID.Level.create)
            {
            }

            public override void GetAuraTargets(AuraEffect auraEffect, List<IBuffTarget> results)
            {
                results.Add(auraEffect.Source.GetLevel());
            }
        }
    }
}
