#nullable enable // autogenerated

using System;
using System.Collections.Generic;
using System.Linq;
using PVZEngine.Modifiers;

namespace PVZEngine.Entities
{
    public sealed partial class Entity : IModifierSource, IModifierProvider
    {
        private void ReevaluateModifierCaches()
        {
            modifierLibrary.ClearModifierCaches();
            modifierLibrary.AddModifierCaches(Definition.GetModifiers().Select(m => new ModifierSourceItem(this, m)));
        }
        private void OnModifiedPropertyNeedsUpdateCallback(IPropertyKey name)
        {
            OnModifiedPropertyNeedsUpdate?.Invoke(name);
        }
        #region 接口实现
        T? IModifierSource.GetProperty<T>(PropertyKey<T> name) where T : default => GetProperty<T>(name);
        IEnumerable<IPropertyKey> IModifierProvider.GetModifiedProperties()
        {
            return modifierLibrary.GetModifyPropertyKeys();
        }
        void IModifierProvider.GetModifiersForProperty(IPropertyKey name, List<ModifierSourceItem> results)
        {
            modifierLibrary.GetModifierItemsForProperty(name, results);
        }
        #endregion

        #region 事件
        public event Action<IPropertyKey>? OnModifiedPropertyNeedsUpdate;
        #endregion

        #region 属性字段
        private ModifierLibrary modifierLibrary;
        #endregion
    }
}