#nullable enable // autogenerated

using MVZ2.GameContent.Damages;
using MVZ2.GameContent.Projectiles;
using MVZ2.Vanilla.Audios;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Properties;
using MVZ2Logic.Level;
using PVZEngine;
using PVZEngine.Damages;
using PVZEngine.Entities;
using PVZEngine.Level;
using UnityEngine;

namespace MVZ2.GameContent.Contraptions
{
    [EntityBehaviourDefinition(VanillaContraptionNames.dimensionHammer)]
    public class DimensionHammer : ContraptionBehaviour
    {
        public DimensionHammer(string nsp, string name) : base(nsp, name)
        {
        }
        protected override void UpdateAI(Entity hammer)
        {
            base.UpdateAI(hammer);
            var frame = GetFrame(hammer);
            frame++;
            if (frame == START_FRAME)
            {
                hammer.TriggerAnimation("Attack");
            }
            if (frame == FLING_FRAME)
            {
                hammer.PlaySound(VanillaSoundID.fling);
            }
            if (frame == SMASH_FRAME)
            {
                hammer.PlaySound(VanillaSoundID.thump);
                Smash(hammer, hammer.GetDamage(), hammer.GetFaction());
            }
            if (frame == SMASHED_FRAME)
            {
                hammer.SetAnimationBool("Attacked", true);
            }
            SetFrame(hammer, frame);
        }
        protected override void UpdateLogic(Entity hammer)
        {
            base.UpdateLogic(hammer);
            var frame = GetFrame(hammer);
            if (frame <= SMASHED_FRAME)
            {
                hammer.Timeout = hammer.GetMaxTimeout();
            }
        }
        public override bool CanEvoke(Entity entity)
        {
            return false;
        }
        public static void Smash(Entity entity, float damage, int faction)
        {
            DamageEffectList damageEffectList = new DamageEffectList(VanillaDamageEffects.IMPACT, VanillaDamageEffects.DAMAGE_BOTH_ARMOR_AND_BODY, VanillaDamageEffects.MUTE);
            var groundEntities = entity.Level.OverlapSphere(entity.Position, entity.GetRange(), faction, EntityCollisionHelper.MASK_VULNERABLE, 0);
            foreach (var target in groundEntities)
            {
                var ent = target.Entity;
                if (!ent.IsOnGround && !ent.IsAboveLand())
                    continue;
                target.TakeDamage(damage, damageEffectList, entity);
                if (ent.Type == EntityTypes.ENEMY)
                {
                    if (ent.CanDeactive())
                    {
                        ent.Velocity += Vector3.up * 10;
                        ent.Stun(Ticks.FromSeconds(5));
                    }
                }
            }
            for (int i = 0; i < 10; i++)
            {
                for (int j = 0; j < 6; j++)
                {
                    var angle = i * 36 + j * 18;
                    var param = entity.GetShootParams();
                    param.projectileID = VanillaProjectileID.arrowBullet;
                    param.damage = entity.GetDamage() / 6f;
                    param.velocity = new Vector3(Mathf.Cos(angle * Mathf.Deg2Rad), 0, Mathf.Sin(angle * Mathf.Deg2Rad)) * Mathf.RoundToInt(20 / (j + 1));
                    entity.ShootProjectile(param)?.Let(e =>
                    {
                        e.SetHSVToColor(new Color(1, 0.6f, 1, 1));
                    });
                }
            }
        }
        public static int GetFrame(Entity entity) => entity.GetBehaviourField<int>(ID, PROP_EVOCATION_TIME);
        public static void SetFrame(Entity entity, int value) => entity.SetBehaviourField(ID, PROP_EVOCATION_TIME, value);
        private static readonly NamespaceID ID = VanillaContraptionID.dimensionHammer;
        public static readonly VanillaEntityPropertyMeta<int> PROP_EVOCATION_TIME = new VanillaEntityPropertyMeta<int>("frame");
        public const float RADIUS = 40;
        public const int START_FRAME = 20;
        public const int FLING_FRAME = 30;
        public const int SMASH_FRAME = 35;
        public const int SMASHED_FRAME = 50;
    }
}

