#nullable enable // autogenerated

using MVZ2.GameContent.Buffs.Contraptions;
using MVZ2.GameContent.Damages;
using MVZ2.GameContent.Effects;
using MVZ2.GameContent.Projectiles;
using MVZ2.Vanilla.Audios;
using MVZ2.Vanilla.Contraptions;
using MVZ2.Vanilla.Detections;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Properties;
using MVZ2Logic.Level;
using PVZEngine;
using PVZEngine.Buffs;
using PVZEngine.Damages;
using PVZEngine.Entities;
using PVZEngine.Level;
using UnityEngine;

namespace MVZ2.GameContent.Contraptions
{
    [EntityBehaviourDefinition(VanillaContraptionNames.dimensionHammer)]
    public class DimensionHammer : ContraptionBehaviour
    {
        public DimensionHammer(string nsp, string name) : base(nsp, name)
        {
        }
        public override void Init(Entity entity)
        {
            base.Init(entity);
            entity.CollisionMaskHostile |= EntityCollisionHelper.MASK_ENEMY;
        }
        protected override void UpdateAI(Entity hammer)
        {
            base.UpdateAI(hammer);
            if (!IsSmashing(hammer))
                return;
            var frame = GetFrame(hammer);
            if (frame == START_FRAME)
            {
                hammer.TriggerAnimation("Attack");
            }
            if (frame == JUMP_FRAME)
            {
                hammer.Velocity = VanillaProjectileExt.GetLobVelocityByTime(hammer.Position, hammer.Position - SMASH_OFFSET * hammer.GetFacingDirection(), SMASH_FRAME - JUMP_FRAME, hammer.GetGravity());
            }
            if (frame == FLING_FRAME_1 || frame ==  FLING_FRAME_2 || frame ==  FLING_FRAME_3)
            {
                hammer.PlaySound(VanillaSoundID.fling);
            }
            if (frame == SMASH_FRAME)
            {
                hammer.PlaySound(VanillaSoundID.thump);
                Smash(hammer, hammer.GetDamage(), hammer.GetFaction());
                hammer.SetAnimationBool("Attacked", true);
            }
            frame++;
            SetFrame(hammer, frame);
        }
        protected override void UpdateLogic(Entity hammer)
        {
            base.UpdateLogic(hammer);
            var frame = GetFrame(hammer);
            if (frame <= SMASH_FRAME)
            {
                hammer.Timeout = hammer.GetMaxTimeout();
            }
        }
        public override void PostCollision(EntityCollision collision, int state)
        {
            base.PostCollision(collision, state);
            if (state == EntityCollisionHelper.STATE_EXIT)
                return;
            if (!collision.Collider.IsForMain())
                return;
            var hammer = collision.Entity;
            if (IsSmashing(hammer) || hammer.IsAIFrozen())
                return;
            var other = collision.Other;
            if (other.Type != EntityTypes.ENEMY && !Detection.CanDetect(other))
                return;
            if (!IsValidEnemy(hammer, other))
                return;
            StartSmash(hammer);
        }
        public override bool CanEvoke(Entity entity)
        {
            if (IsSmashing(entity))
            {
                return false;
            }
            return base.CanEvoke(entity);
        }
        protected override void OnEvoke(Entity entity)
        {
            base.OnEvoke(entity);
            entity.SetEvoked(true);
            StartSmash(entity);
            entity.AddBuff<DimensionHammerEvokedBuff>();
        }
        public static void Smash(Entity entity, float damage, int faction)
        {
            var offset = SMASH_OFFSET * entity.GetFacingDirection();
            DamageEffectList damageEffectList = new DamageEffectList(VanillaDamageEffects.IMPACT, VanillaDamageEffects.DAMAGE_BOTH_ARMOR_AND_BODY, VanillaDamageEffects.MUTE);
            var groundEntities = entity.Level.OverlapSphere(entity.Position + offset, entity.GetRange(), faction, EntityCollisionHelper.MASK_VULNERABLE, 0);
            foreach (var target in groundEntities)
            {
                var ent = target.Entity;
                if (!ent.IsOnGround && !ent.IsAboveLand())
                    continue;
                target.TakeDamage(damage, damageEffectList, entity);
                if (ent.Type == EntityTypes.ENEMY)
                {
                    if (ent.CanDeactive())
                    {
                        ent.Velocity += Vector3.up * 10;
                        ent.Stun(Ticks.FromSeconds(5));
                    }
                }
            }
            if (entity.IsEvoked())
            {
                Explosion.Spawn(entity, entity.Position + offset, entity.GetRange());
                entity.PlaySound(VanillaSoundID.explosion);
            }
            for (int i = 0; i < 10; i++)
            {
                for (int j = 0; j < 6; j++)
                {
                    var angle = i * 36 + j * 18;
                    var param = entity.GetShootParams();
                    param.projectileID = VanillaProjectileID.arrowBullet;
                    param.position += SMASH_OFFSET * entity.GetFacingDirection();
                    param.damage = entity.GetDamage() / 6f;
                    param.velocity = new Vector3(Mathf.Cos(angle * Mathf.Deg2Rad), 0, Mathf.Sin(angle * Mathf.Deg2Rad)) * Mathf.RoundToInt(20 / (j + 1));
                    entity.ShootProjectile(param)?.Let(e =>
                    {
                        e.SetHSVToColor(new Color(1, 0.6f, 1, 1));
                    });
                }
            }
        }
        public static void StartSmash(Entity entity)
        {
            entity.AddBuff<DimensionHammerInvincibleBuff>();
        }
        public static bool IsSmashing(Entity entity)
        {
            return entity.HasBuff<DimensionHammerInvincibleBuff>();
        }
        public static bool IsValidEnemy(Entity hopper, Entity target)
        {
            return !target.IsDead && hopper.IsHostile(target);
        }
        public static int GetFrame(Entity entity) => entity.GetBehaviourField<int>(ID, PROP_EVOCATION_TIME);
        public static void SetFrame(Entity entity, int value) => entity.SetBehaviourField(ID, PROP_EVOCATION_TIME, value);
        private static readonly NamespaceID ID = VanillaContraptionID.dimensionHammer;
        public static readonly VanillaEntityPropertyMeta<int> PROP_EVOCATION_TIME = new VanillaEntityPropertyMeta<int>("frame");
        public static readonly VanillaEntityPropertyMeta<bool> PROP_SMASH = new VanillaEntityPropertyMeta<bool>("smash");
        public static readonly VanillaEntityPropertyMeta<Vector3> PROP_POSITION = new VanillaEntityPropertyMeta<Vector3>("position");
        public const int START_FRAME = 0;
        public const int JUMP_FRAME = START_FRAME + 5;
        public const int FLING_FRAME_1 = JUMP_FRAME + 10;
        public const int FLING_FRAME_2 = FLING_FRAME_1 + 10;
        public const int FLING_FRAME_3 = FLING_FRAME_2 + 10;
        public const int SMASH_FRAME = FLING_FRAME_3 + 5;
        public const float SMASH_OFFSET = 45f;
    }
}

