#nullable enable // autogenerated

using System.Linq;
using MVZ2.GameContent.Buffs;
using MVZ2.GameContent.Buffs.Contraptions;
using MVZ2.GameContent.Damages;
using MVZ2.GameContent.Difficulties;
using MVZ2.Vanilla.Audios;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Properties;
using PVZEngine;
using PVZEngine.Buffs;
using PVZEngine.Callbacks;
using PVZEngine.Damages;
using PVZEngine.Entities;
using PVZEngine.Level;
using Tools;
using UnityEngine;

namespace MVZ2.GameContent.Contraptions
{
    [EntityBehaviourDefinition(VanillaContraptionNames.elasticCloud)]
    public class ElasticCloud : AIEntityBehaviour
    {
        public ElasticCloud(string nsp, string name) : base(nsp, name)
        {
        }
        public override void Init(Entity entity)
        {
            base.Init(entity);
            entity.CollisionMaskHostile |= EntityCollisionHelper.MASK_ENEMY;
            SetKnockBackMultipiler(entity, 1f);
            SetHealthCostMultipiler(entity, 1f);
            SetAnimationSpeedMultipiler(entity, 1f);
            SetChargeCooldownTimer(entity, new FrameTimer(Ticks.FromSeconds(KNOCKBACK_COOLDOWN_SECONDS)));
        }
        public override void PostCollision(EntityCollision collision, int state)
        {
            base.PostCollision(collision, state);
            if (!collision.OtherCollider.IsForMain())
                return;
            var cloud = collision.Entity;
            var other = collision.Other;
            if (other.Type != EntityTypes.ENEMY || !cloud.IsHostile(other))
                return;
            TryBounceEnemy(cloud, other);
        }
        protected override void UpdateAI(Entity entity)
        {
            base.UpdateAI(entity);
            var timer = GetChargeCooldownTimer(entity);
            if (!timer.RunToExpiredAndNotNull())
                return;
            var push = Mathf.Lerp(GetKnockBackMultipiler(entity), 1.5f, 0.005f);
            SetKnockBackMultipiler(entity, push);
            var cost = Mathf.Lerp(GetHealthCostMultipiler(entity), 0.5f, 0.005f);
            SetHealthCostMultipiler(entity, cost);
            var speed = Mathf.Lerp(GetAnimationSpeedMultipiler(entity), 2f, 0.01f);
            SetAnimationSpeedMultipiler(entity, speed);
        }
        protected override void UpdateLogic(Entity entity)
        {
            base.UpdateLogic(entity);
            entity.SetAnimationFloat("Multiplier", GetAnimationSpeedMultipiler(entity));
            entity.SetAnimationBool("Charge", GetAnimationSpeedMultipiler(entity) > 1f);
        }
        public override void PreTakeDamage(DamageInput input, CallbackResult result)
        {
            base.PreTakeDamage(input, result);
            bool punch = input.Effects.HasEffect(VanillaDamageEffects.IMPACT);
            if (input.Effects.HasEffect(VanillaDamageEffects.ENEMY_MELEE) || punch)
            {
                var cloud = input.Entity;
                if (input.Source is EntitySourceReference entityRef)
                {
                    TryBounceEnemy(cloud, entityRef.GetEntity(cloud.Level), punch);
                }
                result.SetFinalValue(false);
                return;
            }
        }
        public static bool TryBounceEnemy(Entity self, Entity? enemy, bool ignoreCooldown = false)
        {
            if (!enemy.ExistsAndAlive() || enemy.Type != EntityTypes.ENEMY)
                return false;
            if (!ignoreCooldown && HasEnemyKnockbackCooldown(self, enemy))
                return false;
            var push = GetKnockBackMultipiler(self);
            var cost = GetHealthCostMultipiler(self);
            var timer = GetChargeCooldownTimer(self);
            var knockbackMultiplier = enemy.GetStrongKnockbackMultiplier();
            enemy.Velocity += knockbackMultiplier * KNOCKBACK_DISTANCE * push * self.GetFacingDirection();

            var bounceDamage = BOUNCE_DAMAGE * self.Level.GetElasticCloudBounceDamageMultiplier() * cost;
            self.TakeDamage(bounceDamage, new DamageEffectList(VanillaDamageEffects.SELF_DAMAGE), self);
            AddEnemyKnockbackCooldown(self, enemy, Ticks.FromSeconds(KNOCKBACK_COOLDOWN_SECONDS));
            PlayBounceEffect(self);
            ResetMultipliers(self);
            timer?.Reset();
            return true;
        }
        public static void PlayBounceEffect(Entity entity)
        {
            entity.TriggerAnimation("Bounce");
            entity.PlaySound(VanillaSoundID.boing);
        }
        public static void ResetMultipliers(Entity entity)
        {
            SetKnockBackMultipiler(entity, 1f);
            SetHealthCostMultipiler(entity, 1f);
            SetAnimationSpeedMultipiler(entity, 1f);
        }
        public static void AddEnemyKnockbackCooldown(Entity self, Entity enemy, int cooldown)
        {
            var targetID = enemy.ID;
            var buffID = VanillaBuffID.Contraption.elasticCloudBounceCooldown;
            var buff = GetEnemyKnockbackCooldownBuff(self, enemy);
            if (buff == null)
            {
                buff = self.AddBuff(buffID);
                ElasticCloudBounceCooldownBuff.SetTargetID(buff, targetID);
            }
            ElasticCloudBounceCooldownBuff.SetTimeout(buff, cooldown);
        }
        public static Buff GetEnemyKnockbackCooldownBuff(Entity self, Entity enemy)
        {
            var targetID = enemy.ID;
            var buffID = VanillaBuffID.Contraption.elasticCloudBounceCooldown;
            var buffs = self.GetBuffs(buffID);
            return buffs.FirstOrDefault(b => ElasticCloudBounceCooldownBuff.GetTargetID(b) == targetID);
        }
        public static bool HasEnemyKnockbackCooldown(Entity self, Entity enemy)
        {
            return GetEnemyKnockbackCooldownBuff(self, enemy) != null;
        }
        public static float GetKnockBackMultipiler(Entity entity) => entity.GetProperty<float>(KNOCKBACK_MULTIPLIER);
        public static void SetKnockBackMultipiler(Entity entity, float value) => entity.SetProperty(KNOCKBACK_MULTIPLIER, value);
        public static float GetHealthCostMultipiler(Entity entity) => entity.GetProperty<float>(HEALTH_COST_MULTIPLIER);
        public static void SetHealthCostMultipiler(Entity entity, float value) => entity.SetProperty(HEALTH_COST_MULTIPLIER, value);
        public static float GetAnimationSpeedMultipiler(Entity entity) => entity.GetProperty<float>(ANIMATION_SPEED_MULTIPLIER);
        public static void SetAnimationSpeedMultipiler(Entity entity, float value) => entity.SetProperty(ANIMATION_SPEED_MULTIPLIER, value);
        public static FrameTimer? GetChargeCooldownTimer(Entity entity) => entity.GetBehaviourField<FrameTimer>(CHARGE_COOLDOWN_TIMER);
        public static void SetChargeCooldownTimer(Entity entity, FrameTimer timer) => entity.SetBehaviourField(CHARGE_COOLDOWN_TIMER, timer);
        public const float KNOCKBACK_DISTANCE = 20f;
        public const float BOUNCE_DAMAGE = 300f;
        public const float KNOCKBACK_COOLDOWN_SECONDS = 1f;
        public static readonly VanillaEntityPropertyMeta<float> KNOCKBACK_MULTIPLIER = new VanillaEntityPropertyMeta<float>("KnockBackMultipiler");
        public static readonly VanillaEntityPropertyMeta<float> HEALTH_COST_MULTIPLIER = new VanillaEntityPropertyMeta<float>("HealthCostMultipiler");
        public static readonly VanillaEntityPropertyMeta<float> ANIMATION_SPEED_MULTIPLIER = new VanillaEntityPropertyMeta<float>("AnimationSpeedMultipiler");
        public static readonly VanillaEntityPropertyMeta<FrameTimer> CHARGE_COOLDOWN_TIMER = new VanillaEntityPropertyMeta<FrameTimer>("charge_cooldown_timer");
    }
}
