#nullable enable // autogenerated

using System.Linq;
using MVZ2.GameContent.Buffs.Entities;
using MVZ2.GameContent.Damages;
using MVZ2.GameContent.Effects;
using MVZ2.GameContent.Entities;
using MVZ2.Vanilla.Audios;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Level;
using MVZ2.Vanilla.Properties;
using MVZ2Logic.Entities;
using PVZEngine;
using PVZEngine.Damages;
using PVZEngine.Definitions;
using PVZEngine.Entities;
using Tools;
using UnityEngine;

namespace MVZ2.GameContent.Enemies
{
    [AutoEntityBehaviourDefinition(VanillaEnemyNames.berserker)]
    public class Berserker : AIEntityBehaviour, IDeathEffectsBehaviour
    {
        public Berserker(string nsp, string name) : base(nsp, name)
        {
        }
        public override void Init(Entity entity)
        {
            base.Init(entity);
            SetDangerTimer(entity, new FrameTimer(CAST_COOLDOWN));
        }
        protected override void UpdateAI(Entity entity)
        {
            base.UpdateAI(entity);
            var stateTimer = GetDangerTimer(entity);
            var dangerLevel = GetDangerLevel(entity);
            if (stateTimer.RunToExpiredAndNotNull(entity.GetAttackSpeed()))
            {
                dangerLevel++;
                SetDangerLevel(entity, dangerLevel);
                if (dangerLevel <= 2)
                {
                    entity.PlaySound(VanillaSoundID.powerUp);
                    WhiteFlashBuff.AddToEntity(entity, 10);
                }
                stateTimer.Reset();
            }
        }
        protected override void UpdateLogic(Entity entity)
        {
            base.UpdateLogic(entity);
            var dangerLevel = GetDangerLevel(entity);
            entity.SetModelProperty("DangerLevel", dangerLevel);
        }
        public void DeathEffects(Entity entity, DeathInfo info)
        {
            Explode(entity, entity.GetDamage(), entity.GetFaction());
            entity.Remove();
        }
        public static void Explode(Entity entity, float damage, int faction)
        {
            var effects = new DamageEffectList(VanillaDamageEffects.EXPLOSION, VanillaDamageEffects.DAMAGE_BODY_AFTER_ARMOR_BROKEN, VanillaDamageEffects.MUTE);
            Explode(entity, damage * 3, effects, faction);

            if (entity.IsEntityOf(VanillaEnemyID.berserker))
            {
                var dangerLevel = GetDangerLevel(entity);
                if (dangerLevel >= 1)
                {
                    FireExplode(entity, entity.GetDamage() * 2, effects, faction);
                }
                if (dangerLevel >= 2)
                {
                    LightningExplode(entity, damage, effects, faction);
                }
            }
        }
        public static void Explode(Entity entity, float damage, DamageEffectList effects, int faction)
        {
            Explode(entity, damage, entity.GetRange(), effects, faction);
        }
        public static void Explode(Entity entity, float damage, float range, DamageEffectList effects, int faction)
        {
            var scale = entity.GetFinalScale();
            var scaleX = Mathf.Abs(scale.x);
            var radius = range * scaleX;
            entity.Explode(entity.GetCenter(), radius, faction, damage, effects);

            Explosion.Spawn(entity, entity.GetCenter(), radius);

            entity.PlaySound(VanillaSoundID.explosion, scaleX == 0 ? 1000 : 1 / (scaleX));
        }
        public static void FireExplode(Entity entity, float damage, DamageEffectList effects, int faction)
        {
            var scale = entity.GetFinalScale();
            var scaleX = Mathf.Abs(scale.x);
            var range = entity.GetRange() * scaleX;
            var fireRange = range * 1.5f;
            entity.Explode(entity.GetCenter(), fireRange, faction, damage, new DamageEffectList(effects.GetEffects().Append(VanillaDamageEffects.FIRE).ToArray()));

            for (int i = 0; i < 15; i++)
            {
                float degree = i * 24;
                float rad = degree * Mathf.Deg2Rad;
                Vector3 pos = entity.GetCenter() + new Vector3(Mathf.Sin(rad), 0, Mathf.Cos(rad)) * (fireRange / 2);
                entity.Spawn(VanillaEffectID.fireburn, pos);
            }
            for (int i = 0; i < 30; i++)
            {
                float degree = i * 12 + 6;
                float rad = degree * Mathf.Deg2Rad;
                Vector3 pos = entity.GetCenter() + new Vector3(Mathf.Sin(rad), 0, Mathf.Cos(rad)) * fireRange;
                entity.Spawn(VanillaEffectID.fireburn, pos);
            }

            entity.PlaySound(VanillaSoundID.darkSkiesImpact, scaleX == 0 ? 1000 : 1 / (scaleX));
        }
        public static void LightningExplode(Entity entity, float damage, DamageEffectList effects, int faction)
        {
            var scale = entity.GetFinalScale();
            var scaleX = Mathf.Abs(scale.x);
            var range = entity.GetRange() * scaleX;
            var ligntningRange = range * 2.5f;
            entity.Explode(entity.GetCenter(), ligntningRange, faction, damage, new DamageEffectList(effects.GetEffects().Append(VanillaDamageEffects.LIGHTNING).ToArray()));

            for (int i = 0; i < 10; i++)
            {
                entity.Spawn(VanillaEffectID.electricArc, entity.Position)?.Let(e =>
                {
                    float degree = i * 36;
                    float rad = degree * Mathf.Deg2Rad;
                    Vector3 pos = entity.Position + new Vector3(Mathf.Sin(rad), 0, Mathf.Cos(rad)) * ligntningRange;
                    ElectricArc.SetPointCount(e, 25);
                    ElectricArc.Connect(e, pos);
                    ElectricArc.UpdateArc(e);
                });
            }

            entity.PlaySound(VanillaSoundID.powerOff, scaleX == 0 ? 1000 : 1 / (scaleX));
        }
        #region 常量
        private const int CAST_COOLDOWN = 240;
        public static void SetDangerLevel(Entity entity, int value) => entity.SetBehaviourField(PROP_DANGER_LEVEL, value);
        public static int GetDangerLevel(Entity entity) => entity.GetBehaviourField<int>(PROP_DANGER_LEVEL);
        public static void SetDangerTimer(Entity entity, FrameTimer timer) => entity.SetBehaviourField(PROP_STATE_TIMER, timer);
        public static FrameTimer? GetDangerTimer(Entity entity) => entity.GetBehaviourField<FrameTimer>(PROP_STATE_TIMER);
        public static readonly VanillaEntityPropertyMeta<int> PROP_DANGER_LEVEL = new VanillaEntityPropertyMeta<int>("danger_level");
        public static readonly VanillaEntityPropertyMeta<FrameTimer> PROP_STATE_TIMER = new VanillaEntityPropertyMeta<FrameTimer>("StateTimer");
        #endregion 常量
    }
}
