#nullable enable // autogenerated

using MVZ2.GameContent.Damages;
using MVZ2.Vanilla.Callbacks;
using MVZ2.Vanilla.Entities;
using PVZEngine.Callbacks;
using PVZEngine.Definitions;

namespace MVZ2.GameContent.Enemies
{
    [AutoEntityBehaviourDefinition(VanillaEnemyNames.jackDullahanHead)]
    public class JackDullahanHead : DullahanHead
    {
        public JackDullahanHead(string nsp, string name) : base(nsp, name)
        {
            AddTrigger(VanillaLevelCallbacks.APPLY_DAMAGE_SPECIAL_EFFECTS, ApplyDamageEffectsCallback);
        }
        private void ApplyDamageEffectsCallback(VanillaLevelCallbacks.PostTakeDamageParams param, CallbackResult callbackResult)
        {
            var output = param.output;
            var entity = output.Entity;
            var bodyResult = output.BodyResult;
            var armorResult = output.ArmorResult;
            bool wither = false;
            if (bodyResult != null && bodyResult.Source?.DefinitionID == GetID() && bodyResult.HasEffect(VanillaDamageEffects.ENEMY_MELEE))
            {
                wither = !entity.IsUndead();
            }
            if (armorResult != null && armorResult.Source?.DefinitionID == GetID() && armorResult.HasEffect(VanillaDamageEffects.ENEMY_MELEE))
            {
                wither = !entity.IsUndead();
            }
            if (wither)
            {
                entity.InflictWither(150, bodyResult?.Source ?? armorResult?.Source);
            }
        }
    }
}
