#nullable enable // autogenerated

using System.Collections.Generic;
using MVZ2.GameContent.Buffs;
using MVZ2.GameContent.Detections;
using MVZ2.Vanilla.Detections;
using MVZ2.Vanilla.Effects;
using PVZEngine.Auras;
using PVZEngine.Buffs;
using PVZEngine.Damages;
using PVZEngine.Definitions;
using PVZEngine.Entities;
using UnityEngine;

namespace MVZ2.GameContent.Enemies
{
    [AutoEntityBehaviourDefinition(VanillaEnemyNames.soulsand)]
    public class Soulsand : EnemyBehaviour
    {
        public Soulsand(string nsp, string name) : base(nsp, name)
        {
            AddAura(new SoulsandAura());
        }
        protected override void UpdateLogic(Entity entity)
        {
            base.UpdateLogic(entity);

            if (entity.Velocity.y != 0)
            {
                entity.AddFragmentTickDamage(Mathf.Abs(entity.Velocity.y));
            }
        }
        public override void PostDeath(Entity entity, DeathInfo info)
        {
            base.PostDeath(entity, info);
            entity.Remove();
        }
        public class SoulsandAura : AuraEffectDefinition
        {
            public SoulsandAura() : base(VanillaBuffID.Enemy.soulsandSlow, 5)
            {
                enemyDetector = new SoulsandDetector();
            }

            public override void GetAuraTargets(AuraEffect auraEffect, List<IBuffTarget> results)
            {
                var source = auraEffect.Source;
                var entity = source.GetEntity();
                if (entity == null)
                    return;
                detectBuffer.Clear();
                enemyDetector.DetectEntities(entity, detectBuffer);
                results.AddRange(detectBuffer);
            }
            private Detector enemyDetector;
            private List<Entity> detectBuffer = new List<Entity>();
        }
    }
}
