#nullable enable // autogenerated

using System.Collections.Generic;
using System.Linq;
using MVZ2.GameContent.Detections;
using MVZ2.Vanilla.Audios;
using MVZ2.Vanilla.Detections;
using MVZ2.Vanilla.Enemies;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Properties;
using PVZEngine;
using PVZEngine.Damages;
using PVZEngine.Entities;
using PVZEngine.Level;
using Tools;

namespace MVZ2.GameContent.Enemies
{
    [EntityBehaviourDefinition(VanillaEnemyNames.spellcaster)]
    public class Spellcaster : AIEntityBehaviour
    {
        public Spellcaster(string nsp, string name) : base(nsp, name)
        {
            detector = new LawnDetector()
            {
                mask = EntityCollisionHelper.MASK_ENEMY | EntityCollisionHelper.MASK_PLANT,
                factionTarget = FactionTarget.Friendly
            };
        }

        public override void Init(Entity entity)
        {
            base.Init(entity);
            SetStateTimer(entity, new FrameTimer(CAST_COOLDOWN));
        }
        protected override void UpdateAI(Entity entity)
        {
            base.UpdateAI(entity);

            if (entity.State == STATE_WALK)
            {
                var stateTimer = GetStateTimer(entity);
                healBuffer.Clear();
                detector.DetectEntities(entity, healBuffer);
                if (stateTimer.RunToExpiredAndNotNull(entity.GetAttackSpeed()))
                {
                    var heal_target = healBuffer.Where(e => !e.IsNotActiveEnemy() && e.Health < e.GetMaxHealth()).RandomTake(1, entity.RNG);
                    if (heal_target == null)
                    {
                        stateTimer.Frame = CONTROL_DETECT_TIME;
                    }
                    else
                    {
                        foreach (var target in heal_target)
                        {
                            target.HealEffects(entity.GetDamage() * 2, entity);
                            entity.PlaySound(VanillaSoundID.heal);
                            entity.SetCasting(true);
                        }
                        stateTimer.Frame = CONTROL_DETECT_TIME;
                    }
                }
            }
            else if (entity.State == STATE_CAST)
            {
                var stateTimer = GetStateTimer(entity);
                if (stateTimer.RunToExpiredAndNotNull(entity.GetAttackSpeed()))
                {
                    EndCasting(entity);
                }
            }
        }
        public override void PostDeath(Entity entity, DeathInfo info)
        {
            base.PostDeath(entity, info);
            if (entity.IsCasting())
            {
                EndCasting(entity);
            }
        }
        private void EndCasting(Entity entity)
        {
            var stateTimer = GetStateTimer(entity);
            stateTimer?.Reset();
            entity.SetCasting(false);
        }

        public static void SetStateTimer(Entity entity, FrameTimer timer) => entity.SetBehaviourField(ID, PROP_STATE_TIMER, timer);
        public static FrameTimer? GetStateTimer(Entity entity) => entity.GetBehaviourField<FrameTimer>(ID, PROP_STATE_TIMER);

        #region ����
        private const int CAST_COOLDOWN = 180;
        private const int CONTROL_DETECT_TIME = 30;
        public const int STATE_WALK = VanillaEnemyStates.WALK;
        public const int STATE_CAST = VanillaEnemyStates.CAST;
        private Detector detector;
        private List<Entity> healBuffer = new List<Entity>();

        public static readonly NamespaceID ID = VanillaEnemyID.spellcaster;
        public static readonly VanillaEntityPropertyMeta<bool> PROP_CASTING = new VanillaEntityPropertyMeta<bool>("Casting");
        public static readonly VanillaEntityPropertyMeta<EntityID> PROP_ORB = new VanillaEntityPropertyMeta<EntityID>("Orb");
        public static readonly VanillaEntityPropertyMeta<FrameTimer> PROP_STATE_TIMER = new VanillaEntityPropertyMeta<FrameTimer>("StateTimer");
        #endregion ����
    }
}