#nullable enable // autogenerated

using MVZ2.GameContent.Projectiles;
using MVZ2.Vanilla.Audios;
using MVZ2.Vanilla.Contraptions;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Level;
using MVZ2.Vanilla.Properties;
using PVZEngine.Entities;
using PVZEngine.Level;
using Tools;
using UnityEngine;

namespace MVZ2.GameContent.Contraptions
{
    [EntityBehaviourDefinition(VanillaContraptionNames.repeatenser)]
    public class Repeatenser : DispenserFamily
    {
        public Repeatenser(string nsp, string name) : base(nsp, name)
        {
        }

        public override void Init(Entity entity)
        {
            base.Init(entity);
            InitShootTimer(entity);
            SetEvocationTimer(entity, new FrameTimer(50));
            SetRepeatTimer(entity, new FrameTimer(15));
        }
        protected override void UpdateAI(Entity entity)
        {
            base.UpdateAI(entity);
            if (!entity.IsEvoked())
            {
                ShootTick(entity);
                int repeatCount = GetRepeatCount(entity);
                if (repeatCount > 0)
                {
                    var repeatTimer = GetRepeatTimer(entity);
                    if (repeatTimer != null && repeatTimer.RunToExpired(entity.GetAttackSpeed()))
                    {
                        entity.PlaySound(VanillaSoundID.shot);
                        entity.PlaySound(VanillaSoundID.bow);
                        Shoot(entity);
                        SetRepeatCount(entity, repeatCount - 1);
                        repeatTimer.Reset();
                    }
                }
            }
            else
            {
                EvokedUpdate(entity);
            }
        }
        public override void OnShootTick(Entity entity)
        {
            int count = REPEAT_COUNT;
            SetRepeatCount(entity, count);
            var repeatTimer = GetRepeatTimer(entity);
            if (repeatTimer != null)
            {
                repeatTimer.ResetTime(Mathf.FloorToInt(15f / count));
                repeatTimer.Frame = 0;
            }
        }

        protected override void OnEvoke(Entity entity)
        {
            base.OnEvoke(entity);
            var evocationTimer = GetEvocationTimer(entity);
            evocationTimer?.Reset();
            entity.SetEvoked(true);
        }
        private void EvokedUpdate(Entity entity)
        {
            var evocationTimer = GetEvocationTimer(entity);
            if (evocationTimer == null)
                return;
            evocationTimer.Run();
            if (evocationTimer.PassedInterval(10))
            {
                entity.TriggerAnimation("Shoot");
                entity.PlaySound(VanillaSoundID.shot);
                entity.PlaySound(VanillaSoundID.bow);
                var shootParams = entity.GetShootParams();
                shootParams.velocity *= 2;
                shootParams.damage *= 2;
                entity.ShootProjectile(shootParams)?.Let(p => 
                {
                    OakLog.SetEvoked(p, true);
                });
            }
            if (evocationTimer.Expired)
            {
                entity.SetEvoked(false);
                var shootTimer = GetShootTimer(entity);
                shootTimer?.Reset();
            }
        }
        protected override int GetTimerTime(Entity entity)
        {
            if (entity.Level.IsIZombie())
            {
                return ATTACK_INTERVAL_MAX;
            }
            return entity.RNG.Next(ATTACK_INTERVAL_MIN, ATTACK_INTERVAL_MAX + 1);
        }
        public static FrameTimer? GetEvocationTimer(Entity entity) => entity.GetBehaviourField<FrameTimer>(PROP_EVOCATION_TIMER);
        public static void SetEvocationTimer(Entity entity, FrameTimer timer) => entity.SetBehaviourField(PROP_EVOCATION_TIMER, timer);
        public static FrameTimer? GetRepeatTimer(Entity entity) => entity.GetBehaviourField<FrameTimer>(PROP_REPEAT_TIMER);
        public static void SetRepeatTimer(Entity entity, FrameTimer timer) => entity.SetBehaviourField(PROP_REPEAT_TIMER, timer);

        public static int GetRepeatCount(Entity entity) => entity.GetBehaviourField<int>(PROP_REPEAT_COUNT);
        public static void SetRepeatCount(Entity entity, int count) => entity.SetBehaviourField(PROP_REPEAT_COUNT, count);

        public const int REPEAT_COUNT = 1;
        private const int ATTACK_INTERVAL_MIN = 85;
        private const int ATTACK_INTERVAL_MAX = 90;
        public static readonly VanillaEntityPropertyMeta<FrameTimer> PROP_EVOCATION_TIMER = new VanillaEntityPropertyMeta<FrameTimer>("EvocationTimer");
        public static readonly VanillaEntityPropertyMeta<FrameTimer> PROP_REPEAT_TIMER = new VanillaEntityPropertyMeta<FrameTimer>("RepeatTimer");
        public static readonly VanillaEntityPropertyMeta<int> PROP_REPEAT_COUNT = new VanillaEntityPropertyMeta<int>("RepeatCount");
    }
}