#nullable enable // autogenerated

using MVZ2.GameContent.Detections;
using MVZ2.GameContent.Effects;
using MVZ2.Vanilla.Audios;
using MVZ2.Vanilla.Detections;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Properties;
using PVZEngine;
using PVZEngine.Entities;
using PVZEngine.Level;
using Tools;
using UnityEngine;

namespace MVZ2.GameContent.Contraptions
{
    [EntityBehaviourDefinition(VanillaContraptionNames.smoker)]
    public class Smoker : ContraptionBehaviour
    {
        public Smoker(string nsp, string name) : base(nsp, name)
        {
            smokeDetector = new FireBreathDetector(VanillaEffectID.smokerSmoke);
        }
        public override void Init(Entity entity)
        {
            base.Init(entity);
            SetSmokeTimer(entity, new FrameTimer(SMOKE_INTERVAL));
        }
        protected override void UpdateAI(Entity entity)
        {
            base.UpdateAI(entity);
            var target = smokeDetector.Detect(entity);
            var timer = GetSmokeTimer(entity);
            if (timer.RunToExpiredAndNotNull(entity.GetAttackSpeed()))
            {
                if (target != null)
                {
                    var param = entity.GetSpawnParams();
                    param.SetProperty(VanillaEntityProps.DAMAGE, entity.GetDamage() / 20);
                    param.SetProperty(EngineEntityProps.FLIP_X, entity.IsFlipX());
                    entity.Spawn(VanillaEffectID.smokerSmoke, entity.GetCenter(), param)?.Let(e =>
                    {
                        int hideSection = 0;
                        if (entity.GetLane() == 0)
                        {
                            hideSection = -1;
                        }
                        if (entity.GetLane() == entity.Level.GetMaxLaneCount() - 1)
                        {
                            hideSection = 1;
                        }
                        e.SetAnimationInt("HideSection", hideSection);
                    });
                    timer.ResetTime(SMOKE_INTERVAL);
                }
                else
                {
                    timer.ResetTime(SMOKE_INTERVAL_SHORT);
                }
            }
        }
        protected override void UpdateLogic(Entity entity)
        {
            base.UpdateLogic(entity);
            bool frozen = entity.IsAIFrozen();
            entity.SetAnimationBool("Frozen", frozen);
            entity.SetLightSource(!frozen);
        }
        protected override void OnEvoke(Entity entity)
        {
            base.OnEvoke(entity);
            entity.TriggerAnimation("Burst");
            entity.PlaySound(VanillaSoundID.flame);
            var level = entity.Level;
            int startLine = -1;
            int endLine = 1;
            int startCol = 1;
            int endCol = 3;
            var lane = entity.GetLane();
            var column = entity.GetColumn();
            if (lane == 0)
            {
                endLine = 0;
            }
            if (lane == level.GetMaxLaneCount() - 1)
            {
                startLine = 0;
            }
            if (column == level.GetMaxColumnCount() - 1)
            {
                endCol = 1;
            }
            for (int i = startLine; i <= endLine; i++)
            {
                for (int j = startCol; j <= endCol; j++)
                {
                    var param = entity.GetSpawnParams();
                    param.SetProperty(VanillaEntityProps.DAMAGE, entity.GetDamage() * 2);
                    param.SetProperty(VanillaEntityProps.MAX_TIMEOUT, 30);
                    var x = entity.Position.x + level.GetGridWidth() * entity.GetFacingX() * j;
                    var z = entity.Position.z + level.GetGridHeight() * i;
                    var y = level.GetGroundY(x, z);
                    Vector3 gridPos = new Vector3(x, y, z);
                    entity.Spawn(VanillaEffectID.smokerFire, gridPos, param);
                }
            }
        }
        public const int SMOKE_INTERVAL = 60;
        public const int SMOKE_INTERVAL_SHORT = 5;
        public static FrameTimer? GetSmokeTimer(Entity entity) => entity.GetBehaviourField<FrameTimer>(PROP_SMOKE_TIMER);
        public static void SetSmokeTimer(Entity entity, FrameTimer timer) => entity.SetBehaviourField(PROP_SMOKE_TIMER, timer);
        private static readonly NamespaceID ID = VanillaContraptionID.smoker;
        private static readonly VanillaEntityPropertyMeta<FrameTimer> PROP_SMOKE_TIMER = new VanillaEntityPropertyMeta<FrameTimer>("SmokeTimer");
        private Detector smokeDetector;
    }
}
