#nullable enable // autogenerated

using MVZ2Logic.Definitions;

namespace MVZ2.GameContent.HeldItems
{
    [AutoHeldItemDefinition(VanillaHeldItemNames.skywardFamiliar)]
    public class SkywardFamiliarHeldItemDefinition : EntityHeldItemDefinition
    {
        public SkywardFamiliarHeldItemDefinition(string nsp, string name) : base(nsp, name)
        {
            AddBehaviour(VanillaHeldItemBehaviourID.skywardFamiliar);
            AddBehaviour(VanillaHeldItemBehaviourID.rightMouseCancel);
        }
    }
}
