#nullable enable // autogenerated

using PVZEngine.Buffs;
using PVZEngine.Definitions;
using PVZEngine.Modifiers;

namespace MVZ2.GameContent.Buffs.Armors
{
    [AutoBuffDefinition(VanillaBuffNames.Armor.eatenGoldenAppleArmor)]
    public class EatenGoldenAppleArmorBuff : BuffDefinition
    {
        public EatenGoldenAppleArmorBuff(string nsp, string name) : base(nsp, name)
        {
            AddModifier(new ArmorMaxHealthModifier(NumberOperator.AddMultiple, 0.5f));
        }
    }
}
