#nullable enable // autogenerated

using MVZ2.Vanilla.Entities;
using PVZEngine.Buffs;
using PVZEngine.Definitions;
using PVZEngine.Modifiers;

namespace MVZ2.GameContent.Buffs.Enemies
{
    [AutoBuffDefinition(VanillaBuffNames.Enemy.lunaticEnemy)]
    public class LunaticEnemyBuff : BuffDefinition
    {
        public LunaticEnemyBuff(string nsp, string name) : base(nsp, name)
        {
            AddModifier(new FloatModifier(VanillaEntityProps.ATTACK_SPEED, NumberOperator.Multiply, 1.5f));
            AddModifier(new MaxHealthModifier(NumberOperator.Multiply, 1.5f));
        }
    }
}