#nullable enable // autogenerated

using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Properties;
using PVZEngine.Buffs;
using PVZEngine.Level;
using PVZEngine.Modifiers;
using UnityEngine;

namespace MVZ2.GameContent.Buffs.Contraptions
{
    [BuffDefinition(VanillaBuffNames.Contraption.beaconDamage)]
    public class BeaconDamageBuff : BuffDefinition
    {
        public BeaconDamageBuff(string nsp, string name) : base(nsp, name)
        {
            AddModifier(new FloatModifier(VanillaEntityProps.DAMAGE, NumberOperator.AddMultiple, PROP_DAMAGE_MULTIPLIER));
            AddModifier(new Vector3Modifier(VanillaEntityProps.LIGHT_RANGE, NumberOperator.Add, PROP_LIGHT_RANGE_MULTIPLIER));
        }
        public static void SetDamageMultiplier(Buff buff, float value)
        {
            buff.SetProperty(PROP_DAMAGE_MULTIPLIER, value);
        }
        public static void SetLightRangeAddtion(Buff buff, Vector3 value)
        {
            buff.SetProperty(PROP_LIGHT_RANGE_MULTIPLIER, value);
        }
        public static readonly VanillaBuffPropertyMeta<float> PROP_DAMAGE_MULTIPLIER = new VanillaBuffPropertyMeta<float>("damageMultiplier");
        public static readonly VanillaBuffPropertyMeta<Vector3> PROP_LIGHT_RANGE_MULTIPLIER = new VanillaBuffPropertyMeta<Vector3>("lightRangeMultiplier");
    }
}
