#nullable enable // autogenerated

using MVZ2Logic.Entities;
using PVZEngine.Buffs;
using PVZEngine.Definitions;
using PVZEngine.Modifiers;

namespace MVZ2.GameContent.Buffs.Contraptions
{
    [AutoBuffDefinition(VanillaBuffNames.Contraption.softlock)]
    public class SoftlockBuff : BuffDefinition
    {
        public SoftlockBuff(string nsp, string name) : base(nsp, name)
        {
            AddModifier(new BooleanModifier(LogicContraptionProps.NO_EVOKE, true));
        }
    }
}