#nullable enable // autogenerated

using MVZ2.Vanilla.Callbacks;
using MVZ2.Vanilla.Properties;
using PVZEngine;
using PVZEngine.Buffs;
using PVZEngine.Callbacks;
using PVZEngine.Entities;
using PVZEngine.Level;
using Tools;

namespace MVZ2.GameContent.Buffs.Contraptions
{
    [BuffDefinition(VanillaBuffNames.Contraption.lightningOrbEnergyShieldBreak)]
    public class LightningOrbEnergyShieldBreakBuff : BuffDefinition
    {
        public LightningOrbEnergyShieldBreakBuff(string nsp, string name) : base(nsp, name)
        {
            AddTrigger(VanillaLevelCallbacks.PRE_ENTITY_TAKE_DAMAGE, PreEntityTakeDamageCallback);
        }
        public override void OnCreate(Buff buff)
        {
            base.OnCreate(buff);
            buff.SetProperty(PROP_TIMER, new FrameTimer(5));
        }
        public override void PostUpdate(Buff buff)
        {
            base.PostUpdate(buff);
            var timer = buff.GetProperty<FrameTimer>(PROP_TIMER);
            var evoked = buff.GetProperty<bool>(PROP_EVOKED);
            var entity = buff.GetEntity();
            if (timer.RunToExpiredOrNull())
            {
                buff.Remove();
                if (evoked && entity.ExistsAndAlive())
                {
                    entity.AddBuff<LightningOrbEvokedBuff>();
                }
            }
        }
        private void PreEntityTakeDamageCallback(VanillaLevelCallbacks.PreTakeDamageParams param, CallbackResult result)
        {
            var damage = param.input;
            var entity = damage.Entity;
            foreach (var buff in entity.GetBuffs<LightningOrbEnergyShieldBreakBuff>())
            {
                result.SetFinalValue(false);
            }
        }
        public static readonly VanillaBuffPropertyMeta<FrameTimer> PROP_TIMER = new VanillaBuffPropertyMeta<FrameTimer>("timer");
        public static readonly VanillaBuffPropertyMeta<bool> PROP_EVOKED = new VanillaBuffPropertyMeta<bool>("evoked");
    }
}
