#nullable enable // autogenerated

using System.Collections.Generic;
using MVZ2.GameContent.Buffs.Contraptions;
using MVZ2.GameContent.Damages;
using MVZ2.GameContent.Detections;
using MVZ2.GameContent.Effects;
using MVZ2.Vanilla.Audios;
using MVZ2.Vanilla.Callbacks;
using MVZ2.Vanilla.Detections;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Properties;
using MVZ2Logic.Entities;
using MVZ2Logic.Level;
using PVZEngine.Buffs;
using PVZEngine.Callbacks;
using PVZEngine.Definitions;
using PVZEngine.Entities;
using PVZEngine.Modifiers;
using UnityEngine;
using Tools;
using PVZEngine.Damages;
using PVZEngine;
using PVZEngine.Collisions.Level;
using PVZEngine.Level;
using PVZEngine.Collisions;

namespace MVZ2.GameContent.Contraptions
{
    [AutoEntityBehaviourDefinition(VanillaContraptionNames.hellfire)]
    public class Hellfire : ContraptionBehaviour, IDeathEffectsBehaviour
    {
        public Hellfire(string nsp, string name) : base(nsp, name)
        {
            AddModifier(new BooleanModifier(VanillaEntityProps.IS_FIRE, BooleanOperator.SetNot, PROP_EXTINGUISHED));
            AddModifier(new BooleanModifier(LogicEntityProps.IS_LIGHT_SOURCE, BooleanOperator.SetNot, PROP_EXTINGUISHED));
            AddTrigger(VanillaLevelCallbacks.APPLY_DAMAGE_SPECIAL_EFFECTS, ApplyDamageSpecialEffectsCallback, filter: EntityTypes.PLANT);
            detector = new HellfireIgniteDetector(32)
            {
                factionTarget = FactionTarget.Friendly,
                mask = EntityCollisionHelper.MASK_PROJECTILE,
            };
            rekindleDetector = new HellfireIgniteDetector(32)
            {
                factionTarget = FactionTarget.Any,
                mask = EntityCollisionHelper.MASK_ALL,
            };
            burnDetector = new BlackholeDetector();
        }
        public override void Init(Entity entity)
        {
            base.Init(entity);
            SetDamageCooldown(entity, new FrameTimer(DAMAGE_COOLDOWN));
        }
        protected override void UpdateAI(Entity entity)
        {
            base.UpdateAI(entity);
            if (IsExtinguished(entity))
                return;

            detectBuffer.Clear();
            burnDetector.DetectMultiple(entity, detectBuffer);

            var cooldown = GetDamageCooldown(entity);
            if (cooldown.RunToExpiredAndNotNull(entity.GetAttackSpeed()))
            {
                foreach (var targetCollider in detectBuffer)
                {
                    targetCollider.TakeDamage(entity.GetDamage(), new DamageEffectList(VanillaDamageEffects.FIRE), entity);
                    var target = targetCollider.Entity;
                    var effectID = IsCursed(entity) ? VanillaEffectID.cursedFireburn : VanillaEffectID.fireburn;
                    target.Spawn(effectID, target.GetCenter());
                    target.PlaySound(VanillaSoundID.fire, volume: 0.6f);
                }
                cooldown.Reset();
            }
        }
        protected override void UpdateLogic(Entity entity)
        {
            base.UpdateLogic(entity);
            if (!IsExtinguished(entity))
            {
                UpdateIgnite(entity);
            }
            else
            {
                UpdateExtinguished(entity);
            }
            entity.SetAnimationBool("Evoked", IsCursed(entity));
        }
        public void DeathEffects(Entity entity, DeathInfo info)
        {
            if (IsExtinguished(entity))
                return;

            Explode(entity, entity.GetDamage() * 45);
        }
        public override bool CanEvoke(Entity entity)
        {
            if (IsCursed(entity))
                return false;
            var meteor = GetMeteor(entity);
            if (meteor != null && meteor.Exists(entity.Level))
                return false;
            return base.CanEvoke(entity);

        }
        protected override void OnEvoke(Entity entity)
        {
            base.OnEvoke(entity);
            var pos = entity.Position + new Vector3(0, 1280, 0);
            entity.SpawnWithParams(VanillaEffectID.cursedMeteor, pos)?.Let(e =>
            {
                e.SetParent(entity);
                SetMeteor(entity, new EntityID(e));
                e.PlaySound(VanillaSoundID.bombFalling);
            });
        }
        private void ApplyDamageSpecialEffectsCallback(VanillaLevelCallbacks.PostTakeDamageParams param, CallbackResult result)
        {
            var output = param.output;
            var hellfire = output.Entity;
            if (hellfire.HasBehaviour(this) && IsExtinguished(hellfire))
            {
                if (output.BodyResult != null && output.BodyResult.HasEffect(VanillaDamageEffects.FIRE))
                {
                    Rekindle(hellfire);
                }
            }
        }
        private void UpdateIgnite(Entity hellfire)
        {
            bool cursed = IsCursed(hellfire);
            igniteBuffer.Clear();
            detector.DetectEntities(hellfire, igniteBuffer);
            foreach (Entity target in igniteBuffer)
            {
                target.HellfireIgnite(hellfire, cursed);
            }
        }
        private void UpdateExtinguished(Entity hellfire)
        {
            igniteBuffer.Clear();
            rekindleDetector.DetectEntities(hellfire, igniteBuffer);
            foreach (Entity target in igniteBuffer)
            {
                if (target != hellfire && target.IsFire())
                {
                    Rekindle(hellfire);
                    return;
                }
            }
        }
        public static void Extinguish(Entity entity)
        {
            if (IsExtinguished(entity))
                return;
            SetExtinguished(entity, true);
            entity.PlaySound(VanillaSoundID.fizz);
        }
        public static void Rekindle(Entity entity)
        {
            if (!IsExtinguished(entity))
                return;
            SetExtinguished(entity, false);
            entity.PlaySound(VanillaSoundID.fire);
        }
        public static void Curse(Entity entity)
        {
            SetCursed(entity, true);
            entity.AddBuff<HellfireCursedBuff>();
        }
        public static DamageOutput[] Explode(Entity entity, float damage)
        {
            var level = entity.Level;
            List<DamageOutput> damageOutputs = new List<DamageOutput>();
            var border_distance = LevelPositions.RIGHT_BORDER - LevelPositions.LEFT_BORDER;

            var center = new Vector3(LevelPositions.LAWN_CENTER_X, 500, entity.Position.z);
            foreach (var entityCollider in level.OverlapBox(center, new Vector3(border_distance, 1000, 80), OverlapParams.Hostile(entity.GetFaction(), EntityCollisionHelper.MASK_VULNERABLE)))
            {
                var damageEffects = new DamageEffectList(VanillaDamageEffects.FIRE, VanillaDamageEffects.EXPLOSION, VanillaDamageEffects.DAMAGE_BODY_AFTER_ARMOR_BROKEN);
                var damageOutput = entityCollider.TakeDamage(damage, damageEffects, entity);
                if (damageOutput != null)
                {
                    damageOutputs.Add(damageOutput);
                }
            }

            entity.Level.ShakeScreen(10, 0, 15);
            Explosion.Spawn(entity, entity.GetCenter(), BURN_RADIUS);
            entity.PlaySound(VanillaSoundID.explosion);
            entity.PlaySound(VanillaSoundID.flame);
            for (var i = 0; i < Mathf.CeilToInt(border_distance / 80); i++)
            {
                var param = new SpawnParams();
                param.SetProperty(LogicEntityProps.HSV_OFFSET, IsCursed(entity) ? Vector3.right * 90 : Vector3.zero);
                param.SetProperty(LogicEntityProps.LIGHT_COLOR, entity.GetLightColor());
                var x_pos = LevelPositions.LEFT_BORDER + 80 * i;
                entity.Spawn(VanillaEffectID.fireblock, new Vector3(x_pos, entity.Level.GetGroundY(x_pos, entity.Position.z), entity.Position.z), param)?.Let(e =>
                {
                    e.Timeout += i * 2;
                });
            }
            entity.Level.Triggers.RunCallbackFiltered(VanillaLevelCallbacks.POST_CONTRAPTION_DETONATE, new EntityCallbackParams(entity), entity.GetDefinitionID());

            return damageOutputs.ToArray();
        }
        public static void SetCursed(Entity entity, bool value) => entity.SetProperty(PROP_CURSED, value);
        public static bool IsCursed(Entity entity) => entity.GetProperty<bool>(PROP_CURSED);
        public static void SetExtinguished(Entity entity, bool value) => entity.SetProperty(PROP_EXTINGUISHED, value);
        public static bool IsExtinguished(Entity entity) => entity.GetProperty<bool>(PROP_EXTINGUISHED);
        public static void SetMeteor(Entity entity, EntityID value) => entity.SetProperty(PROP_METEOR, value);
        public static EntityID? GetMeteor(Entity entity) => entity.GetProperty<EntityID>(PROP_METEOR);
        public static FrameTimer? GetDamageCooldown(Entity entity) => entity.GetBehaviourField<FrameTimer>(PROP_DAMAGE_COOLDOWN);
        public static void SetDamageCooldown(Entity entity, FrameTimer value) => entity.SetBehaviourField(PROP_DAMAGE_COOLDOWN, value);
        public static readonly VanillaBuffPropertyMeta<bool> PROP_CURSED = new VanillaBuffPropertyMeta<bool>("cursed");
        public static readonly VanillaBuffPropertyMeta<bool> PROP_EXTINGUISHED = new VanillaBuffPropertyMeta<bool>("extinguished");
        public static readonly VanillaBuffPropertyMeta<EntityID> PROP_METEOR = new VanillaBuffPropertyMeta<EntityID>("meteor");
        private Detector detector;
        private Detector rekindleDetector;
        private List<Entity> igniteBuffer = new List<Entity>();
        private static readonly VanillaEntityPropertyMeta<FrameTimer> PROP_DAMAGE_COOLDOWN = new VanillaEntityPropertyMeta<FrameTimer>("DamageCooldown");
        private Detector burnDetector;
        private List<IEntityCollider> detectBuffer = new List<IEntityCollider>();

        public const float BURN_RADIUS = 40;
        public const int DAMAGE_COOLDOWN = 30;
    }
    public interface IHellfireIgniteBehaviour
    {
        void Ignite(Entity entity, Entity hellfire, bool cursed);
    }
}
