#nullable enable // autogenerated

using MVZ2.GameContent.Buffs.Contraptions;
using MVZ2.Vanilla.Audios;
using MVZ2.Vanilla.Callbacks;
using MVZ2.Vanilla.Contraptions;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Properties;
using MVZ2Logic.Level;
using PVZEngine;
using PVZEngine.Buffs;
using PVZEngine.Callbacks;
using PVZEngine.Entities;
using PVZEngine.Level;
using Tools;

namespace MVZ2.GameContent.Contraptions
{
    [EntityBehaviourDefinition(VanillaContraptionNames.lightningOrb)]
    public class LightningOrb : ContraptionBehaviour
    {
        public LightningOrb(string nsp, string name) : base(nsp, name)
        {
            AddTrigger(VanillaLevelCallbacks.PRE_PROJECTILE_HIT, PreProjectileHitCallback);
            AddTrigger(VanillaLevelCallbacks.PRE_ENTITY_HEAL, PreHealCallback);
            AddTrigger(VanillaLevelCallbacks.POST_OBSIDIAN_FIRST_AID, PostObsidianFirstAidCallback);
        }
        public override void Init(Entity entity)
        {
            base.Init(entity);
            var timer = new FrameTimer(REGENERATE_TIME);
            SetShieldRegenerateTimer(entity, timer);
            entity.AddBuff<LightningOrbEnergyShieldBuff>();
        }
        protected override void UpdateAI(Entity contraption)
        {
            base.UpdateAI(contraption);
            if (contraption.HasBuff<LightningOrbEnergyShieldBuff>() || contraption.IsEvoked())
                return;
            var timer = GetShieldRegenerateTimer(contraption);
            if (timer.RunToExpiredAndNotNull(contraption.GetProduceSpeed()))
            {
                timer.Reset();
                contraption.AddBuff<LightningOrbEnergyShieldBuff>();
            }
        }
        protected override void UpdateLogic(Entity contraption)
        {
            base.UpdateLogic(contraption);
            contraption.SetAnimationFloat("Damaged", 1 - contraption.Health / contraption.GetMaxHealth());
            contraption.SetAnimationBool("Absorbing", contraption.HasBuff<LightningOrbEvokedBuff>());
            contraption.SetAnimationBool("Charged", contraption.HasBuff<LightningOrbEnergyShieldBuff>());
        }
        private void PreProjectileHitCallback(VanillaLevelCallbacks.PreProjectileHitParams param, CallbackResult result)
        {
            var hit = param.hit;
            var damage = param.damage;
            if (NamespaceID.IsValid(damage.ShieldTarget))
                return;
            var orb = hit.Other;
            if (!orb.Definition.HasBehaviour(this))
                return;

            var projectile = hit.Projectile;

            orb.HealEffects(100, projectile);
            foreach (var buff in orb.GetBuffs<LightningOrbEvokedBuff>())
            {
                LightningOrbEvokedBuff.AddTakenDamage(buff, damage.Amount);
            }
            projectile.Remove();
            result.SetFinalValue(false);
            orb.PlaySound(VanillaSoundID.energyShieldHit);
        }
        private void PreHealCallback(VanillaLevelCallbacks.PreHealParams param, CallbackResult result)
        {
            var input = param.input;
            var orb = input.Entity;
            if (!orb.Definition.HasBehaviour(this))
                return;
            var healAmount = input.Amount;
            foreach (var buff in orb.GetBuffs<LightningOrbEnergyShieldBuff>())
            {
                LightningOrbEnergyShieldBuff.Heal(buff, healAmount / 10);
            }
        }
        private void PostObsidianFirstAidCallback(EntityCallbackParams param, CallbackResult result)
        {
            var orb = param.entity;
            if (!orb.Definition.HasBehaviour(this))
                return;
            if (!orb.HasBuff<LightningOrbEnergyShieldBuff>())
            {
                var timer = GetShieldRegenerateTimer(orb);
                timer?.ResetTime(REGENERATE_TIME);
                orb.AddBuff<LightningOrbEnergyShieldBuff>();
                return;
            }
            foreach (var buff in orb.GetBuffs<LightningOrbEnergyShieldBuff>())
            {
                LightningOrbEnergyShieldBuff.Heal(buff, LightningOrbEnergyShieldBuff.MAX_HEALTH);
            }
        }
        public override bool CanEvoke(Entity entity)
        {
            if (entity.HasBuff<LightningOrbEvokedBuff>())
                return false;
            return base.CanEvoke(entity);
        }
        protected override void OnEvoke(Entity entity)
        {
            base.OnEvoke(entity);
            entity.PlaySound(VanillaSoundID.lightningAttack);
            entity.AddBuff<LightningOrbEnergyShieldBreakBuff>();
            entity.RemoveBuffs<LightningOrbEnergyShieldBuff>();
            entity.AddBuff<LightningOrbEvokedBuff>();
        }
        public static FrameTimer? GetShieldRegenerateTimer(Entity entity) => entity.GetBehaviourField<FrameTimer>(PROP_TIMER);
        public static void SetShieldRegenerateTimer(Entity entity, FrameTimer timer) => entity.SetBehaviourField(PROP_TIMER, timer);
        public static readonly VanillaBuffPropertyMeta<FrameTimer> PROP_TIMER = new VanillaBuffPropertyMeta<FrameTimer>("timer");
        public const float HEAL_AMOUNT = 100;
        public const int REGENERATE_TIME = 600;
    }
}
