#nullable enable // autogenerated

using MVZ2.GameContent.Buffs;
using MVZ2.GameContent.Detections;
using MVZ2.GameContent.Projectiles;
using MVZ2.GameContent.Stages;
using MVZ2.Vanilla.Audios;
using MVZ2.Vanilla.Contraptions;
using MVZ2.Vanilla.Detections;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Properties;
using MVZ2Logic.Level;
using PVZEngine;
using PVZEngine.Entities;
using PVZEngine.Level;
using Tools;

namespace MVZ2.GameContent.Contraptions
{
    [EntityBehaviourDefinition(VanillaContraptionNames.splitenser)]
    public class Splitenser : DispenserFamily
    {
        public Splitenser(string nsp, string name) : base(nsp, name)
        {
            detectorBack = new DispenserDetector()
            {
                ignoreHighEnemy = true,
                reversed = true,
            };
        }

        public override void Init(Entity entity)
        {
            base.Init(entity);
            InitShootTimer(entity);
            SetEvocationTimer(entity, new FrameTimer(120));
            SetRepeatTimer(entity, new FrameTimer(REPEAT_INTERVAL));
        }
        protected override void UpdateAI(Entity entity)
        {
            base.UpdateAI(entity);
            FeverUpdate(entity);
            if (!entity.IsEvoked())
            {
                ShootTickSplit(entity);
                int repeatCount = GetRepeatCount(entity);
                if (repeatCount > 0)
                {
                    var repeatTimer = GetRepeatTimer(entity);
                    if (repeatTimer.RunToExpiredAndNotNull(entity.GetAttackSpeed()))
                    {
                        ShootBack(entity);
                        SetRepeatCount(entity, repeatCount - 1);
                        repeatTimer.Reset();
                    }
                }

                return;
            }

            EvokedUpdate(entity);
        }
        protected override void UpdateLogic(Entity entity)
        {
            base.UpdateLogic(entity);
            entity.SetAnimationBool("Fever", IsFever(entity));
        }
        public void ShootTickSplit(Entity entity)
        {
            var shootTimer = GetShootTimer(entity);
            if (shootTimer.RunToExpiredAndNotNull(entity.GetAttackSpeed()))
            {
                var frontTarget = detector.Detect(entity);
                if (frontTarget != null)
                {
                    ShootFront(entity);
                }
                var backTarget = detectorBack.Detect(entity);
                if (backTarget != null)
                {
                    RepeatShootBack(entity);
                }
                shootTimer.ResetTime(GetTimerTime(entity));
            }
        }
        public Entity? ShootFront(Entity entity)
        {
            entity.TriggerAnimation("ShootFront");
            return entity.ShootProjectile()?.Let(e =>
            {
                if (IsFever(entity))
                {
                    var behaviour = e.Definition?.GetBehaviour<IHellfireIgniteBehaviour>();
                    behaviour?.Ignite(e, entity, false);
                }
            });
        }
        public Entity? ShootBack(Entity entity)
        {
            entity.TriggerAnimation("ShootBack");

            var param = entity.GetShootParams();

            var offset = entity.GetShotOffset();
            offset.x *= -1;
            offset = entity.ModifyShotOffset(offset);
            param.position = entity.Position + offset;

            param.projectileID = VanillaProjectileID.knife;
            param.damage = entity.GetDamage() * 3 / 4;
            var vel = param.velocity;
            vel.x *= -1;
            param.velocity = vel;
            
            return entity.ShootProjectile(param)?.Let(e =>
            {
                if (IsFever(entity))
                {
                    var behaviour = e.Definition?.GetBehaviour<ITeslaCoilElectrifyBehaviour>();
                    behaviour?.Electrify(e, entity);
                }
            });
        }
        public Entity? BurstShootFront(Entity entity, float multipiler)
        {
            entity.TriggerAnimation("ShootFront");

            var param = entity.GetShootParams();

            var vel = param.velocity;
            param.velocity = vel.normalized * multipiler;
            param.projectileID = VanillaProjectileID.knife;
            param.damage = entity.GetDamage() * 3 / 4;

            param.soundID = null;
            return entity.ShootProjectile(param)?.Let(e =>
            {
                if (IsFever(entity))
                {
                    var behaviour = e.Definition?.GetBehaviour<ITeslaCoilElectrifyBehaviour>();
                    behaviour?.Electrify(e, entity);
                }
            });
        }
        public Entity? ShootLargeArrowBack(Entity entity)
        {
            entity.TriggerAnimation("ShootBack");

            var param = entity.GetShootParams();

            var offset = entity.GetShotOffset();
            offset.x *= -1;
            offset = entity.ModifyShotOffset(offset);
            param.position = entity.Position + offset;

            var vel = param.velocity;
            vel.x *= -1;
            param.velocity = vel.normalized;

            param.projectileID = VanillaProjectileID.largeArrow;
            param.damage = entity.GetDamage() * 30;
            param.soundID = VanillaSoundID.spellCard;

            return entity.ShootProjectile(param)?.Let(e =>
            {
                if (IsFever(entity))
                {
                    var behaviour = e.Definition?.GetBehaviour<IHellfireIgniteBehaviour>();
                    behaviour?.Ignite(e, entity, false);
                }
            });
        }
        public void RepeatShootBack(Entity entity)
        {
            SetRepeatCount(entity, 2);
            var repeatTimer = GetRepeatTimer(entity);
            if (repeatTimer != null)
            {
                repeatTimer.ResetTime(REPEAT_INTERVAL);
                repeatTimer.Frame = 0;
            }
        }
        protected override void OnEvoke(Entity entity)
        {
            base.OnEvoke(entity);
            var evocationTimer = GetEvocationTimer(entity);
            if (evocationTimer != null)
            {
                evocationTimer.Reset();
            }
            entity.SetEvoked(true);
        }
        public void FeverUpdate(Entity entity)
        {
            if (!entity.Level.HasBehaviour<WaveStageBehaviour>())
                return;
            SetFever(entity, WaveStageBehaviour.IsHighWave(entity.Level));
            if (IsFever(entity))
            {
                if (PlaySound(entity))
                {
                    entity.PlaySound(VanillaSoundID.pearlBoost);
                    WhiteFlashBuff.AddToEntity(entity, 30);
                    SetPlaySound(entity, false);
                }
            }
            else
            {
                SetPlaySound(entity, true);
            }
        }
        public static FrameTimer? GetEvocationTimer(Entity entity) => entity.GetBehaviourField<FrameTimer>(PROP_EVOCATION_TIMER);
        public static void SetEvocationTimer(Entity entity, FrameTimer timer) => entity.SetBehaviourField(PROP_EVOCATION_TIMER, timer);
        public static FrameTimer? GetRepeatTimer(Entity entity) => entity.GetBehaviourField<FrameTimer>(PROP_REPEAT_TIMER);
        public static void SetRepeatTimer(Entity entity, FrameTimer timer) => entity.SetBehaviourField(PROP_REPEAT_TIMER, timer);
        public static int GetRepeatCount(Entity entity) => entity.GetBehaviourField<int>(PROP_REPEAT_COUNT);
        public static void SetRepeatCount(Entity entity, int timer) => entity.SetBehaviourField(PROP_REPEAT_COUNT, timer);
        public static void SetFever(Entity entity, bool value) => entity.SetBehaviourField(PROP_FEVER, value);
        public static bool IsFever(Entity entity) => entity.GetBehaviourField<bool>(PROP_FEVER);
        public static void SetPlaySound(Entity entity, bool value) => entity.SetBehaviourField(PROP_PLAY_SOUND, value);
        public static bool PlaySound(Entity entity) => entity.GetBehaviourField<bool>(PROP_PLAY_SOUND);
        private void EvokedUpdate(Entity entity)
        {
            var evocationTimer = GetEvocationTimer(entity);
            if (evocationTimer == null)
                return;
            evocationTimer.Run();
            if (evocationTimer.PassedInterval(2))
            {
                var frontProjectile = ShootFront(entity);
                if (frontProjectile != null)
                    frontProjectile.Velocity *= 2;

                var backProjectile = ShootBack(entity);
                if (backProjectile != null)
                    backProjectile.Velocity *= 2;
            }
            if (evocationTimer.Expired)
            {
                ShootLargeArrowBack(entity);
                for (var i = 0; i < 10; i++)
                {
                    BurstShootFront(entity, i + 1);
                }
                entity.SetEvoked(false);
                var shootTimer = GetShootTimer(entity);
                shootTimer?.Reset();
            }
        }
        private Detector detectorBack;
        public const int REPEAT_INTERVAL = 5;
        public static readonly VanillaEntityPropertyMeta<FrameTimer> PROP_EVOCATION_TIMER = new VanillaEntityPropertyMeta<FrameTimer>("EvocationTimer");
        public static readonly VanillaEntityPropertyMeta<FrameTimer> PROP_REPEAT_TIMER = new VanillaEntityPropertyMeta<FrameTimer>("RepeatTimer");
        public static readonly VanillaEntityPropertyMeta<int> PROP_REPEAT_COUNT = new VanillaEntityPropertyMeta<int>("RepeatCount");
        public static readonly VanillaEntityPropertyMeta<bool> PROP_FEVER = new VanillaEntityPropertyMeta<bool>("Fever");
        public static readonly VanillaEntityPropertyMeta<bool> PROP_PLAY_SOUND = new VanillaEntityPropertyMeta<bool>("PlaySound", true);
    }
}
