#nullable enable // autogenerated

using System.Linq;
using MVZ2.GameContent.Buffs.Contraptions;
using MVZ2.GameContent.Buffs.Enemies;
using MVZ2.GameContent.Effects;
using MVZ2.Vanilla.Audios;
using MVZ2.Vanilla.Callbacks;
using MVZ2.Vanilla.Entities;
using MVZ2Logic.Entities;
using PVZEngine.Buffs;
using PVZEngine.Callbacks;
using PVZEngine.Definitions;
using PVZEngine.Entities;
using Tools;
using UnityEngine;

namespace MVZ2.GameContent.Contraptions
{
    [AutoEntityBehaviourDefinition(VanillaContraptionNames.youkaiLeaf)]
    public class YoukaiLeaf : DispenserFamily
    {
        public YoukaiLeaf(string nsp, string name) : base(nsp, name)
        {
            AddTrigger(VanillaLevelCallbacks.POST_ENEMY_MELEE_ATTACK, PostEnemyMeleeAttackCallback);
        }
        public override void Init(Entity entity)
        {
            base.Init(entity);
            InitShootTimer(entity);
        }
        protected override void UpdateAI(Entity entity)
        {
            base.UpdateAI(entity);
            if (!entity.IsEvoked())
            {
                ShootTick(entity);
            }
        }
        protected override void UpdateLogic(Entity entity)
        {
            base.UpdateLogic(entity);
            entity.SetAnimationBool("Sleep", entity.HasBuff<NocturnalBuff>() || entity.HasBuff<DreamSilkBuff>());
        }
        private void PostEnemyMeleeAttackCallback(VanillaLevelCallbacks.EnemyMeleeAttackParams param, CallbackResult result)
        {
            var enemy = param.enemy;
            var target = param.target;
            if (!target.IsEntityOf(VanillaContraptionID.youkaiLeaf))
                return;
            if (!target.IsHostile(enemy))
                return;
            if (target.IsAIFrozen())
                return;
            target.SpawnWithParams(enemy.GetDefinitionID(), target.Position)?.Let(e =>
            {
                e.AddBuff<YoukaiLeafBuff>();
                target.Level.Spawn(VanillaEffectID.smokeCluster, target.GetCenter(), target)?.Let(s =>
                {
                    s.SetTint(new Color(0, 1, 0, 1));
                });
            });
            target.Remove();
        }
        protected override void OnEvoke(Entity entity)
        {
            base.OnEvoke(entity);
            entity.PlaySound(VanillaSoundID.meow);
            entity.PlaySound(VanillaSoundID.nimbleFabric);
            var enemies = entity.Level.FindEntities(e => e.Type == EntityTypes.ENEMY && !e.IsNotActiveEnemy()).RandomTake(3, entity.RNG);
            if (enemies.Count() <= 0)
                return;
            var imitate_number = enemies.Count();
            var choose_imitate = enemies.Random(entity.RNG);
            foreach (var enemy in enemies)
            {
                entity.SpawnWithParams(enemy.GetDefinitionID(), entity.Position)?.Let(e =>
                {
                    e.AddBuff<YoukaiLeafBuff>();
                });
            }
            if (imitate_number < 3)
            {
                for (var i = 0; i < 3 - imitate_number; i++)
                {
                    entity.SpawnWithParams(choose_imitate.GetDefinitionID(), entity.Position)?.Let(e =>
                    {
                        e.AddBuff<YoukaiLeafBuff>();
                    });
                }
            }
            entity.Spawn(VanillaEffectID.smokeCluster, entity.GetCenter())?.Let(s =>
            {
                s.SetTint(new Color(0, 1, 0, 1));
            });
            entity.Remove();
        }
    }
}
