#nullable enable // autogenerated

using MVZ2.Vanilla.Audios;
using MVZ2.Vanilla.Callbacks;
using MVZ2.Vanilla.Entities;
using MVZ2Logic.Entities;
using PVZEngine.Callbacks;
using PVZEngine.Definitions;
using PVZEngine.Entities;
using UnityEngine;

namespace MVZ2.GameContent.Projectiles
{
    [AutoEntityBehaviourDefinition(VanillaProjectileNames.bounceBoulder)]
    public class BounceBoulder : EntityBehaviourDefinition
    {
        public BounceBoulder(string nsp, string name) : base(nsp, name)
        {
            AddTrigger(VanillaLevelCallbacks.POST_PROJECTILE_HIT, PostHitEntityCallback);
        }
        public override void PostContactGround(Entity projectile, Vector3 velocity)
        {
            base.PostContactGround(projectile, velocity);
            if (!projectile.IsAboveLand())
                return;
            projectile.Velocity = new Vector3(projectile.Velocity.x, 10f, projectile.Velocity.z);
        }
        private void PostHitEntityCallback(VanillaLevelCallbacks.PostProjectileHitParams param, CallbackResult result)
        {
            var hitResult = param.hit;
            var projectile = hitResult.Projectile;
            if (!projectile.Definition.HasBehaviour(this))
                return;
            var other = hitResult.Other;
            projectile.Velocity = new Vector3(projectile.Velocity.x, 10f, projectile.Velocity.z);
            if (other.Type == EntityTypes.ENEMY)
            {
                var vel = other.Velocity;
                vel.x += 5 * Mathf.Sign(projectile.Velocity.x) * other.GetWeakKnockbackMultiplier();
                other.Velocity = vel;
                projectile.PlaySound(VanillaSoundID.bash);
            }
        }
    }
}
