#nullable enable // autogenerated

using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Properties;
using PVZEngine;
using PVZEngine.Damages;
using PVZEngine.Entities;
using PVZEngine.Level;

namespace MVZ2.GameContent.Projectiles
{
    [EntityBehaviourDefinition(VanillaEntityBehaviourNames.gemBall)]
    public class GemBallBehaviour : GoldenBall
    {
        public GemBallBehaviour(string nsp, string name) : base(nsp, name)
        {
        }
        protected override void PostHitEntity(ProjectileHitOutput hitResult, DamageOutput? damage)
        {
            base.PostHitEntity(hitResult, damage);
            var projectile = hitResult.Projectile;
            NamespaceID? gemID = projectile.GetProperty<NamespaceID>(PROP_GEM_ID);
            if (projectile.RNG.Next(100) < projectile.GetProperty<float>(PROP_GEM_CHANCE) && gemID != null)
            {
                projectile.Produce(gemID);
            }
        }
        public static readonly VanillaEntityPropertyMeta<float> PROP_GEM_CHANCE = new VanillaEntityPropertyMeta<float>("gem_chance");
        public static readonly VanillaEntityPropertyMeta<NamespaceID> PROP_GEM_ID = new VanillaEntityPropertyMeta<NamespaceID>("gem_id");
    }
}
