#nullable enable // autogenerated

using System.Linq;
using MVZ2.GameContent.Buffs;
using MVZ2.GameContent.Buffs.Enemies;
using MVZ2.GameContent.Damages;
using MVZ2.GameContent.Effects;
using MVZ2.GameContent.Projectiles;
using MVZ2.Vanilla.Audios;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Level;
using MVZ2Logic.Level;
using PVZEngine.Buffs;
using PVZEngine.Damages;
using PVZEngine.Entities;
using Tools;
using UnityEngine;

namespace MVZ2.GameContent.Bosses
{
    public partial class Crescent
    {
        #region 状态机
        private class CrescentStateMachine : EntityStateMachine
        {
            public CrescentStateMachine()
            {
                AddState(new AppearState());
                AddState(new IdleState());
                AddState(new DashState());
                AddState(new CocoonState());
                AddState(new ThrowState());
                AddState(new DeadState());
            }
        }
        public static void UpdatePosition(Entity entity)
        {
            var posi = GetPositionBeforeDash(entity);
            var pos = entity.Position;
            pos.x = pos.x * 0.3f + posi.x * 0.7f;
            pos.y = pos.y * 0.3f + posi.y * 0.7f;
            pos.z = pos.z * 0.3f + posi.z * 0.7f;
            entity.Position = pos;
        }
        private class AppearState : EntityStateMachineState
        {
            public AppearState() : base(STATE_APPEAR, ANIMATION_STATE_APPEAR) { }
            public override void OnEnter(EntityStateMachine stateMachine, Entity entity)
            {
                base.OnEnter(stateMachine, entity);
                var stateTimer = stateMachine.GetStateTimer(entity);
                stateTimer.ResetTime(30);
                StopFly(entity);
            }
            public override void OnUpdateAI(EntityStateMachine stateMachine, Entity entity)
            {
                base.OnUpdateAI(stateMachine, entity);
                var nextStateTimer = stateMachine.GetStateTimer(entity);
                nextStateTimer.Run(stateMachine.GetSpeed(entity));
                if (!nextStateTimer.Expired)
                    return;
                stateMachine.StartState(entity, STATE_IDLE);
                Fly(entity);
            }
        }
        private class IdleState : EntityStateMachineState
        {
            public IdleState() : base(STATE_IDLE, ANIMATION_STATE_IDLE) { }
            public override void OnEnter(EntityStateMachine stateMachine, Entity entity)
            {
                base.OnEnter(stateMachine, entity);
                var stateTimer = stateMachine.GetStateTimer(entity);
                stateTimer.ResetTime(60);
            }
            public override void OnExit(EntityStateMachine stateMachine, Entity entity)
            {
                base.OnExit(stateMachine, entity);
                SetAlterJump(entity, !AlterJump(entity));
            }
            public override void OnUpdateAI(EntityStateMachine stateMachine, Entity entity)
            {
                base.OnUpdateAI(stateMachine, entity);
                var nextStateTimer = stateMachine.GetStateTimer(entity);
                nextStateTimer.Run(stateMachine.GetSpeed(entity));
                if (!nextStateTimer.Expired)
                    return;

                var lastState = stateMachine.GetPreviousState(entity);

                if (lastState == STATE_DASH)
                {
                    lastState = STATE_COCOON;
                }
                else if (lastState == STATE_COCOON)
                {
                    lastState = STATE_THROW;
                }
                else
                {
                    lastState = STATE_DASH;
                }
                stateMachine.StartState(entity, lastState);
                stateMachine.SetPreviousState(entity, lastState);
            }
        }
        private class DashState : EntityStateMachineState
        {
            public DashState() : base(STATE_DASH, ANIMATION_STATE_DASH) { }
            public override void OnEnter(EntityStateMachine stateMachine, Entity entity)
            {
                base.OnEnter(stateMachine, entity);
                var stateTimer = stateMachine.GetSubStateTimer(entity);
                stateTimer.ResetTime(15);
                entity.PlaySound(VanillaSoundID.crescentPreDash);
                SetPositionBeforeDash(entity, entity.Position + Vector3.right * 80 * (entity.Position.x < VanillaLevelExt.LAWN_CENTER_X ? -1 : 1));
            }
            public override void OnUpdateAI(EntityStateMachine stateMachine, Entity entity)
            {
                base.OnUpdateAI(stateMachine, entity);
                var grid = entity.Level.GetAllGrids().Where(g => g.Column == (entity.Position.x < VanillaLevelExt.LAWN_CENTER_X ? entity.Level.GetMaxColumnCount() - 1 : 0)).Random(entity.RNG);
                var endGrid = entity.Level.GetAllGrids().Where(g => g.Column >= 2 && g.Column <= 6).Random(entity.RNG);

                var concealLanes = entity.Level.GetAllLanes().Where(l => 
                {
                    bool noGas = true;
                    foreach (var item in entity.Level.FindEntities(VanillaEffectID.concealingSmoke))
                    {
                        if (item.GetLane() == l)
                            noGas = false;
                    }
                    return noGas;
                });
                var deviceGrids = entity.Level.GetAllGrids().Where(g => g.GetEntities().Any(e => !e.HasBuff(VanillaBuffID.Entity.crescentAntiGravity)));

                var dir = (grid.GetEntityPosition() - new Vector3(entity.Position.x, entity.GetGroundY(), entity.Position.z)).normalized;
                var subStateTimer = stateMachine.GetSubStateTimer(entity);
                subStateTimer.Run(stateMachine.GetSpeed(entity));
                var substate = stateMachine.GetSubState(entity);
                if (subStateTimer.Expired)
                {
                    switch (substate)
                    {
                        case SUBSTATE_PREPARE:
                        case SUBSTATE_DASH_1:
                        case SUBSTATE_DASH_2:
                        case SUBSTATE_DASH_3:
                            stateMachine.StartSubState(entity, substate + 1);
                            entity.PlaySound(VanillaSoundID.crescentDash);
                            SetDashDir(entity, dir);
                            subStateTimer.ResetTime(40);
                            ResetPosition(entity);
                            break;
                        case SUBSTATE_DASH_4:
                            stateMachine.StartSubState(entity, SUBSTATE_END);
                            SetPositionBeforeDash(entity, endGrid.GetEntityPosition() + Vector3.up * HEIGHT);
                            subStateTimer.ResetTime(15);
                            break;
                        case SUBSTATE_END:
                            stateMachine.StartState(entity, STATE_IDLE);
                            break;
                    }
                }
                else
                {
                    switch (substate)
                    {
                        case SUBSTATE_DASH_1:
                        case SUBSTATE_DASH_2:
                        case SUBSTATE_DASH_3:
                        case SUBSTATE_DASH_4:
                            entity.Velocity = GetDashDir(entity) * 30;
                            if (subStateTimer.PassedFrame(20))
                            {
                                var concealGrid = entity.Level.GetAllGrids().Random(entity.RNG);
                                if (concealLanes.Count() > 0)
                                {
                                    var concealLane = concealLanes.Random(entity.RNG);
                                    concealGrid = entity.Level.GetAllGrids().Where(g => g.Lane == concealLane).Random(entity.RNG);
                                }
                                entity.SpawnWithParams(VanillaProjectileID.deliciousTroll, entity.GetCenter())?.Let(e =>
                                {
                                    e.Velocity = VanillaProjectileExt.GetLobVelocityByTime(entity.GetCenter(), concealGrid.GetEntityPosition(), 30, e.GetGravity());
                                });
                            }
                            if (subStateTimer.PassedInterval(20))
                            {
                                if (deviceGrids.Count() > 0)
                                {
                                    var deviceGrid = deviceGrids.Random(entity.RNG);
                                    entity.SpawnWithParams(VanillaProjectileID.antigravityDevice, entity.GetCenter())?.Let(e =>
                                    {
                                        e.Velocity = VanillaProjectileExt.GetLobVelocityByTime(entity.GetCenter(), deviceGrid.GetEntityPosition(), 15, e.GetGravity());
                                    });
                                }
                            }
                            break;
                        case SUBSTATE_PREPARE:
                        case SUBSTATE_END:
                            entity.Velocity = Vector3.zero;
                            UpdatePosition(entity);
                            break;
                    }
                }
            }
            private void ResetPosition(Entity entity)
            {
                var pos1 = entity.Position;
                if (pos1.x < VanillaLevelExt.ENEMY_LEFT_BORDER)
                {
                    pos1.x = VanillaLevelExt.ENEMY_LEFT_BORDER;
                    entity.Position = pos1;
                }
                else if (pos1.x > VanillaLevelExt.ENEMY_RIGHT_BORDER)
                {
                    pos1.x = VanillaLevelExt.ENEMY_RIGHT_BORDER;
                    entity.Position = pos1;
                }
            }

            public const int SUBSTATE_PREPARE = 0;
            public const int SUBSTATE_DASH_1 = 1;
            public const int SUBSTATE_DASH_2 = 2;
            public const int SUBSTATE_DASH_3 = 3;
            public const int SUBSTATE_DASH_4 = 4;
            public const int SUBSTATE_END = 5;
        }
        private class CocoonState : EntityStateMachineState
        {
            public CocoonState() : base(STATE_COCOON, ANIMATION_STATE_COCOON) { }
            public override void OnEnter(EntityStateMachine stateMachine, Entity entity)
            {
                base.OnEnter(stateMachine, entity);
                var stateTimer = stateMachine.GetSubStateTimer(entity);
                stateTimer.ResetTime(5);
            }
            public override void OnUpdateAI(EntityStateMachine stateMachine, Entity entity)
            {
                base.OnUpdateAI(stateMachine, entity);
                var cocoonGrid = entity.Level.GetAllGrids().Where(g => g.Column >= entity.Level.GetMaxColumnCount() - 3 && g.Column < entity.Level.GetMaxColumnCount()).Random(entity.RNG);
                var subStateTimer = stateMachine.GetSubStateTimer(entity);
                subStateTimer.Run(stateMachine.GetSpeed(entity));
                var substate = stateMachine.GetSubState(entity);
                switch (substate)
                {
                    case SUBSTATE_ENTER:
                        entity.Velocity = Vector3.zero;
                        UpdatePosition(entity);
                        if (subStateTimer.Expired)
                        {
                            stateMachine.StartSubState(entity, SUBSTATE_STAY);
                            subStateTimer.ResetTime(150);
                        }
                        break;
                    case SUBSTATE_STAY:
                        if (subStateTimer.PassedInterval(5))
                        {
                            entity.PlaySound(VanillaSoundID.bow);
                            entity.SpawnWithParams(VanillaProjectileID.terrorCocoon, entity.GetCenter())?.Let(e =>
                            {
                                e.Velocity = VanillaProjectileExt.GetLobVelocityByTime(entity.GetCenter(), cocoonGrid.GetEntityPosition(), 30, e.GetGravity());
                            });
                        }
                        if (subStateTimer.Expired)
                        {
                            stateMachine.StartSubState(entity, SUBSTATE_END);
                            subStateTimer.ResetTime(15);
                        }
                        break;
                    case SUBSTATE_END:
                        entity.Velocity = Vector3.zero;
                        UpdatePosition(entity);
                        if (subStateTimer.Expired)
                        {
                            stateMachine.StartState(entity, STATE_IDLE);
                        }
                        break;
                }
            }
            public const int SUBSTATE_ENTER = 0;
            public const int SUBSTATE_STAY = 1;
            public const int SUBSTATE_END = 2;
        }

        private class ThrowState : EntityStateMachineState
        {
            public ThrowState() : base(STATE_THROW, ANIMATION_STATE_THROW) { }
            public override void OnEnter(EntityStateMachine stateMachine, Entity entity)
            {
                base.OnEnter(stateMachine, entity);
                var stateTimer = stateMachine.GetSubStateTimer(entity);
                stateTimer.ResetTime(35);
                entity.PlaySound(VanillaSoundID.throwSound);
            }
            public override void OnUpdateAI(EntityStateMachine stateMachine, Entity entity)
            {
                base.OnUpdateAI(stateMachine, entity);
                var grid = entity.Level.GetAllGrids().Random(entity.RNG);
                var subStateTimer = stateMachine.GetSubStateTimer(entity);
                subStateTimer.Run(stateMachine.GetSpeed(entity));
                var substate = stateMachine.GetSubState(entity);
                switch (substate)
                {
                    case SUBSTATE_THROW:
                        if (subStateTimer.PassedFrame(18))
                        {
                            var vector = new Vector3(0, 40, 0);
                            entity.PlaySound(VanillaSoundID.explosion);
                            entity.PlaySound(VanillaSoundID.reflection);
                            entity.Explode(entity.GetCenter() + vector, 120, entity.GetFaction(), entity.GetDamage(), new DamageEffectList(VanillaDamageEffects.EXPLOSION));
                            Explosion.Spawn(entity, entity.GetCenter() + vector, 120);
                            entity.Level.ShakeScreen(10, 0, 10);
                            var param = entity.GetSpawnParams();
                            param.SetProperty(VanillaEntityProps.DAMAGE, entity.GetDamage() / 2);
                            entity.Spawn(VanillaProjectileID.darkMatterBall, entity.GetCenter() + vector, param)?.Let(e =>
                            {
                                e.Velocity = Vector3.up * 20;
                            });
                        }
                        if (subStateTimer.Expired)
                        {
                            stateMachine.StartSubState(entity, SUBSTATE_END);
                            subStateTimer.ResetTime(10);
                        }
                        break;
                    case SUBSTATE_END:
                        if (subStateTimer.Expired)
                        {
                            stateMachine.StartState(entity, STATE_IDLE);
                        }
                        break;
                }
            }

            public const int SUBSTATE_THROW = 0;
            public const int SUBSTATE_END = 1;
        }
        private class DeadState : EntityStateMachineState
        {
            public DeadState() : base(STATE_DEAD, ANIMATION_STATE_DEATH) { }
            public override void OnEnter(EntityStateMachine stateMachine, Entity entity)
            {
                base.OnEnter(stateMachine, entity);
                entity.Velocity = Vector3.zero;
                entity.TriggerAnimation("Shock");
                Vector3 pos = new Vector3(entity.Level.GetEntityColumnX(4), 0, entity.Level.GetEntityLaneZ(2));
                SetPositionBeforeDash(entity, pos + Vector3.up * HEIGHT);
                var stateTimer = stateMachine.GetSubStateTimer(entity);
                stateTimer.ResetTime(60);
            }
            public override void OnUpdateLogic(EntityStateMachine stateMachine, Entity entity)
            {
                base.OnUpdateLogic(stateMachine, entity);
                var subStateTimer = stateMachine.GetSubStateTimer(entity);
                subStateTimer.Run();
                var substate = stateMachine.GetSubState(entity);
                switch (substate)
                {
                    case SUBSTATE_ENTER:
                    case SUBSTATE_SHOCK_0:
                    case SUBSTATE_SHOCK_1:
                    case SUBSTATE_SHOCK_2:
                        entity.Velocity = Vector3.zero;
                        var posi = GetPositionBeforeDash(entity);
                        var pos = entity.Position;
                        pos.x = pos.x * 0.3f + posi.x * 0.7f;
                        pos.y = pos.y * 0.3f + posi.y * 0.7f;
                        pos.z = pos.z * 0.3f + posi.z * 0.7f;
                        entity.Position = pos;

                        if (subStateTimer.Expired)
                        {
                            entity.TriggerAnimation("Shock");
                            stateMachine.StartSubState(entity, substate + 1);
                            entity.PlaySound(VanillaSoundID.crescentShock);
                            subStateTimer.ResetTime(60 - substate * 18);
                            entity.Spawn(VanillaEffectID.nightmareFireParticles, entity.GetCenter());
                        }
                        break;
                    case SUBSTATE_SHOCK_3:
                        if (subStateTimer.Expired)
                        {
                            Explosion.Spawn(entity, entity.GetCenter(), 120);
                            entity.PlaySound(VanillaSoundID.explosion);
                            stateMachine.StartSubState(entity, SUBSTATE_END);
                            subStateTimer.ResetTime(45);
                        }
                        break;
                    case SUBSTATE_END:
                        StopFly(entity);
                        entity.AddBuff<NightmareaperFallBuff>();
                        entity.Velocity = Vector3.up * 20;
                        if (subStateTimer.Expired)
                        {
                            entity.Spawn(VanillaEffectID.darkMatterParticles, entity.Position);
                            Explosion.Spawn(entity, entity.GetCenter(), 120);
                            entity.PlaySound(VanillaSoundID.explosion);
                            entity.Remove();
                        }
                        break;
                }
            }
            public const int SUBSTATE_ENTER = 0;
            public const int SUBSTATE_SHOCK_0 = 1;
            public const int SUBSTATE_SHOCK_1 = 2;
            public const int SUBSTATE_SHOCK_2 = 3;
            public const int SUBSTATE_SHOCK_3 = 4;
            public const int SUBSTATE_END = 5;
        }
        #endregion
        public const int ANIMATION_STATE_IDLE = 0;
        public const int ANIMATION_STATE_APPEAR = 1;
        public const int ANIMATION_STATE_DASH = 2;
        public const int ANIMATION_STATE_COCOON = 3;
        public const int ANIMATION_STATE_THROW = 4;
        public const int ANIMATION_STATE_DEATH = 5;
    }
}