#nullable enable // autogenerated

using MVZ2.GameContent.Models;
using MVZ2.Vanilla.Audios;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Models;
using MVZ2.Vanilla.Properties;
using MVZ2Logic.Entities;
using MVZ2Logic.Models;
using PVZEngine;
using PVZEngine.Buffs;
using PVZEngine.Definitions;
using PVZEngine.Entities;
using PVZEngine.Modifiers;
using Tools;
using UnityEngine;

namespace MVZ2.GameContent.Buffs.Contraptions
{
    [AutoBuffDefinition(VanillaBuffNames.Contraption.hackerGlitched)]
    public class HackerGlitchedBuff : BuffDefinition
    {
        public HackerGlitchedBuff(string nsp, string name) : base(nsp, name)
        {
            AddModifier(new BooleanModifier(VanillaEntityProps.AI_FROZEN, PROP_GLITCHED));
            AddModifier(new Vector3Modifier(EngineEntityProps.DISPLAY_SCALE, NumberOperator.Multiply, PROP_SCALE));
            AddModelInsertion(LogicModelHelper.ANCHOR_CENTER, VanillaModelKeys.glitched, VanillaModelID.glitched);
        }
        public override void OnCreate(Buff buff)
        {
            base.OnCreate(buff);
            SetTimer(buff, TimerHelper.NewSecondTimer(DEFAULT_DELAY_SECONDS), TimerHelper.NewSecondTimer(DEFAULT_SECONDS));
        }
        public override void PostUpdate(Buff buff)
        {
            base.PostUpdate(buff);
            var entity = buff.GetEntity();
            if (!entity.ExistsAndAlive())
            {
                buff.Remove();
                return;
            }
            var delayTimeout = buff.GetProperty<FrameTimer>(PROP_DELAY_TIMEOUT);
            if (delayTimeout.RunToExpiredOrNull())
            {
                var preBugged = buff.GetProperty<bool>(PROP_GLITCHED);
                var iconModel = buff.GetInsertedModel(VanillaModelKeys.glitched);
                iconModel?.SetAnimationBool("PlayParticle", true);

                var timeout = buff.GetProperty<FrameTimer>(PROP_TIMEOUT);
                if (timeout.RunToExpiredOrNull())
                {
                    buff.Remove();
                    if (preBugged)
                    {
                        entity.PlaySound(VanillaSoundID.dataminer);
                    }
                    return;
                }
                if (timeout.PassedInterval(Ticks.FromSeconds(2)))
                {
                    var bugged = entity.RNG.Next(2) == 0;
                    if (preBugged != bugged)
                    {
                        entity.PlaySound(VanillaSoundID.dataminer);
                        var scale = bugged ? new Vector3(entity.RNG.Next(0.5f, 1.5f), entity.RNG.Next(0.5f, 1.5f), entity.RNG.Next(0.5f, 1.5f)) : Vector3.one;
                        buff.SetProperty(PROP_SCALE, scale);
                    }
                    buff.SetProperty(PROP_GLITCHED, bugged);
                }
            }
        }
        public static FrameTimer? GetDelayTimer(Buff buff)
        {
            return buff.GetProperty<FrameTimer>(PROP_DELAY_TIMEOUT);
        }
        public static FrameTimer? GetTimer(Buff buff)
        {
            return buff.GetProperty<FrameTimer>(PROP_TIMEOUT);
        }
        public static void SetTimer(Buff buff, FrameTimer? delayValue, FrameTimer? value)
        {
            buff.SetProperty(PROP_DELAY_TIMEOUT, delayValue);
            buff.SetProperty(PROP_TIMEOUT, value);
        }
        public static void MaxDelayTime(Buff buff, int frames)
        {
            var timer = GetDelayTimer(buff);
            if (timer == null || timer.Frame >= frames)
                return;
            timer.ResetTime(frames);
        }
        public static void MaxTime(Buff buff, int frames)
        {
            var timer = GetTimer(buff);
            if (timer == null || timer.Frame >= frames)
                return;
            timer.ResetTime(frames);
        }
        public const float DEFAULT_DELAY_SECONDS = 16f;
        public const float DEFAULT_SECONDS = 64f;
        public static readonly VanillaBuffPropertyMeta<FrameTimer> PROP_TIMEOUT = new VanillaBuffPropertyMeta<FrameTimer>("Timeout");
        public static readonly VanillaBuffPropertyMeta<FrameTimer> PROP_DELAY_TIMEOUT = new VanillaBuffPropertyMeta<FrameTimer>("delay_timeout");
        public static readonly VanillaBuffPropertyMeta<bool> PROP_GLITCHED = new VanillaBuffPropertyMeta<bool>("glitched", true);
        public static readonly VanillaBuffPropertyMeta<Vector3> PROP_SCALE = new VanillaBuffPropertyMeta<Vector3>("scale", Vector3.one);
    }
}
