#nullable enable // autogenerated

using System;
using System.Collections.Generic;
using System.Linq;
using PVZEngine.Modifiers;

namespace PVZEngine.Level
{
    public partial class LevelEngine : IModifierSource, IModifierProvider
    {
        private void ReevaluateModifierCaches()
        {
            modifierLibrary.ClearModifierCaches();
            modifierLibrary.AddModifierCaches(AreaDefinition.GetModifiers().Select(m => new ModifierSourceItem(this, m)));
            modifierLibrary.AddModifierCaches(StageDefinition.GetModifiers().Select(m => new ModifierSourceItem(this, m)));
        }
        private void OnModifiedPropertyNeedsUpdateCallback(IPropertyKey name)
        {
            OnModifiedPropertyNeedsUpdate?.Invoke(name);
        }
        T? IModifierSource.GetProperty<T>(PropertyKey<T> name) where T : default
        {
            return GetProperty<T>(name);
        }

        IEnumerable<IPropertyKey> IModifierProvider.GetModifiedProperties()
        {
            return modifierLibrary.GetModifyPropertyKeys();
        }

        void IModifierProvider.GetModifiersForProperty(IPropertyKey name, List<ModifierSourceItem> results)
        {
            modifierLibrary.GetModifierItemsForProperty(name, results);
        }

        public event Action<IPropertyKey>? OnModifiedPropertyNeedsUpdate;
        private ModifierLibrary modifierLibrary;
    }
}