#nullable enable // autogenerated

using System.Collections.Generic;
using PVZEngine.Collisions;
using PVZEngine.Collisions.Level;
using PVZEngine.Entities;
using UnityEngine;

namespace PVZEngine.Level
{
    public partial class LevelEngine
    {
        #region 碰撞检测
        private void InitEntityCollision(Entity entity)
        {
            collisionSystem.InitEntity(entity);
        }
        private void RemoveEntityCollision(Entity entity)
        {
            collisionSystem.DestroyEntity(entity);
        }
        public void UpdateEntityCollisionDetection(Entity entity)
        {
            collisionSystem.UpdateEntityDetection(entity);
        }
        public void UpdateEntityCollisionPosition(Entity entity)
        {
            collisionSystem.UpdateEntityPosition(entity);
        }
        public void UpdateEntityCollisionSize(Entity entity)
        {
            collisionSystem.UpdateEntitySize(entity);
        }
        public IEntityCollider[] OverlapBox(Vector3 center, Vector3 size, OverlapParams param)
        {
            return collisionSystem.OverlapBox(center, size, param);
        }
        public void OverlapBoxNonAlloc(Vector3 center, Vector3 size, OverlapParams param, List<IEntityCollider> results)
        {
            collisionSystem.OverlapBoxNonAlloc(center, size, param, results);
        }
        public IEntityCollider[] OverlapSphere(Vector3 center, float radius, OverlapParams param)
        {
            return collisionSystem.OverlapSphere(center, radius, param);
        }
        public void OverlapSphereNonAlloc(Vector3 center, float radius, OverlapParams param, List<IEntityCollider> results)
        {
            collisionSystem.OverlapSphereNonAlloc(center, radius, param, results);
        }
        public IEntityCollider[] OverlapCapsule(Vector3 point0, Vector3 point1, float radius, OverlapParams param)
        {
            return collisionSystem.OverlapCapsule(point0, point1, radius, param);
        }
        public void OverlapCapsuleNonAlloc(Vector3 point0, Vector3 point1, float radius, OverlapParams param, List<IEntityCollider> results)
        {
            collisionSystem.OverlapCapsuleNonAlloc(point0, point1, radius, param, results);
        }
        public IEntityCollider? AddEntityCollider(Entity entity, ColliderConstructor info)
        {
            return collisionSystem.CreateCustomCollider(entity, info);
        }
        public bool RemoveEntityCollider(Entity entity, string name)
        {
            return collisionSystem.RemoveCollider(entity, name);
        }
        public IEntityCollider? GetEntityCollider(Entity entity, string name)
        {
            return collisionSystem.GetCollider(entity, name);
        }
        public void GetEntityCurrentCollisions(Entity entity, List<EntityCollision> collisions)
        {
            collisionSystem.GetCurrentCollisions(entity, collisions);
        }
        #endregion

        #region 碰撞
        private void CollisionUpdate()
        {
            collisionSystem.Update();
        }
        #endregion

        #region 序列化
        private void WriteCollisionToSerializable(SerializableLevel seri)
        {
            seri.collisionSystem = collisionSystem.ToSerializable();
        }
        private void ReadCollisionFromSerializable(SerializableLevel seri)
        {
            if (seri.collisionSystem != null)
                collisionSystem.LoadFromSerializable(this, seri.collisionSystem);
        }
        #endregion

        private ICollisionSystem collisionSystem;
    }
}