#nullable enable // autogenerated

using System.Collections.Generic;
using PVZEngine.Entities;
using PVZEngine.Modifiers;

namespace PVZEngine.Level
{
    public abstract class StageBehaviour
    {
        public StageBehaviour(StageDefinition stageDef)
        {
        }
        public virtual void Setup(LevelEngine level) { }
        public virtual void Start(LevelEngine level) { }
        public virtual void Update(LevelEngine level) { }
        public virtual void PrepareForBattle(LevelEngine level) { }
        public virtual void PostWave(LevelEngine level, int wave) { }
        public virtual void PostHugeWaveEvent(LevelEngine level) { }
        public virtual void PostFinalWaveEvent(LevelEngine level) { }
        public virtual void PostEnemySpawned(Entity entity) { }
        public bool LevelHasBehaviour<T>(LevelEngine level) where T : StageBehaviour
        {
            return level.StageDefinition.HasBehaviour<T>();
        }
        public PropertyModifier[] GetModifiers()
        {
            return modifiers.ToArray();
        }
        protected void AddModifier(PropertyModifier modifier)
        {
            modifiers.Add(modifier);
        }
        private List<PropertyModifier> modifiers = new List<PropertyModifier>();
    }
}
