#nullable enable // autogenerated

using MVZ2.GameContent.Bosses;
using MVZ2.GameContent.Effects;
using MVZ2.GameContent.ProgressBars;
using MVZ2.Vanilla.Audios;
using MVZ2.Vanilla.Bosses;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Level;
using MVZ2.Vanilla.Properties;
using MVZ2Logic.Level;
using PVZEngine.Buffs;
using PVZEngine.Entities;
using PVZEngine.Level;
using UnityEngine;

namespace MVZ2.GameContent.Buffs.Level
{
    [BuffDefinition(VanillaBuffNames.Level.crescentTransition)]
    public class CrescentTransitionBuff : BuffDefinition
    {
        public CrescentTransitionBuff(string nsp, string name) : base(nsp, name)
        {
        }
        public override void PostAdd(Buff buff)
        {
            base.PostAdd(buff);
            buff.SetProperty(PROP_TIMEOUT, MAX_TIMEOUT);
        }
        public override void PostUpdate(Buff buff)
        {
            base.PostUpdate(buff);

            var timeout = buff.GetProperty<int>(PROP_TIMEOUT);
            timeout--;
            buff.SetProperty(PROP_TIMEOUT, timeout);

            var level = buff.Level;
            if (timeout > CREATE_DARKNESS_TIMEOUT)
            {
                // 让眼睛闭眼。
                foreach (var eye in level.FindEntities(VanillaEffectID.nightmareWatchingEye))
                {
                    if (eye.Timeout <= 0)
                    {
                        eye.Timeout = 30;
                    }
                }
                // 音乐放缓。
                level.SetMusicVolume(Mathf.Clamp01(level.GetMusicVolume() - (1 / 30f)));
            }
            if (timeout == CREATE_DARKNESS_TIMEOUT || timeout == SPLASH_TIMEOUT_0 || timeout == SPLASH_TIMEOUT_1 || timeout == SPLASH_TIMEOUT_2
             || timeout == SPLASH_TIMEOUT_3 || timeout == SPLASH_TIMEOUT_4)
            {
                level.PlaySound(VanillaSoundID.thump);
                level.ShakeScreen(10, 0, 10);
                Vector3 pos = new Vector3(level.GetEntityColumnX(4), 0, level.GetEntityLaneZ(2));
                level.Spawn(VanillaEffectID.splashParticles, pos, null)?.Let(e =>
                {
                    e.SetDisplayScale(Vector3.one * 3);
                    e.SetTint(level.GetWaterColor());
                });
                level.PlaySound(VanillaSoundID.splash);
            }
            else if (timeout <= 0)
            {
                // 音乐。
                level.PlayMusic(VanillaMusicID.junkoThemeArchived);
                level.SetMusicVolume(1);

                Vector3 pos = new Vector3(level.GetEntityColumnX(4), 0, level.GetEntityLaneZ(2));
                level.Spawn(VanillaBossID.crescent, pos, null)?.Let(e =>
                {
                    e.Velocity = Vector3.up * 30;
                    e.PlaySound(VanillaSoundID.splashBig);
                    e.Spawn(VanillaEffectID.nightmareaperSplash, pos);
                    e.ApplyBuffForBossRevenge();
                    Crescent.Appear(e);
                });

                level.SetProgressBarToBoss(VanillaProgressBarID.nightmare);

                buff.Remove();
            }
        }
        public static readonly VanillaBuffPropertyMeta<int> PROP_TIMEOUT = new VanillaBuffPropertyMeta<int>("Timeout");
        public const int MAX_TIMEOUT = CREATE_DARKNESS_TIMEOUT + 60;
        public const int SPLASH_TIMEOUT_0 = FADEOUT_TIMEOUT;
        public const int SPLASH_TIMEOUT_1 = FADEOUT_TIMEOUT + 5;
        public const int SPLASH_TIMEOUT_2 = FADEOUT_TIMEOUT + 30;
        public const int SPLASH_TIMEOUT_3 = FADEOUT_TIMEOUT + 45;
        public const int SPLASH_TIMEOUT_4 = FADEOUT_TIMEOUT + 90;
        public const int CREATE_DARKNESS_TIMEOUT = FADEOUT_TIMEOUT + 150;
        public const int FADEOUT_TIMEOUT = 0;
    }
}