#nullable enable // autogenerated

using MVZ2.GameContent.Buffs.Enemies;
using MVZ2.Vanilla.Enemies;
using MVZ2.Vanilla.Entities;
using PVZEngine.Entities;
using PVZEngine.Level;

namespace MVZ2.GameContent.Enemies
{
    [EntityBehaviourDefinition(VanillaEntityBehaviourNames.flyingPirate_Move)]
    public class FlyingPirate_MoveBehaviour : AIEntityBehaviour
    {
        public FlyingPirate_MoveBehaviour(string nsp, string name) : base(nsp, name)
        {
        }
        protected override void UpdateAI(Entity entity)
        {
            base.UpdateAI(entity);
            if (entity.State == STATE_WALK || FlyingPirateGlideBuff.IsParachuting(entity))
            {
                entity.UpdateWalkVelocity();
            }
        }
        public const int STATE_WALK = VanillaEnemyStates.WALK;
        public const int STATE_RANGED_ATTACK = VanillaEnemyStates.RANGED_ATTACK;
    }
}
