#nullable enable // autogenerated

using MVZ2.GameContent.Buffs.Enemies;
using MVZ2.GameContent.Entities;
using MVZ2.Vanilla.Enemies;
using MVZ2.Vanilla.Entities;
using MVZ2Logic.Entities;
using PVZEngine.Definitions;
using PVZEngine.Entities;

namespace MVZ2.GameContent.Enemies
{
    [AutoEntityBehaviourDefinition(VanillaEntityBehaviourNames.flyingPirate_Move)]
    public class FlyingPirate_MoveBehaviour : AIEntityBehaviour
    {
        public FlyingPirate_MoveBehaviour(string nsp, string name) : base(nsp, name)
        {
        }
        protected override void UpdateAI(Entity entity)
        {
            base.UpdateAI(entity);
            if (entity.State == STATE_WALK || FlyingPirateGlideBuff.IsParachuting(entity))
            {
                entity.UpdateWalkVelocity();
            }
        }
        public const int STATE_WALK = LogicEnemyStates.WALK;
    }
}
