#nullable enable // autogenerated

using MVZ2.GameContent.Buffs.Enemies;
using MVZ2.Vanilla.Entities;
using PVZEngine.Definitions;
using PVZEngine.Entities;

namespace MVZ2.GameContent.Enemies
{
    [AutoEntityBehaviourDefinition(VanillaEntityBehaviourNames.flyingPirate_Animation)]
    public class FlyingPirate_AnimationBehaviour : HumanoidAnimationBehaviour
    {
        public FlyingPirate_AnimationBehaviour(string nsp, string name) : base(nsp, name)
        {
        }
        protected override void ModifyAnimationParameters(Entity entity, int state, ref AnimationParameters parameters)
        {
            base.ModifyAnimationParameters(entity, state, ref parameters);
            if (FlyingPirateGlideBuff.IsParachuting(entity))
            {
                parameters.armState = ARM_STATE_HANDS_UP;
            }
        }
    }
}