#nullable enable // autogenerated

using MVZ2.Vanilla.Enemies;
using MVZ2.Vanilla.Entities;
using PVZEngine.Definitions;
using PVZEngine.Entities;

namespace MVZ2.GameContent.Enemies
{
    [AutoEntityBehaviourDefinition(VanillaEntityBehaviourNames.graveWarden_Animation)]
    public class GraveWarden_AnimationBehaviour : HumanoidAnimationBehaviour
    {
        public GraveWarden_AnimationBehaviour(string nsp, string name) : base(nsp, name)
        {
        }
        protected override void ModifyAnimationParameters(Entity entity, int state, ref AnimationParameters parameters)
        {
            base.ModifyAnimationParameters(entity, state, ref parameters);
            if (state == STATE_PLACE)
            {
                parameters.walkState = WALK_STATE_NONE;
                parameters.armState = ARM_STATE_SPECIAL_1;
            }
        }
        public const int STATE_PLACE = VanillaEnemyStates.GRAVE_WARDEN_PLACE;
    }
}