#nullable enable // autogenerated

using MVZ2.Vanilla.Enemies;
using MVZ2.Vanilla.Entities;
using PVZEngine.Definitions;
using PVZEngine.Entities;

namespace MVZ2.GameContent.Enemies
{
    [AutoEntityBehaviourDefinition(VanillaEntityBehaviourNames.skelebomb_Animation)]
    public class Skelebomb_AnimationBehaviour : HumanoidAnimationBehaviour
    {
        public Skelebomb_AnimationBehaviour(string nsp, string name) : base(nsp, name)
        {
        }
        protected override void ModifyAnimationParameters(Entity entity, int state, ref AnimationParameters parameters)
        {
            base.ModifyAnimationParameters(entity, state, ref parameters);
            if (state == STATE_PRE_EXPLODE)
            {
                parameters.walkState = WALK_STATE_NONE;
                parameters.armState = ARM_STATE_NONE;
                parameters.specialState = SPECIAL_STATE_PRE_EXPLODE;
            }
        }
        public const int STATE_PRE_EXPLODE = VanillaEnemyStates.SKELEBOMB_PRE_EXPLODE;
        public const int SPECIAL_STATE_PRE_EXPLODE = 1;
    }
}