#nullable enable // autogenerated

using System.Linq;
using MVZ2.Vanilla.Level;
using PVZEngine.Definitions;
using PVZEngine.Level;

namespace MVZ2.GameContent.Stages
{
    public class BlueprintCrisisBehaviour : StageBehaviour
    {
        public BlueprintCrisisBehaviour(StageDefinition stageDef) : base(stageDef)
        {
        }
        public override void Start(LevelEngine level)
        {
            var blueprintSet = level.GetBlueprintSet();
            if (!level.NeedBlueprints() && blueprintSet != null)
            {
                level.SetSeedSlotCount(blueprintSet.Count());
                level.FillSeedPacks(blueprintSet);
            }
        }
    }
}
