#nullable enable // autogenerated

using MVZ2.GameContent.Buffs.Contraptions;
using MVZ2.GameContent.Damages;
using MVZ2.GameContent.Effects;
using MVZ2.Vanilla.Audios;
using MVZ2.Vanilla.Entities;
using PVZEngine.Buffs;
using PVZEngine.Damages;
using PVZEngine.Entities;
using PVZEngine.Level;
using UnityEngine;

namespace MVZ2.GameContent.Projectiles
{
    [EntityBehaviourDefinition(VanillaProjectileNames.antigravityDevice)]
    public class AntigravityDevice : ProjectileBehaviour
    {
        public AntigravityDevice(string nsp, string name) : base(nsp, name)
        {
        }
        public override void PostDeath(Entity entity, DeathInfo damageInfo)
        {
            base.PostDeath(entity, damageInfo);
            if (damageInfo.HasEffect(VanillaDamageEffects.NO_DEATH_TRIGGER))
                return;
            var pos = entity.GetCenter();
            entity.PlaySound(VanillaSoundID.nimbleFabric);
            entity.Spawn(VanillaEffectID.smokeCluster, pos);
            foreach (var collider in entity.Level.OverlapBox(pos, Vector3.one * 60, entity.GetFaction(), EntityCollisionHelper.MASK_PLANT | EntityCollisionHelper.MASK_ENEMY, 0))
            {
                collider.Entity.AddBuff<CrescentAntiGravityBuff>();
            }
        }
    }
}
