#nullable enable // autogenerated

using MVZ2.GameContent.Damages;
using MVZ2.GameContent.Effects;
using MVZ2.Vanilla.Audios;
using MVZ2.Vanilla.Entities;
using PVZEngine.Damages;
using PVZEngine.Entities;
using PVZEngine.Level;
using UnityEngine;

namespace MVZ2.GameContent.Projectiles
{
    [EntityBehaviourDefinition(VanillaProjectileNames.deliciousTroll)]
    public class DeliciousTroll : ProjectileBehaviour
    {
        public DeliciousTroll(string nsp, string name) : base(nsp, name)
        {
        }
        public override void Init(Entity entity)
        {
            base.Init(entity);
            entity.CollisionMaskHostile = 0;
            entity.CollisionMaskFriendly = 0;
        }
        public override void PostDeath(Entity entity, DeathInfo damageInfo)
        {
            base.PostDeath(entity, damageInfo);
            if (damageInfo.HasEffect(VanillaDamageEffects.NO_DEATH_TRIGGER))
                return;
            entity.PlaySound(VanillaSoundID.glassBreak);
            entity.PlaySound(VanillaSoundID.smallExplosion);
            entity.PlaySound(VanillaSoundID.poisonCast);
            var lane = entity.GetLane();
            var x = entity.Level.GetColumnX(4);
            var y = entity.GetGroundY();
            var z = entity.Level.GetEntityLaneZ(lane);
            entity.SpawnWithParams(VanillaEffectID.concealingSmoke, new Vector3(x, y, z));
        }
    }
}
