#nullable enable // autogenerated

using MVZ2.GameContent.Enemies;
using MVZ2.Vanilla.Audios;
using MVZ2.Vanilla.Entities;
using MVZ2Logic.Entities;
using PVZEngine.Definitions;
using PVZEngine.Entities;
using UnityEngine;

namespace MVZ2.GameContent.Projectiles
{
    [AutoEntityBehaviourDefinition(VanillaProjectileNames.terrorCocoon)]
    public class TerrorCocoon : EntityBehaviourDefinition
    {
        public TerrorCocoon(string nsp, string name) : base(nsp, name)
        {
        }
        public override void Init(Entity entity)
        {
            base.Init(entity);
            entity.CollisionMaskHostile = 0;
            entity.CollisionMaskFriendly = 0;
        }
        public override void Update(Entity projectile)
        {
            base.Update(projectile);
            if (projectile.GetRelativeY() <= 0)
            {
                projectile.PlaySound(VanillaSoundID.splat);
                projectile.SpawnWithParams(VanillaEnemyID.parasiteTerror, projectile.Position)?.Let(e =>
                {
                    e.Velocity += Vector3.up * 10;
                });
                projectile.Remove();
            }
        }
    }
}
