#nullable enable // autogenerated

using MVZ2.Vanilla.Enemies;
using MVZ2.Vanilla.Entities;
using PVZEngine.Entities;
using PVZEngine.Level;

namespace MVZ2.GameContent.Enemies
{
    [EntityBehaviourDefinition(VanillaEntityBehaviourNames.jackDullahan_State)]
    public class JackDullahan_StateBehaviour : EnemyStateBehaviour
    {
        public JackDullahan_StateBehaviour(string nsp, string name) : base(nsp, name)
        {
        }
        protected override int GetActiveState(Entity enemy)
        {
            var baseState = base.GetActiveState(enemy);
            if (baseState == STATE_WALK)
            {
                var horse = enemy.GetRidingEntity();
                var hasHorse = horse.ExistsAndAlive();
                if (hasHorse)
                {
                    return STATE_IDLE;
                }
                else
                {
                    return STATE_SPECIAL_MOVE;
                }
            }
            return baseState;
        }
    }
}
