#nullable enable // autogenerated

using MVZ2.Vanilla.Entities;
using MVZ2Logic.Contents.Enemies;
using PVZEngine.Definitions;
using PVZEngine.Entities;

namespace MVZ2.GameContent.Enemies
{
    [AutoEntityBehaviourDefinition(VanillaEntityBehaviourNames.jackDullahan_State)]
    public class JackDullahan_StateBehaviour : EnemyStateBehaviour
    {
        public JackDullahan_StateBehaviour(string nsp, string name) : base(nsp, name)
        {
        }
        protected override int GetActiveState(Entity enemy)
        {
            var baseState = base.GetActiveState(enemy);
            if (baseState == STATE_WALK)
            {
                var horse = enemy.GetRidingEntity();
                var hasHorse = horse.ExistsAndAlive();
                if (hasHorse)
                {
                    return STATE_IDLE;
                }
                else
                {
                    return JackDullahan.STATE_SWING;
                }
            }
            return baseState;
        }
    }
}
