#nullable enable // autogenerated

using MVZ2.Vanilla.Enemies;
using MVZ2.Vanilla.Entities;
using PVZEngine.Definitions;
using PVZEngine.Entities;

namespace MVZ2.GameContent.Enemies
{
    [AutoEntityBehaviourDefinition(VanillaEntityBehaviourNames.skelebomb_State)]
    public class Skelebomb_StateBehaviour : EnemyStateBehaviour
    {
        public Skelebomb_StateBehaviour(string nsp, string name) : base(nsp, name)
        {
        }
        protected override int GetActiveState(Entity enemy)
        {
            if (enemy.IsPerformingSpecialMove())
            {
                return STATE_PRE_EXPLODE;
            }
            return base.GetActiveState(enemy);
        }
        public const int STATE_PRE_EXPLODE = VanillaEnemyStates.SKELEBOMB_PRE_EXPLODE;
    }
}
