#nullable enable // autogenerated

using MVZ2.Vanilla.Entities;
using PVZEngine;
using PVZEngine.Definitions;
using PVZEngine.Entities;

namespace MVZ2.GameContent.Enemies
{
    [AutoEntityBehaviourDefinition(VanillaEntityBehaviourNames.zombieSpectre_State)]
    public class ZombieSpectre_StateBehaviour : EnemyStateBehaviour
    {
        public ZombieSpectre_StateBehaviour(string nsp, string name) : base(nsp, name)
        {
        }
        protected override int GetActiveState(Entity enemy)
        {
            if (ZombieSpectre.IsAppearing(enemy))
            {
                return ZombieSpectre.STATE_APPEAR;
            }
            return base.GetActiveState(enemy);
        }
    }
}
