#nullable enable // autogenerated

using MVZ2Logic.Level;
using PVZEngine.Buffs;
using PVZEngine.Definitions;
using PVZEngine.Modifiers;

namespace MVZ2.GameContent.Buffs.Level
{
    [AutoBuffDefinition(VanillaBuffNames.Level.create)]
    public class CreateBuff : BuffDefinition
    {
        public CreateBuff(string nsp, string name) : base(nsp, name)
        {
            AddModifier(new BooleanModifier(LogicLevelProps.STARSHARD_RECHARGES_BLUEPRINT, true));
        }
    }
}
