#nullable enable // autogenerated

using System.Linq;
using MVZ2.GameContent.Buffs;
using MVZ2.GameContent.Damages;
using MVZ2.GameContent.Pickups;
using MVZ2.Vanilla.Audios;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Pickups;
using MVZ2.Vanilla.Properties;
using MVZ2Logic.Blueprints;
using MVZ2Logic.Entities;
using PVZEngine.Buffs;
using PVZEngine.Callbacks;
using PVZEngine.Definitions;
using PVZEngine.Entities;
using PVZEngine.Modifiers;
using UnityEngine;

namespace MVZ2.GameContent.Contraptions
{
    [AutoEntityBehaviourDefinition(VanillaContraptionNames.respawnAnchor)]
    public class RespawnAnchor : ContraptionBehaviour
    {
        public RespawnAnchor(string nsp, string name) : base(nsp, name)
        {
            AddModifier(new BooleanModifier(LogicEntityProps.IS_LIGHT_SOURCE, PROP_WORKING));
            AddModifier(new Vector3Modifier(LogicEntityProps.LIGHT_RANGE, NumberOperator.Multiply, PROP_LIGHT_RANGE_MULTIPLIER));
            AddTrigger(LevelCallbacks.POST_ENTITY_DEATH, PostContraptionDestroyCallback, filter: EntityTypes.PLANT);
        }
        private void PostContraptionDestroyCallback(LevelCallbacks.EntityDeathParams param, CallbackResult result)
        {
            var entity = param.entity;
            var info = param.deathInfo;
            if (entity.Definition.HasBehaviour(this))
                return;
            if (info.HasEffect(VanillaDamageEffects.PICKAXE) || !entity.ShouldTriggerDeathEffects(info))
                return;
            var anchors = entity.Level.FindEntities(e => e.Definition.HasBehaviour(this) && IsWorking(e));
            var anchor = anchors.FirstOrDefault();
            if (anchor == null || anchor.IsHostileEntity())
                return;
            var spawnParams = anchor.GetSpawnParams();
            spawnParams.SetProperty(VanillaPickupProps.CONTENT_ID, LogicBlueprintID.FromEntity(entity.GetDefinitionID()));
            spawnParams.SetProperty(BlueprintPickup.PROP_COMMAND_BLOCK, entity.HasBuff(VanillaBuffID.Contraption.imitated));
            anchor.Produce(VanillaPickupID.blueprintPickup, spawnParams);

            var charge = GetCharges(anchor);
            charge--;
            SetCharges(anchor, charge);
            anchor.PlaySound(VanillaSoundID.respawnAnchorDeplete);
        }
        protected override void UpdateLogic(Entity entity)
        {
            base.UpdateLogic(entity);
            SetWorking(entity, GetCharges(entity) > 0);
            SetLightRangeMultiplier(entity, Vector3.one * (GetCharges(entity) / (float)MAX_CHARGES));
            entity.SetModelProperty("ChargeIndex", GetCharges(entity) - 1);
            entity.SetAnimationBool("Working", IsWorking(entity));
        }
        protected override void OnEvoke(Entity entity)
        {
            base.OnEvoke(entity);
            entity.PlaySound(VanillaSoundID.respawnAnchorCharge);
            entity.HealEffects(entity.GetMaxHealth(), entity);
            SetCharges(entity, MAX_CHARGES);
        }
        public const int MAX_CHARGES = 4;
        public static bool IsWorking(Entity entity) => entity.GetProperty<bool>(PROP_WORKING);
        public static void SetWorking(Entity entity, bool value) => entity.SetProperty(PROP_WORKING, value);
        public static int GetCharges(Entity entity) => entity.GetProperty<int>(PROP_CHARGES);
        public static void SetCharges(Entity entity, int value) => entity.SetProperty(PROP_CHARGES, value);
        public static Vector3 GetLightRangeMultiplier(Entity entity) => entity.GetProperty<Vector3>(PROP_LIGHT_RANGE_MULTIPLIER);
        public static void SetLightRangeMultiplier(Entity entity, Vector3 value) => entity.SetProperty(PROP_LIGHT_RANGE_MULTIPLIER, value);
        public static readonly VanillaEntityPropertyMeta<bool> PROP_WORKING = new VanillaEntityPropertyMeta<bool>("working");
        public static readonly VanillaEntityPropertyMeta<int> PROP_CHARGES = new VanillaEntityPropertyMeta<int>("charges", 4);
        public static readonly VanillaEntityPropertyMeta<Vector3> PROP_LIGHT_RANGE_MULTIPLIER = new VanillaEntityPropertyMeta<Vector3>("light_range_multiplier", Vector3.one);
    }
}
