#nullable enable // autogenerated

using MVZ2.GameContent.Damages;
using MVZ2.GameContent.Entities;
using MVZ2.Vanilla.Entities;
using MVZ2Logic.Entities;
using MVZ2Logic.Grids;
using PVZEngine;
using PVZEngine.Damages;
using PVZEngine.Definitions;
using PVZEngine.Entities;

namespace MVZ2.GameContent.Contraptions
{
    [AutoEntityBehaviourDefinition(VanillaEntityBehaviourNames.spawnUpgradeFromEntity)]
    public class SpawnUpgradeFromEntityBehaviour : AIEntityBehaviour, IDeathEffectsBehaviour
    {
        public SpawnUpgradeFromEntityBehaviour(string nsp, string name) : base(nsp, name)
        {
        }
        public void DeathEffects(Entity entity, DeathInfo info)
        {
            if (info.HasEffect(VanillaDamageEffects.PICKAXE))
                return;
            foreach (var grid in entity.GetGridsToTake())
            {
                if (grid == null)
                    continue;
                var upgradeFromEntity = entity.Level.Content.GetEntityDefinition(entity.GetDefinitionID())?.GetUpgradeFromEntity();
                if (upgradeFromEntity == null)
                    continue;
                if (!grid.CanSpawnEntity(upgradeFromEntity))
                    continue;
                entity.SpawnWithParams(upgradeFromEntity, grid.GetEntityPosition());
            }
        }
    }
}
