#nullable enable // autogenerated

using System;
using PVZEngine.Level;
using Tools;
using UnityEngine;

namespace PVZEngine.Entities
{
    public sealed partial class Entity : IModifiablePropertyTarget
    {
        #region 属性
        public T? GetProperty<T>(PropertyKey<T> name, bool ignoreBuffs = false)
        {
            return properties.GetProperty<T>(name, ignoreBuffs);
        }
        public void SetProperty<T>(PropertyKey<T> name, T? value)
        {
            properties.SetProperty(name, value);
        }
        public void SetPropertyObject(IPropertyKey name, object? value)
        {
            properties.SetPropertyObject(name, value);
        }
        private void UpdateAllModifiedProperties(bool triggersEvaluation)
        {
            properties.UpdateAllModifiedProperties(triggersEvaluation);
        }
        #endregion

        #region 接口实现
        bool IModifiablePropertyTarget.GetFallbackProperty(IPropertyKey name, out object? value)
        {
            if (Definition == null)
            {
                value = default;
                return false;
            }
            if (Definition.TryGetPropertyObject(name, out var defProp))
            {
                value = defProp;
                return true;
            }

            var behaviourCount = Definition.GetBehaviourCount();
            for (int i = 0; i < behaviourCount; i++)
            {
                var behaviour = Definition.GetBehaviourAt(i);
                if (behaviour.TryGetPropertyObject(name, out var behProp))
                {
                    value = behProp;
                    return true;
                }
            }
            value = default;
            return false;
        }
        void IModifiablePropertyTarget.OnPropertyChanged(IPropertyKey name, object? beforeValue, object? afterValue, bool triggersEvaluation)
        {
            if (triggersEvaluation)
            {
                if (name == ((PropertyKey<float>)EngineEntityProps.MAX_HEALTH))
                {
                    var before = beforeValue.ToGeneric<float>();
                    var after = afterValue.ToGeneric<float>();
                    Health = Mathf.Min(after, Health * (after / before));
                }
            }
            Cache.UpdateProperty(this, name, beforeValue, afterValue);
            PostPropertyChanged?.Invoke(name, beforeValue, afterValue);
            modifierLibrary.CallPropertyChanged(this, name);
        }
        #endregion

        #region 序列化
        private void LoadPropertiesFromSerializable(SerializableEntity seri)
        {
            properties.LoadFromSerializable(seri.properties);
        }
        #endregion

        #region 事件
        public event Action<IPropertyKey, object?, object?>? PostPropertyChanged;
        #endregion

        #region 属性字段
        private PropertyBlock properties;
        #endregion
    }
}