#nullable enable // autogenerated

using System;
using PVZEngine.Level;

namespace PVZEngine.Entities
{
    public class EntitySourceReference : ILevelSourceReference
    {
        private EntitySourceReference(long id, NamespaceID defID, ILevelSourceReference? parent, int faction)
        {
            this.id = id;
            this.definitionID = defID;
            this.parent = parent;
            this.faction = faction;
        }
        public EntitySourceReference(Entity entity) : this(entity.ID, entity.Definition.GetID(), entity.SpawnerReference?.Clone(), entity.Cache.Faction)
        {
        }
        public EntitySourceReference(LevelEngine level, SerializableEntitySourceReference seri)
        {
            this.id = seri.id;
            this.definitionID = seri.definitionID;
            this.parent = seri.parent?.ToDeserialized(level);
            this.faction = seri.faction;
        }
        public EntitySourceReference Clone()
        {
            return new EntitySourceReference(ID, DefinitionID, parent?.Clone(), faction);
        }
        public Entity? GetEntity(LevelEngine game)
        {
            return game.FindEntityByID(ID);
        }
        public override bool Equals(object obj)
        {
            if (obj is EntitySourceReference entityRef)
            {
                return ID == entityRef.ID;
            }
            return base.Equals(obj);
        }
        public override int GetHashCode()
        {
            return ID.GetHashCode();
        }
        public static bool operator ==(EntitySourceReference lhs, EntitySourceReference rhs)
        {
            if (lhs is null)
                return rhs is null;
            return lhs.Equals(rhs);
        }
        public static bool operator !=(EntitySourceReference lhs, EntitySourceReference rhs)
        {
            return !(lhs == rhs);
        }
        ILevelSourceReference ILevelSourceReference.Clone()
        {
            return Clone();
        }
        ILevelSourceTarget? ILevelSourceReference.GetTarget(LevelEngine level)
        {
            return GetEntity(level);
        }
        public ISerializableSourceReference ToSerializable()
        {
            return new SerializableEntitySourceReference(this);
        }
        public ILevelSourceReference? SpawnerReference => parent;
        public int Faction => faction;
        public NamespaceID DefinitionID => definitionID;
        public long ID => id;
        ILevelSourceReference? ILevelSourceReference.Parent => parent;
        private NamespaceID definitionID;
        private ILevelSourceReference? parent;
        private int faction = -1;
        private long id;

    }
    [Serializable]
    public class SerializableEntitySourceReference : ISerializableSourceReference
    {
        public NamespaceID definitionID;
        public ISerializableSourceReference? parent;
        public int faction = -1;
        public long id;

        public SerializableEntitySourceReference(EntitySourceReference reference)
        {
            definitionID = reference.DefinitionID;
            parent = reference.SpawnerReference?.ToSerializable();
            faction = reference.Faction;
            id = reference.ID;
        }
        public ILevelSourceReference ToDeserialized(LevelEngine level)
        {
            return new EntitySourceReference(level, this);
        }
    }
}