#nullable enable // autogenerated

using System;
using PVZEngine.Entities;
using PVZEngine.Level;

namespace PVZEngine.Grids
{
    public class GridSourceReference : ILevelSourceReference
    {
        private GridSourceReference(int index, NamespaceID defID)
        {
            this.index = index;
            definitionID = defID;
        }
        public GridSourceReference(LawnGrid grid)
        {
            index = grid.GetIndex();
            definitionID = grid.Definition.GetID();
        }
        public GridSourceReference(LevelEngine level, SerializableGridSourceReference seri)
        {
            this.index = seri.index;
            this.definitionID = seri.definitionID;
        }
        public GridSourceReference Clone()
        {
            return new GridSourceReference(index, definitionID);
        }
        public Entity? GetEntity(LevelEngine game) => null;
        public override bool Equals(object obj)
        {
            if (obj is GridSourceReference entityRef)
            {
                return ID == entityRef.ID;
            }
            return base.Equals(obj);
        }
        public override int GetHashCode()
        {
            return ID.GetHashCode();
        }
        public static bool operator ==(GridSourceReference lhs, GridSourceReference rhs)
        {
            if (lhs is null)
                return rhs is null;
            return lhs.Equals(rhs);
        }
        public static bool operator !=(GridSourceReference lhs, GridSourceReference rhs)
        {
            return !(lhs == rhs);
        }
        ILevelSourceReference ILevelSourceReference.Clone()
        {
            return Clone();
        }
        ILevelSourceTarget? ILevelSourceReference.GetTarget(LevelEngine level)
        {
            return level.GetGrid(index);
        }
        public ISerializableSourceReference ToSerializable()
        {
            return new SerializableGridSourceReference(this);
        }
        public int Faction => 0;
        public NamespaceID DefinitionID => definitionID;
        public long ID => index;
        ILevelSourceReference? ILevelSourceReference.Parent => null;
        private NamespaceID definitionID;
        private int index;
    }
    [Serializable]
    public class SerializableGridSourceReference : ISerializableSourceReference
    {
        public NamespaceID definitionID;
        public int index;

        public SerializableGridSourceReference(GridSourceReference reference)
        {
            definitionID = reference.DefinitionID;
            index = (int)reference.ID;
        }
        public ILevelSourceReference ToDeserialized(LevelEngine level)
        {
            return new GridSourceReference(level, this);
        }
    }
}