#nullable enable // autogenerated

using System;
using PVZEngine.Entities;

namespace PVZEngine.Level
{
    public class SpawnParams
    {
        public void SetProperty<T>(PropertyKey<T> key, T? value)
        {
            properties.SetProperty(key, value);
        }
        public void Apply(Entity entity)
        {
            if (EntityParent != null)
            {
                entity.SetParent(EntityParent);
            }
            foreach (var property in properties.GetPropertyNames())
            {
                entity.SetPropertyObject(property, properties.GetPropertyObject(property));
            }
            OnApply?.Invoke(entity);
        }
        public event Action<Entity>? OnApply;
        public Entity? EntityParent { get; set; }
        private PropertyDictionary properties = new PropertyDictionary();
    }
}
