#nullable enable // autogenerated

using MVZ2.GameContent.Damages;
using MVZ2.GameContent.Enemies;
using MVZ2.GameContent.Models;
using MVZ2.Vanilla.Audios;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Models;
using MVZ2.Vanilla.Properties;
using MVZ2Logic.Models;
using PVZEngine.Buffs;
using PVZEngine.Callbacks;
using PVZEngine.Entities;
using PVZEngine.Level;

namespace MVZ2.GameContent.Buffs.Contraptions
{
    [BuffDefinition(VanillaBuffNames.Contraption.abyss)]
    public class AbyssBuff : BuffDefinition
    {
        public AbyssBuff(string nsp, string name) : base(nsp, name)
        {
            AddModelInsertion(LogicModelHelper.ANCHOR_CENTER, VanillaModelKeys.curseOfTheAbyss, VanillaModelID.curseOfTheAbyss);
            AddTrigger(LevelCallbacks.POST_ENTITY_DEATH, PostEntityDeathCallback, filter: EntityTypes.PLANT);
        }
        private void PostEntityDeathCallback(LevelCallbacks.PostEntityDeathParams param, CallbackResult result)
        {
            var entity = param.entity;
            if (entity == null)
                return;
            if (!entity.HasBuff(this))
                return;
            var sourceEntity = param.deathInfo.Source?.GetEntity(entity.Level);
            if (sourceEntity == null)
                return;
            var effects = param.deathInfo.Effects;
            if (effects.HasEffect(VanillaDamageEffects.NO_DEATH_TRIGGER) || effects.HasEffect(VanillaDamageEffects.DIG))
                return;
            if (entity.RNG.Next(4) == 0)
            {
                var transformParam = sourceEntity.GetSpawnParams();
                entity.Spawn(VanillaEnemyID.gargoyle, entity.Position, transformParam);
                entity.PlaySound(VanillaSoundID.lightningAttack);
            }
        }
    }
}
