#nullable enable // autogenerated

using PVZEngine.Buffs;
using PVZEngine.Definitions;
using PVZEngine.Entities;
using PVZEngine.Modifiers;

namespace MVZ2.GameContent.Buffs.Enemies
{
    [AutoBuffDefinition(VanillaBuffNames.Enemy.shadowCellHealthUp)]
    public class ShadowCellHealthUpBuff : BuffDefinition
    {
        public ShadowCellHealthUpBuff(string nsp, string name) : base(nsp, name)
        {
            AddModifier(new FloatModifier(EngineEntityProps.MAX_HEALTH, NumberOperator.Add, 100f));
        }
    }
}
