#nullable enable // autogenerated

using System;
using PVZEngine.Modifiers;

namespace PVZEngine.Level
{
    public class PropertyBlock
    {
        public PropertyBlock(IModifiablePropertyTarget container, params IModifierProvider[] providers) : this(new ModifiableProperties(container, providers))
        {
        }
        private PropertyBlock(ModifiableProperties props)
        {
            modifiableProperties = props;
        }

        #region 可修改属性
        public void SetProperty<T>(PropertyKey<T> name, T? value)
        {
            modifiableProperties.SetProperty(name, value);
        }
        public void SetPropertyObject(IPropertyKey name, object? value)
        {
            modifiableProperties.SetPropertyObject(name, value);
        }
        public T? GetProperty<T>(PropertyKey<T> name, bool ignoreBuffs = false)
        {
            return modifiableProperties.GetProperty<T>(name, ignoreBuffs);
        }
        public object? GetPropertyObject(IPropertyKey name, bool ignoreBuffs = false)
        {
            return modifiableProperties.GetPropertyObject(name, ignoreBuffs);
        }
        public bool TryGetProperty<T>(PropertyKey<T> name, out T? value, bool ignoreBuffs = false)
        {
            return modifiableProperties.TryGetProperty<T>(name, out value, ignoreBuffs);
        }
        public bool RemoveProperty(IPropertyKey name)
        {
            return modifiableProperties.RemoveProperty(name);
        }
        public IPropertyKey[] GetPropertyNames()
        {
            return modifiableProperties.GetPropertyNames();
        }
        public void UpdateAllModifiedProperties(bool triggersEvaluation)
        {
            modifiableProperties.UpdateAllModifiedProperties(triggersEvaluation);
        }
        #endregion

        #region 后备缓存
        public void ClearFallbackCaches() => modifiableProperties.ClearFallbackCaches();
        #endregion

        #region 序列化
        public SerializablePropertyBlock ToSerializable()
        {
            return new SerializablePropertyBlock()
            {
                modifiable = modifiableProperties.ToSerializable()
            };
        }
        public void LoadFromSerializable(SerializablePropertyBlock? seri)
        {
            modifiableProperties.LoadFromSerializable(seri?.modifiable);
        }
        #endregion

        private ModifiableProperties modifiableProperties;
    }
    [Serializable]
    public class SerializablePropertyBlock
    {
        public SerializableModifiableProperties? modifiable;
    }
}
