#nullable enable // autogenerated

using System;
using UnityEngine;

public static class Log
{
    public static void LogMessage(string message)
    {
        Debug.Log(message);
    }
    public static void LogWarning(string message)
    {
        Debug.LogWarning(message);
    }
    public static void LogError(string message)
    {
        Debug.LogError(message);
    }
    public static void LogException(Exception exception)
    {
        Debug.LogException(exception);
    }
}