#nullable enable // autogenerated

using PVZEngine.Level;
using Tools;
using UnityEngine;

namespace PVZEngine.Armors
{
    public partial class Armor
    {
        #region 属性
        public T? GetProperty<T>(PropertyKey<T> name, bool ignoreBuffs = false)
        {
            return properties.GetProperty<T>(name, ignoreBuffs);
        }
        public void SetProperty<T>(PropertyKey<T> name, T? value)
        {
            properties.SetProperty(name, value);
        }
        private void UpdateAllBuffedProperties(bool triggersEvaluation)
        {
            properties.UpdateAllModifiedProperties(triggersEvaluation);
        }

        bool IModifiablePropertyTarget.GetFallbackProperty(IPropertyKey name, out object? value)
        {
            if (Definition != null)
            {
                if (Definition.TryGetPropertyObject(name, out var prop))
                {
                    value = prop;
                    return true;
                }
            }
            value = default;
            return false;
        }
        void IModifiablePropertyTarget.OnPropertyChanged(IPropertyKey name, object? beforeValue, object? afterValue, bool triggersEvaluation)
        {
            if (triggersEvaluation)
            {
                if (EngineArmorProps.MAX_HEALTH.Equals(name))
                {
                    var before = beforeValue.ToGeneric<float>();
                    var after = afterValue.ToGeneric<float>();
                    Health = Mathf.Min(after, Health * (after / before));
                }
            }
        }
        #endregion

        public void WritePropertiesToSerializable(SerializableArmor seri)
        {
            seri.properties = properties.ToSerializable();
        }
        public void InitPropertiesFromSerializable(SerializableArmor seri)
        {
            properties.LoadFromSerializable(seri.properties);
        }

        #region 属性字段
        private PropertyBlock properties;
        #endregion
    }
}