#nullable enable // autogenerated

using MVZ2.GameContent.Effects;
using MVZ2.GameContent.Shells;
using MVZ2.Vanilla.Audios;
using MVZ2.Vanilla.Enemies;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Properties;
using MVZ2Logic.Entities;
using MVZ2Logic.Level;
using PVZEngine;
using PVZEngine.Buffs;
using PVZEngine.Definitions;
using PVZEngine.Entities;
using PVZEngine.Modifiers;
using Tools;
using UnityEngine;

namespace MVZ2.GameContent.Buffs.Entities
{

    [AutoBuffDefinition(VanillaBuffNames.Entity.stoneEyeSlowing)]
    public class StoneEyeSlowingBuff : BuffDefinition
    {
        public StoneEyeSlowingBuff(string nsp, string name) : base(nsp, name)
        {
            AddModifier(new FloatModifier(VanillaEnemyProps.SPEED, NumberOperator.Multiply, 0.5f));
            AddModifier(new FloatModifier(VanillaEntityProps.ATTACK_SPEED, NumberOperator.Multiply, 0.5f));
            AddModifier(new Vector3Modifier(LogicEntityProps.HSV_OFFSET, NumberOperator.Add, new Vector3(0, -50, 0)) { NoStack = true });
            var tintModifier = ColorModifier.Multiply(EngineEntityProps.TINT, new Color(1.05f, 1.1f, 1.05f, 1f));
            tintModifier.NoStack = true;
            AddModifier(tintModifier);
        }
        public override void OnCreate(Buff buff)
        {
            base.OnCreate(buff);
            SetTimer(buff, TimerHelper.NewSecondTimer(SECONDS));
        }
        public override void PostUpdate(Buff buff)
        {
            base.PostUpdate(buff);
            var entity = buff.GetEntity();
            if (entity != null && entity.GetShellID() != VanillaShellID.stone && !buff.Level.IsIZombie())
            {
                var timer = GetTimer(buff);
                if (timer.RunToExpiredAndNotNull())
                {
                    var spawnParams = entity.GetSpawnParams();
                    spawnParams.SetProperty(EngineEntityProps.TINT, Color.gray);
                    entity.Spawn(VanillaEffectID.smokeCluster, entity.GetCenter(), spawnParams);
                    entity.PlaySound(VanillaSoundID.petrified);
                    entity.InflictPetrified(Ticks.FromSeconds(PETRIFY_DURATION_SECONDS), null);
                    timer.Reset();
                }
            }
        }
        public static FrameTimer? GetTimer(Buff buff) => buff.GetProperty<FrameTimer>(PROP_TIMER);
        public static void SetTimer(Buff buff, FrameTimer? value) => buff.SetProperty(PROP_TIMER, value);
        public const float SECONDS = 20f;
        public const float PETRIFY_DURATION_SECONDS = 10f;
        public static readonly VanillaBuffPropertyMeta<FrameTimer> PROP_TIMER = new VanillaBuffPropertyMeta<FrameTimer>("timer");
    }
}
