#nullable enable // autogenerated

using PVZEngine.Level;

namespace PVZEngine.Grids
{
    public partial class LawnGrid
    {
        #region 属性
        public T? GetProperty<T>(PropertyKey<T> name, bool ignoreBuffs = false)
        {
            return properties.GetProperty<T>(name, ignoreBuffs);
        }
        public void SetProperty<T>(PropertyKey<T> name, T value)
        {
            properties.SetProperty(name, value);
        }
        public void SetPropertyObject(IPropertyKey name, object value)
        {
            properties.SetPropertyObject(name, value);
        }
        #endregion

        #region IPropertyModifyTarget实现
        bool IModifiablePropertyTarget.GetFallbackProperty(IPropertyKey name, out object? value)
        {
            if (Definition == null)
            {
                value = default;
                return false;
            }
            return Definition.TryGetPropertyObject(name, out value);
        }
        void IModifiablePropertyTarget.OnPropertyChanged(IPropertyKey name, object? beforeValue, object? afterValue, bool triggersEvaluation)
        {
        }
        #endregion

        #region 序列化
        private void WritePropertiesToSerializable(SerializableGrid seri)
        {
            seri.properties = properties.ToSerializable();
        }
        private void LoadPropertiesFromSerializable(SerializableGrid seri)
        {
            properties.LoadFromSerializable(seri.properties);
        }
        #endregion

        #region 属性
        private PropertyBlock properties;
        #endregion 属性
    }
}