#nullable enable // autogenerated

using System.Linq;
using MVZ2.GameContent.Contraptions;
using MVZ2.Vanilla.Detections;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Grids;
using PVZEngine.Entities;
using UnityEngine;

namespace MVZ2.GameContent.Detections
{
    public class BeaconBoostDetector : Detector
    {
        public BeaconBoostDetector()
        {
            mask = EntityCollisionHelper.MASK_PLANT;
            factionTarget = FactionTarget.Friendly;
        }
        protected override Bounds GetDetectionBounds(Entity self)
        {
            var sizeX = radius * 2;
            var sizeY = radius * 2;
            var sizeZ = radius * 2;
            var center = self.GetCenter();
            return new Bounds(center, new Vector3(sizeX, sizeY, sizeZ));
        }
        protected override bool ValidateCollider(DetectionParams param, IEntityCollider collider)
        {
            if (!base.ValidateCollider(param, collider))
                return false;
            var entity = collider.Entity;
            if (entity.IsEntityOf(VanillaContraptionID.beacon))
                return false;
            var def = entity.Definition;
            var layers = def.GetGridLayersToTake();
            if (!(layers.Contains(VanillaGridLayers.main) || layers.Contains(VanillaGridLayers.protector)))
                return false;
            var self = param.entity;
            var center = self.GetCenter();
            return collider.CheckSphere(center, radius);
        }
        private float radius = 100;
    }
}
