#nullable enable // autogenerated

using MVZ2.Vanilla.Detections;
using MVZ2.Vanilla.Entities;
using PVZEngine.Entities;
using UnityEngine;

namespace MVZ2.GameContent.Detections
{
    public class BentSpoonDetector : Detector
    {
        public BentSpoonDetector(float radius)
        {
            this.radius = radius;
        }
        protected override Bounds GetDetectionBounds(Entity self)
        {
            var bounds = self.GetBounds();
            var sizeX = radius * 2;
            var sizeY = bounds.size.y;
            var sizeZ = radius * 2;
            return new Bounds(self.GetCenter(), new Vector3(sizeX, sizeY, sizeZ));
        }
        protected override bool ValidateCollider(DetectionParams param, IEntityCollider collider)
        {
            if (!base.ValidateCollider(param, collider))
                return false;
            var self = param.entity;
            var center = self.GetCenter();

            return collider.CheckSphere(center, radius);
        }
        private float radius;
    }
}
