#nullable enable // autogenerated

using MVZ2.GameContent.Buffs.Contraptions;
using MVZ2.Vanilla.Detections;
using PVZEngine.Buffs;
using PVZEngine.Entities;
using UnityEngine;

namespace MVZ2.GameContent.Detections
{
    public class LightningOrbEnergyShieldDetector : Detector
    {
        public LightningOrbEnergyShieldDetector()
        {
        }
        protected override Bounds GetDetectionBounds(Entity self)
        {
            return self.GetBounds();
        }
        protected override bool ValidateCollider(DetectionParams self, IEntityCollider collider)
        {
            var target = collider.Entity;
            if (target.HasBuff<LightningOrbEnergyShieldBuff>())
                return false;
            var selfBounds = self.entity.GetBounds();
            var bounds = collider.GetBoundingBox();
            if (bounds.center.x < selfBounds.min.x || bounds.center.x > selfBounds.max.x)
                return false;
            if (bounds.center.z < selfBounds.min.z || bounds.center.z > selfBounds.max.z)
                return false;
            return base.ValidateCollider(self, collider);
        }
    }
}
