#nullable enable // autogenerated

using MVZ2.GameContent.Enemies;
using MVZ2.Vanilla;
using MVZ2.Vanilla.Contraptions;
using MVZ2.Vanilla.Detections;
using MVZ2.Vanilla.Entities;
using PVZEngine.Entities;
using UnityEngine;

namespace MVZ2.GameContent.Detections
{
    public class PopCaptainDetector : Detector
    {
        public PopCaptainDetector(float rangeAddition, bool friendlyChecker)
        {
            this.rangeAddition = rangeAddition;
            this.friendlyChecker = friendlyChecker;
            if (friendlyChecker == true)
            {
                factionTarget = FactionTarget.Friendly;
                mask = EntityCollisionHelper.MASK_ENEMY;
            }
        }
        protected override Bounds GetDetectionBounds(Entity self)
        {
            var sizeX = self.GetRange() + rangeAddition;
            var sizeY = self.GetMaxAttackHeight();
            var sizeZ = 80;
            var pos = self.Position;
            var centerX = pos.x + self.GetFacingX() * sizeX * 0.5f;
            var centerY = pos.y + sizeY * 0.5f;
            var centerZ = pos.z;
            return new Bounds(new Vector3(centerX, centerY, centerZ), new Vector3(sizeX, sizeY, sizeZ));
        }
        public override bool ValidateTarget(DetectionParams self, Entity target)
        {
            if (target.IsFloor())
                return false;
            if (friendlyChecker && (target.IsNotActiveEnemy() || target.IsHarmless() || target.GetMass() == VanillaMass.VERY_HEAVY || target.IsEntityOf(VanillaEnemyID.popCaptain) || target.GetRelativeY() > (self.entity.GetMaxAttackHeight() / 2)))
                return false;
            return base.ValidateTarget(self, target);
        }
        private float rangeAddition;
        private bool friendlyChecker;
    }
}
