#nullable enable // autogenerated

using MVZ2.Vanilla.Detections;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Level;
using PVZEngine.Entities;
using Tools.Mathematics;
using UnityEngine;

namespace MVZ2.GameContent.Detections
{
    public class SkywardFamiliarDetector : Detector
    {
        protected override Bounds GetDetectionBounds(Entity self)
        {
            var shootOffset = self.GetShotOffset();
            shootOffset = self.ModifyShotOffset(shootOffset);
            var source = self.Position + shootOffset;
            var projectileSize = GetProjectileSize(self, Vector3.one * 32);
            var range = self.GetRange();

            var sizeX = range < 0 ? 800 : range;
            var limitedRange = VanillaLevelExt.GetAttackBorderX(true) - source.x;
            sizeX = Mathf.Min(sizeX, limitedRange);
            var centerX = source.x + sizeX * 0.5f * self.GetFacingX();

            float sizeY = 1000;
            float centerY = source.y;
            var sizeZ = projectileSize.z;
            var centerZ = source.z;


            return new Bounds(new Vector3(centerX, centerY, centerZ), new Vector3(sizeX, sizeY, sizeZ));
        }
        protected override bool ValidateCollider(DetectionParams param, IEntityCollider collider)
        {
            var self = param.entity;
            if (!ValidateTarget(param, collider.Entity))
                return false;
            var shootOffset = self.GetShotOffset();
            shootOffset = self.ModifyShotOffset(shootOffset);
            var source = self.Position + shootOffset;
            var range = self.GetRange();

            var projectileSize = GetProjectileSize(self, Vector3.one * 32);
            var radius = Mathf.Max(projectileSize.x, projectileSize.y, projectileSize.z) * 0.5f;

            var endRangePoint = self.GetShootPoint().x + range * self.GetFacingX();
            Vector3 endPoint = new Vector3(endRangePoint, self.GetGroundY(), self.Position.z);
            var angle = (endPoint - self.GetShootPoint()).normalized;

            Bounds targetBounds = collider.GetBoundingBox();
            
            var dir = angle;
            dir.x *= self.GetFacingX();
            var destination = dir * range + source;
            var capsule = new Capsule(source, destination, radius);
            if (MathTool.CollideBetweenCubeAndCapsule(capsule, targetBounds))
            {
                return true;
            }
            
            return false;
        }
    }
}
