#nullable enable // autogenerated

using MVZ2.Vanilla.Enemies;
using MVZ2Logic.Entities;
using PVZEngine.Buffs;
using PVZEngine.Definitions;
using PVZEngine.Entities;
using PVZEngine.Modifiers;

namespace MVZ2.GameContent.Buffs.Enemies
{
    [AutoBuffDefinition(VanillaBuffNames.Enemy.ghostPossessing)]
    public class GhostPossessingBuff : BuffDefinition
    {
        public GhostPossessingBuff(string nsp, string name) : base(nsp, name)
        {
            AddModifier(new IntModifier(VanillaEnemyProps.STATE_OVERRIDE, IntegerOperator.Set, LogicEnemyStates.IDLE));
            AddModifier(new IntModifier(EngineEntityProps.COLLISION_DETECTION, IntegerOperator.Set, EntityCollisionHelper.DETECTION_DISABLED));
        }
    }
}