#nullable enable // autogenerated

using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Modifiers;
using PVZEngine.Buffs;
using PVZEngine.Definitions;
using PVZEngine.Modifiers;

namespace MVZ2.GameContent.Buffs.Enemies
{
    [AutoBuffDefinition(VanillaBuffNames.Enemy.skelebombPunched)]
    public class SkelebombPunchedBuff : BuffDefinition
    {
        public SkelebombPunchedBuff(string nsp, string name) : base(nsp, name)
        {
            AddModifier(new FloatModifier(VanillaEntityProps.DAMAGE, NumberOperator.Multiply, 2));
            AddModifier(new BooleanModifier(VanillaEntityProps.CAN_DEACTIVE, false));
            AddModifier(new BooleanModifier(VanillaEntityProps.AI_FROZEN, false, VanillaModifierPriorities.FORCE));
        }
    }
}
