#nullable enable // autogenerated

using System.Collections.Generic;
using MVZ2.GameContent.Areas;
using MVZ2.GameContent.Effects;
using MVZ2.GameContent.Enemies;
using MVZ2.Vanilla.Audios;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Level;
using MVZ2.Vanilla.Properties;
using MVZ2Logic.Level;
using PVZEngine;
using PVZEngine.Buffs;
using PVZEngine.Callbacks;
using PVZEngine.Definitions;
using PVZEngine.Level;
using Tools;
using UnityEngine;

namespace MVZ2.GameContent.Buffs.Level
{
    [BuffDefinition(VanillaBuffNames.Level.spawnUFOAndParatrooperBuff)]
    public class SpawnUFOAndParatrooperBuff : BuffDefinition
    {
        public SpawnUFOAndParatrooperBuff(string nsp, string name) : base(nsp, name)
        {
            AddTrigger(LevelCallbacks.POST_WAVE, PostWave);
        }
        private void PostWave(LevelCallbacks.PostWaveParams param, CallbackResult result)
        {
            var level = param.level;
            foreach (var buff in level.GetBuffs(this))
            {
                var ufoWave = buff.GetProperty<int>(PROP_UFO_WAVE);
                var paratrooperWave = buff.GetProperty<int>(PROP_PARATROOPER_WAVE);
                ufoWave++;
                paratrooperWave++;
                buff.SetProperty(PROP_UFO_WAVE, ufoWave);
                buff.SetProperty(PROP_PARATROOPER_WAVE, paratrooperWave);
                // Boss复仇模式下生成间隔更慢。
                int ufoIntervalAddtion = level.IsBossRevenge() ? 2 : 0;
                int paratrooperIntervalMultiplier = level.IsBossRevenge() ? 2 : 1;

                // 生成UFO。
                int ufoInterval = UFO_INTERVAL + ufoIntervalAddtion;
                if (ufoWave == ufoInterval - 1)
                {
                    var ufoDefinition = level.Content.GetSpawnDefinition(VanillaEnemyID.undeadFlyingObject);
                    if (ufoDefinition != null)
                    {
                        PrepareUFO(ufoDefinition, level, level.CalculateSpawnPoints());
                    }
                }
                if (ufoWave >= ufoInterval)
                {
                    buff.SetProperty(PROP_UFO_WAVE, 0);
                }

                // 生成伞兵。
                int paratrooperInterval = PARATROOPER_INTERVAL * paratrooperIntervalMultiplier;
                if (paratrooperWave >= paratrooperInterval)
                {
                    Ship.SpawnParatroops(level, 4);
                    buff.SetProperty(PROP_PARATROOPER_WAVE, 0);
                }
            }
        }
        private void PrepareUFO(SpawnDefinition definition, LevelEngine level, float totalPoints)
        {
            var rng = new RandomGenerator(level.GetSpawnRNG().Next());
            int count = Mathf.Min(10, Mathf.CeilToInt(totalPoints * 0.3333333f));
            var entityVariant = definition.GetSpawnEntityVariant();

            bool random = entityVariant < 0;
            List<int> variantPool = new List<int>();
            int startIndex = 0;
            if (random)
            {
                UndeadFlyingObject.FillUFOVariantRandomPool(level, level.Option.RightFaction, variantPool);

                if (variantPool.Count <= 0)
                {
                    return;
                }
                startIndex = rng.Next(variantPool.Count);
            }
            for (int i = 0; i < count; i++)
            {
                int variant = entityVariant;
                if (random)
                {
                    var typeIndex = (startIndex + i) % variantPool.Count;
                    variant = variantPool[typeIndex];

                    if (rng.Next(100) < 10)
                    {
                        variant = UndeadFlyingObject.VARIANT_RAINBOW;
                    }
                }
                if (level.AreaID == VanillaAreaID.ship)
                {
                    var x = rng.Next(UFOBackground.MIN_X, UFOBackground.MAX_X);
                    var z = rng.Next(UFOBackground.MIN_Z, UFOBackground.MAX_Z);
                    var y = rng.Next(UFOBackground.MIN_Y, UFOBackground.MAX_Y);
                    var pos = new Vector3(x, y, z);
                    var background = level.Spawn(VanillaEffectID.ufoBackground, pos, null);
                    float speedMultiplier = 1;
                    var minLevelTime = Mathf.Min(level.GetWaveMaxSeconds(), level.GetWaveAdvanceSeconds());
                    if (minLevelTime <= TARGET_BACKGROUND_TIME)
                    {
                        speedMultiplier = TARGET_BACKGROUND_TIME / minLevelTime;
                    }
                    if (background != null)
                    {
                        var velocity = UFOBackground.FLY_DIRECTION * rng.Next(UFOBackground.MIN_SPEED, UFOBackground.MAX_SPEED) * speedMultiplier;
                        background.Velocity = velocity;
                        background.SetVariant(variant);
                    }
                }
                UFOSpawnBuff.Prepare(level, variant, definition.GetSpawnLevel());
            }
            level.PlaySound(VanillaSoundID.ufoAlert);
        }
        public const int UFO_INTERVAL = 3;
        public const int PARATROOPER_INTERVAL = 5;
        public const float TARGET_BACKGROUND_TIME = 6f;
        public static readonly VanillaBuffPropertyMeta<int> PROP_UFO_WAVE = new VanillaBuffPropertyMeta<int>("ufo_wave");
        public static readonly VanillaBuffPropertyMeta<int> PROP_PARATROOPER_WAVE = new VanillaBuffPropertyMeta<int>("paratrooper_wave");
    }
}
