#nullable enable // autogenerated

using System.Linq;
using MVZ2.GameContent.Contraptions;
using MVZ2.Vanilla.Audios;
using MVZ2.Vanilla.Callbacks;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Shells;
using MVZ2Logic.Entities;
using PVZEngine.Callbacks;
using PVZEngine.Definitions;
using PVZEngine.Entities;

namespace MVZ2.GameContent.Projectiles
{
    [AutoEntityBehaviourDefinition(VanillaProjectileNames.flint)]
    public class Flint : EntityBehaviourDefinition
    {
        public Flint(string nsp, string name) : base(nsp, name)
        {
            AddTrigger(VanillaLevelCallbacks.POST_PROJECTILE_HIT, PostHitEntityCallback);
        }
        private void PostHitEntityCallback(VanillaLevelCallbacks.PostProjectileHitParams param, CallbackResult result)
        {
            var hitResult = param.hit;
            var projectile = hitResult.Projectile;
            if (!projectile.Definition.HasBehaviour(this))
                return;
            if (hitResult.Pierce)
                return;
            var damageOutput = param.damage;
            if (damageOutput == null)
                return;
            var enemy = hitResult.Other;
            var hitMetal = damageOutput.GetAllResults().Any(e => e?.ShellDefinition?.ReflectSlice() ?? false);
            if (!hitMetal)
                return;
            var grid = enemy.GetGrid();
            if (grid == null)
                return;
            projectile.PlaySound(VanillaSoundID.ignite);
            GridFire.Spawn(grid, projectile, projectile.GetSpawnParams());
        }
    }
}
