#nullable enable // autogenerated

using System.Collections.Generic;
using MVZ2.GameContent.Buffs;
using MVZ2.GameContent.Shells;
using MVZ2.Vanilla.Entities;
using PVZEngine.Auras;
using PVZEngine.Buffs;
using PVZEngine.Definitions;
using PVZEngine.Entities;

namespace MVZ2.GameContent.Enemies
{
    [AutoEntityBehaviourDefinition(VanillaEntityBehaviourNames.gargoyle_Melee)]
    public class Gargoyle_MeleeBehaviour : EnemyMeleeBehaviour
    {
        public Gargoyle_MeleeBehaviour(string nsp, string name) : base(nsp, name)
        {
            AddAura(new CurseAura());
        }
        public class CurseAura : AuraEffectDefinition
        {
            public CurseAura() : base(VanillaBuffID.Contraption.abyss, 2)
            {
            }

            public override void GetAuraTargets(AuraEffect auraEffect, List<IBuffTarget> results)
            {
                var entity = auraEffect.Source as Entity;
                if (entity == null)
                    return;
                var targetID = GetMeleeTarget(entity);
                var curseTarget = targetID?.GetEntity(entity.Level);
                if (curseTarget == null)
                    return;
                bool stoneShell = curseTarget.GetShellDefinition()?.GetID() == VanillaShellID.stone || curseTarget.GetShellDefinition()?.GetID() == VanillaShellID.netherrack;
                if (curseTarget.Type == EntityTypes.PLANT && stoneShell)
                {
                    results.Add(curseTarget);
                }
            }
        }
    }
}
