#nullable enable // autogenerated

using System.Collections.Generic;
using MVZ2.GameContent.Buffs;
using MVZ2.Vanilla.Entities;
using PVZEngine.Auras;
using PVZEngine.Buffs;
using PVZEngine.Definitions;
using PVZEngine.Entities;

namespace MVZ2.GameContent.Effects
{
    [AutoEntityBehaviourDefinition(VanillaEffectNames.concealingSmoke)]
    public class ConcealingSmoke : EffectBehaviour
    {

        #region 公有方法
        public ConcealingSmoke(string nsp, string name) : base(nsp, name)
        {
            AddAura(new ConcealAura());
        }
        public override void Init(Entity entity)
        {
            base.Init(entity);
            entity.CollisionMaskHostile |=
                EntityCollisionHelper.MASK_PLANT |
                EntityCollisionHelper.MASK_ENEMY |
                EntityCollisionHelper.MASK_BOSS |
                EntityCollisionHelper.MASK_OBSTACLE |
                EntityCollisionHelper.MASK_PROJECTILE |
                EntityCollisionHelper.MASK_EFFECT;
        }
        public class ConcealAura : AuraEffectDefinition
        {
            public ConcealAura() : base(VanillaBuffID.Entity.concealed, 3)
            {
            }

            public override void GetAuraTargets(AuraEffect auraEffect, List<IBuffTarget> results)
            {
                var entity = auraEffect?.Source?.GetEntity();
                if (entity == null)
                    return;
                if (GasBehaviour.IsDisappearing(entity))
                    return;
                collisions.Clear();
                entity.GetCurrentCollisions(collisions);
                foreach (var collision in collisions)
                {
                    if (!collision.OtherCollider.IsForMain())
                        continue;
                    var other = collision.Other;
                    results.Add(other);
                }
            }
            private List<EntityCollision> collisions = new List<EntityCollision>();
        }
        #endregion
    }
}