#nullable enable // autogenerated

using MVZ2.GameContent.Projectiles;
using MVZ2.Vanilla.Audios;
using MVZ2.Vanilla.Entities;
using MVZ2Logic.Entities;
using MVZ2Logic.Level;
using PVZEngine.Definitions;
using PVZEngine.Entities;
using UnityEngine;

namespace MVZ2.GameContent.Effects
{
    [AutoEntityBehaviourDefinition(VanillaEffectNames.nightmareMeteor)]
    public class NightmareMeteor : EffectBehaviour
    {

        #region 公有方法
        public NightmareMeteor(string nsp, string name) : base(nsp, name)
        {
        }
        #endregion
        public override void Update(Entity entity)
        {
            base.Update(entity);
            if (entity.Timeout <= 0)
            {
                var effectPosition = entity.GetCenter() + Vector3.up * 37;
                var matterPosition = entity.GetCenter();
                matterPosition.y = 600;
                entity.Spawn(VanillaEffectID.nightmareFireParticles, effectPosition);
                var param = entity.GetSpawnParams();
                param.SetProperty(VanillaEntityProps.DAMAGE, 100f);
                param.SetProperty(VanillaEntityProps.RANGE, 120f);
                entity.Spawn(VanillaProjectileID.darkMatterBall, matterPosition, param);

                entity.PlaySound(VanillaSoundID.explosion);
                entity.Level.ShakeScreen(10, 0, 15);
                entity.Remove();
            }
        }
    }
}