#nullable enable // autogenerated

using Tools;
using UnityEngine;

namespace MVZ2.Models
{
    public class SilvenserModel : ModelComponent
    {
        public override void UpdateFrame(float deltaTime)
        {
            base.UpdateFrame(deltaTime);
            var bluePercent = Model.GetProperty<float>("ProgressBlue");
            var redPercent = Model.GetProperty<float>("ProgressRed");
            var greenPercent = Model.GetProperty<float>("ProgressGreen");
            circleSetterBlue.fill = bluePercent;
            circleSetterRed.fill = redPercent;
            circleSetterGreen.fill = greenPercent;
        }
        [SerializeField]
        private CircleFillSpriteSetter circleSetterBlue = null!;
        [SerializeField]
        private CircleFillSpriteSetter circleSetterRed = null!;
        [SerializeField]
        private CircleFillSpriteSetter circleSetterGreen = null!;
    }
}
