#nullable enable // autogenerated

using MVZ2.Vanilla.Audios;
using MVZ2.Vanilla.Callbacks;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Properties;
using PVZEngine.Buffs;
using PVZEngine.Callbacks;
using PVZEngine.Entities;
using PVZEngine.Level;
using PVZEngine.Modifiers;

namespace MVZ2.GameContent.Buffs.Enemies
{
    [BuffDefinition(VanillaBuffNames.Enemy.revivegraveRevive)]
    public class RevivegraveReviveBuff : BuffDefinition
    {
        public RevivegraveReviveBuff(string nsp, string name) : base(nsp, name)
        {
            AddModifier(new BooleanModifier(VanillaEnemyProps.ASSUME_ALIVE, true));
            AddTrigger(VanillaLevelCallbacks.PRE_ENEMY_FAINT, PreEnemyFaintCallback, priority: -200);
        }
        private void PreEnemyFaintCallback(EntityCallbackParams param, CallbackResult result)
        {
            var entity = param.entity;
            Buff? buff = entity.GetFirstBuff<RevivegraveReviveBuff>();
            if (buff == null)
                return;
            entity.Revive();

            bool stronger = IsStronger(buff);
            entity.AddBuff<BigTroubleBuff>();

            entity.HealEffects(entity.GetMaxHealth(), entity);
            result.SetFinalValue(false);

            var faction = GetFaction(buff);
            entity.CharmPermanent(faction, new EntitySourceReference(entity));
            entity.PlaySound(VanillaSoundID.revived);
            entity.PlaySound(VanillaSoundID.growBig);
            buff.Remove();
        }
        public static Buff AddToEntity(Entity entity, int faction, bool stronger)
        {
            var buff = entity.NewBuff<RevivegraveReviveBuff>();
            buff.SetProperty(RevivegraveReviveBuff.PROP_FACTION, faction);
            buff.SetProperty(RevivegraveReviveBuff.PROP_STRONGER, stronger);
            entity.AddBuff(buff);
            return buff;
        }
        public static int GetFaction(Buff buff) => buff.GetProperty<int>(PROP_FACTION);
        public static bool IsStronger(Buff buff) => buff.GetProperty<bool>(PROP_STRONGER);
        public static readonly VanillaBuffPropertyMeta<int> PROP_FACTION = new VanillaBuffPropertyMeta<int>("faction");
        public static readonly VanillaBuffPropertyMeta<bool> PROP_STRONGER = new VanillaBuffPropertyMeta<bool>("stronger");
    }
}
