#nullable enable // autogenerated

using MVZ2.Vanilla.Entities;
using MVZ2Logic.Entities;
using PVZEngine.Buffs;
using PVZEngine.Definitions;
using PVZEngine.Entities;
using PVZEngine.Modifiers;

namespace MVZ2.GameContent.Buffs.Contraptions
{
    [AutoBuffDefinition(VanillaBuffNames.Enemy.shikaisenInvincible)]
    public class ShikaisenInvincibleBuff : BuffDefinition
    {
        public ShikaisenInvincibleBuff(string nsp, string name) : base(nsp, name)
        {
            AddModifier(new BooleanModifier(EngineEntityProps.INVINCIBLE, true));
            AddModifier(new BooleanModifier(VanillaEntityProps.ETHEREAL, true));
            AddModifier(new BooleanModifier(LogicEnemyProps.ASSUME_ALIVE, true));
        }
    }
}
