#nullable enable // autogenerated

using MVZ2Logic.Entities;
using PVZEngine.Buffs;
using PVZEngine.Definitions;
using PVZEngine.Modifiers;

namespace MVZ2.GameContent.Buffs.Enemies
{
    [AutoBuffDefinition(VanillaBuffNames.Enemy.youkaiLeaf)]
    public class YoukaiLeafBuff : BuffDefinition
    {
        public YoukaiLeafBuff(string nsp, string name) : base(nsp, name)
        {
            AddModifier(new MaxHealthModifier(NumberOperator.Set, 300));
            AddModifier(new BooleanModifier(LogicEntityProps.GRAYSCALE, true));
        }
    }
}
