#nullable enable // autogenerated

using MVZ2.GameContent.Armors;
using MVZ2.GameContent.Enemies;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Properties;
using PVZEngine.Buffs;
using PVZEngine.Level;
using PVZEngine.Modifiers;

namespace MVZ2.GameContent.Buffs.Enemies
{
    [BuffDefinition(VanillaBuffNames.Enemy.karakasaSpeed)]
    public class FlyingPirateGlideBuff : BuffDefinition
    {
        public FlyingPirateGlideBuff(string nsp, string name) : base(nsp, name)
        {
            AddModifier(new FloatModifier(VanillaEnemyProps.SPEED, NumberOperator.Set, 10, 10000));
            AddModifier(new IntModifier(VanillaEnemyProps.STATE_OVERRIDE, IntegerOperator.Set, VanillaEntityStates.ENEMY_PARACHUTE));
        }
        public override void PostUpdate(Buff buff)
        {
            base.PostUpdate(buff);
            var entity = buff.GetEntity();
            if (entity == null)
                return;
            if (entity.Definition.GetID() != VanillaEnemyID.flyingPirate)
            {
                buff.Remove();
                return;
            }

            bool paragliderDiscard = entity.GetProperty<bool>(FlyingPirate.PROP_PARAGLIDER_DISCARDED);
            if (paragliderDiscard)
            {
                buff.Remove();
                return;
            }

            var col = buff.GetProperty<int>(PROP_TARGET_COLUMN);
            if (entity.GetColumn() == col || entity.IsOnGround)
            {
                buff.Remove();
                entity.RemoveBuffs<FlyBuff>();
            }
        }
        public static readonly VanillaBuffPropertyMeta<float> PROP_SPEED = new VanillaBuffPropertyMeta<float>("Speed", 1);
        public static readonly VanillaBuffPropertyMeta<int> PROP_TARGET_COLUMN = new VanillaBuffPropertyMeta<int>("target_column", 4);
    }
}
