#nullable enable // autogenerated

using System.Collections.Generic;
using System.Linq;
using MVZ2.GameContent.Damages;
using MVZ2.GameContent.Effects;
using MVZ2.Vanilla.Audios;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Properties;
using PVZEngine.Buffs;
using PVZEngine.Damages;
using PVZEngine.Entities;
using PVZEngine.Level;
using UnityEngine;

namespace MVZ2.GameContent.Buffs.Enemies
{
    [BuffDefinition(VanillaBuffNames.Entity.electricChain)]
    public class ElectricChainBuff : BuffDefinition
    {
        public ElectricChainBuff(string nsp, string name) : base(nsp, name)
        {
        }
        public override void PostAdd(Buff buff)
        {
            base.PostAdd(buff);
            buff.SetProperty(PROP_TIMEOUT, 10);
            attackedEnemies.Clear();
            var entity = buff.GetEntity();
            if (entity == null)
                return;
            attackedEnemies.Add(entity);
            var nextDamage = buff.GetProperty<float>(PROP_DAMAGE);
            FindNextTarget(buff, entity, entity.Position, entity.GetFaction(), nextDamage);
        }
        public override void PostUpdate(Buff buff)
        {
            base.PostUpdate(buff);
            if (attackedEnemies.Count >= MAX_TARGETS)
                buff.Remove();
        }
        private void FindNextTarget(Buff buff, Entity entity, Vector3 origin, int faction, float nextDamage)
        {
            var ignored = buff.GetProperty<IEntityCollider[]>(PROP_IGNORED_ENTITY);
            IEntityCollider[] hitColliders = entity.Level.OverlapSphere(origin, ZAP_RADIUS, faction, 0, EntityCollisionHelper.MASK_VULNERABLE);

            var validTargets = hitColliders
                .Where(c => !attackedEnemies.Contains(c.Entity) && !ignored.Contains(c))
                .OrderBy(c => Vector3.Distance(origin, c.Entity.Position))
                .ToArray();

            if (validTargets.Length > 0)
            {
                entity.PlaySound(VanillaSoundID.redLightning);
                AttackTarget(buff, entity, validTargets[0].Entity, nextDamage);
            }
        }
        private void AttackTarget(Buff buff, Entity entity, Entity target, float currentDamage)
        {
            if (attackedEnemies.Count >= MAX_TARGETS || target == null || target.IsDead)
                return;
            target.TakeDamage(currentDamage, new DamageEffectList(VanillaDamageEffects.LIGHTNING, VanillaDamageEffects.MUTE), entity);

            entity.Spawn(VanillaEffectID.electricArc, entity.Position)?.Let(e =>
            {
                ElectricArc.Connect(e, target.Position);
                ElectricArc.SetPointCount(e, 10);
                ElectricArc.UpdateArc(e);
                e.Timeout = 15;
            });
            
            attackedEnemies.Add(target);
            FindNextTarget(buff, target, target.Position, target.GetFaction(), currentDamage * (1 - DMG_REDUCTION));
        }
        public const float ZAP_RADIUS = 120;
        public const float MAX_TARGETS = 5;
        public const float DMG = 20;
        public const float DMG_REDUCTION = 0.2f;
        public static readonly VanillaBuffPropertyMeta<float> PROP_DAMAGE = new VanillaBuffPropertyMeta<float>("damage", 20);
        public static readonly VanillaBuffPropertyMeta<int> PROP_TIMEOUT = new VanillaBuffPropertyMeta<int>("Timeout");
        public static readonly VanillaBuffPropertyMeta<IEntityCollider[]> PROP_IGNORED_ENTITY = new VanillaBuffPropertyMeta<IEntityCollider[]>("ignored_entity", new List<IEntityCollider>().ToArray());
        private List<Entity> attackedEnemies = new List<Entity>();
    }
}
