#nullable enable // autogenerated

using MVZ2.Vanilla.Properties;
using PVZEngine.Buffs;
using PVZEngine.Entities;
using PVZEngine.Level;
using PVZEngine.Modifiers;
using Tools;

namespace MVZ2.GameContent.Buffs.Projectiles
{
    [BuffDefinition(VanillaBuffNames.Projectile.blownProjectile)]
    public class BlownProjectileBuff : BuffDefinition
    {
        public BlownProjectileBuff(string nsp, string name) : base(nsp, name)
        {
            AddModifier(new FloatModifier(EngineEntityProps.GRAVITY, NumberOperator.Add, PROP_GRAVITY));
        }
        public override void PostAdd(Buff buff)
        {
            base.PostAdd(buff);
            buff.SetProperty(PROP_TIMEOUT, 30);
            buff.SetProperty(PROP_GRAVITY, 0f);
        }
        public override void PostUpdate(Buff buff)
        {
            base.PostUpdate(buff);
            var entity = buff.GetEntity();
            var timeout = buff.GetProperty<int>(PROP_TIMEOUT);
            var gravity = buff.GetProperty<float>(PROP_GRAVITY);
            var falling = buff.GetProperty<bool>(PROP_FALLING);
            if (timeout <= 0)
            {
                if (falling)
                {
                    gravity += 0.25f;
                    buff.SetProperty(PROP_GRAVITY, gravity);
                    return;
                }

                if (entity?.Velocity.magnitude <= 1)
                {
                    buff.SetProperty(PROP_FALLING, true);
                }
                else
                {
                    buff.Remove();
                }
                return;
            }
            timeout--;
            buff.SetProperty(PROP_TIMEOUT, timeout);
        }
        public static readonly VanillaBuffPropertyMeta<bool> PROP_FALLING = new VanillaBuffPropertyMeta<bool>("falling");
        public static readonly VanillaBuffPropertyMeta<float> PROP_GRAVITY = new VanillaBuffPropertyMeta<float>("gravity");
        public static readonly VanillaBuffPropertyMeta<int> PROP_TIMEOUT = new VanillaBuffPropertyMeta<int>("Timeout");
    }
}
