#nullable enable // autogenerated

using PVZEngine.Entities;
using PVZEngine.Shells;
using UnityEngine;

namespace PVZEngine.Damages
{
    public class BodyDamageResult : DamageResult
    {
        public BodyDamageResult(DamageInput input, ShellDefinition? shell) : base(input, shell)
        {
        }
        public override Vector3 GetPosition()
        {
            return Entity.Position;
        }
    }
}
