#nullable enable // autogenerated

using System;
using PVZEngine.Entities;
using PVZEngine.Level;
using PVZEngine.Shells;
using UnityEngine;

namespace PVZEngine.Damages
{
    public abstract class DamageResult
    {
        public DamageResult(DamageInput input, ShellDefinition? shell)
        {
            values = new DamageResultValues(input.OriginalAmount, input.Amount, 0);
            Entity = input.Entity;
            Effects = input.Effects;
            Source = input.Source;
            ShellDefinition = shell;
        }
        public DamageResult(LevelEngine level, SerializableDamageResult seri)
        {
            var ent = level.FindEntityByID(seri.entityID);
            if (ent == null)
            {
                throw new NullReferenceException($"Cannot find the entity with id {seri.entityID} while loading SerializableDamageResult.");
            }
            Entity = ent;
            Source = seri.source?.ToDeserialized(level);
            Effects = new DamageEffectList(seri.effects);
            values = seri.values;
            Fatal = seri.fatal;
            ShellDefinition = level.Content.GetShellDefinition(seri.shellID);
        }
        public abstract Vector3 GetPosition();
        public bool HasEffect(NamespaceID effect)
        {
            return Effects?.HasEffect(effect) ?? false;
        }
        public bool HasDamageAmount()
        {
            return Amount > 0;
        }
        public abstract SerializableDamageResult ToSerializable();
        public DamageResultValues GetValues() => values;

        private DamageResultValues values;
        public ILevelSourceReference? Source { get; set; }
        public DamageEffectList Effects { get; set; }
        public ShellDefinition? ShellDefinition { get; set; }
        public bool Fatal { get; set; }
        public Entity Entity { get; set; }
        public float OriginalAmount
        {
            get => values.originalAmount;
            set => values.originalAmount = value;
        }
        public float Amount
        {
            get => values.amount;
            set => values.amount = value;
        }
        public float SpendAmount
        {
            get => values.spendAmount;
            set => values.spendAmount = value;
        }
    }
    [Serializable]
    public abstract class SerializableDamageResult
    {
        public ISerializableSourceReference? source;
        public NamespaceID[] effects;
        public NamespaceID? shellID;
        public long entityID;
        public bool fatal;
        public DamageResultValues values;

        protected SerializableDamageResult(DamageResult result)
        {
            source = result.Source?.ToSerializable();
            effects = result.Effects.GetEffects();
            fatal = result.Fatal;
            shellID = result.ShellDefinition?.GetID();
            entityID = result.Entity.ID;
            values = result.GetValues();
        }
        public abstract DamageResult ToDeserialized(LevelEngine level);
    }
}
