#nullable enable // autogenerated

using MVZ2.GameContent.Damages;
using MVZ2.GameContent.Enemies;
using MVZ2.GameContent.Models;
using MVZ2.Vanilla.Enemies;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Models;
using MVZ2.Vanilla.Properties;
using MVZ2Logic.Models;
using PVZEngine;
using PVZEngine.Buffs;
using PVZEngine.Callbacks;
using PVZEngine.Damages;
using PVZEngine.Definitions;
using PVZEngine.Entities;
using PVZEngine.Modifiers;
using Tools;

namespace MVZ2.GameContent.Buffs.Enemies
{
    [AutoBuffDefinition(VanillaBuffNames.Enemy.totenserWeb)]
    public class TotenserWebBuff : BuffDefinition
    {
        public TotenserWebBuff(string nsp, string name) : base(nsp, name)
        {
            AddModifier(new BooleanModifier(VanillaEntityProps.AI_FROZEN, true));
            AddModelInsertion(LogicModelHelper.ANCHOR_CENTER, VanillaModelKeys.totenserWeb, VanillaModelID.totenserWeb);
            AddTrigger(LevelCallbacks.POST_ENTITY_DEATH, PostEntityDeathCallback);
        }
        public override void PostAdd(Buff buff)
        {
            base.PostAdd(buff);
            buff.SetProperty(PROP_TIMER, TimerHelper.NewSecondTimer(COOLDOWN_SECONDS));
        }
        public override void PostUpdate(Buff buff)
        {
            base.PostUpdate(buff);
            var ent = buff.GetEntity();
            if (ent == null)
            {
                buff.Remove();
                return;
            }

            var timer = buff.GetProperty<FrameTimer>(PROP_TIMER);
            if (timer.RunToExpiredOrNull())
            {
                buff.Remove();
            }

            if (IsOutsideView(ent) || ent.Definition.HasBehaviour<MutantZombieBase>())
            {
                ent.TakeDamage(20, new DamageEffectList(VanillaDamageEffects.DAMAGE_BODY_AFTER_ARMOR_BROKEN), ent);
                buff.Remove();
            }
        }
        private void PostEntityDeathCallback(LevelCallbacks.EntityDeathParams param, CallbackResult result)
        {
            var entity = param.entity;
            entity.RemoveBuffs<TotenserWebBuff>();
        }
        private bool IsOutsideView(Entity entity)
        {
            return entity.IsEnemyOutsideLeft() || entity.IsEnemyOutsideRight();
        }
        public const float COOLDOWN_SECONDS = 15f;
        public static readonly VanillaBuffPropertyMeta<FrameTimer> PROP_TIMER = new VanillaBuffPropertyMeta<FrameTimer>("timer");
    }
}
