#nullable enable // autogenerated

using System;
using PVZEngine.Entities;
using PVZEngine.Level;
using PVZEngine.Shells;
using UnityEngine;

namespace PVZEngine.Damages
{
    public class BodyDamageResult : DamageResult
    {
        public BodyDamageResult(DamageInput input, ShellDefinition? shell) : base(input, shell)
        {
        }
        public BodyDamageResult(LevelEngine level, SerializableBodyDamageResult seri) : base(level, seri)
        {
        }
        public override SerializableDamageResult ToSerializable()
        {
            return new SerializableBodyDamageResult(this);
        }
        public override Vector3 GetPosition()
        {
            return Entity.Position;
        }
    }
    [Serializable]
    public class SerializableBodyDamageResult : SerializableDamageResult
    {
        public SerializableBodyDamageResult(BodyDamageResult result) : base(result)
        {
        }
        public override DamageResult ToDeserialized(LevelEngine level)
        {
            return new BodyDamageResult(level, this);
        }
    }
}
