#nullable enable // autogenerated

using MVZ2.GameContent.Damages;
using MVZ2.GameContent.Entities;
using MVZ2.Vanilla.Callbacks;
using MVZ2.Vanilla.Entities;
using PVZEngine.Callbacks;
using PVZEngine.Definitions;
using PVZEngine.Entities;

namespace MVZ2.GameContent.Enemies
{
    [AutoEntityBehaviourDefinition(VanillaEnemyNames.caveSpider)]
    public class CaveSpider : AIEntityBehaviour
    {
        public CaveSpider(string nsp, string name) : base(nsp, name)
        {
            AddTrigger(VanillaLevelCallbacks.APPLY_DAMAGE_SPECIAL_EFFECTS, ApplyDamageEffectsCallback);
        }
        private void ApplyDamageEffectsCallback(VanillaLevelCallbacks.PostTakeDamageParams param, CallbackResult callbackResult)
        {
            var output = param.output;
            var entity = output.Entity;
            if (entity.Type != EntityTypes.ENEMY)
                return;
            var bodyResult = output.BodyResult;
            var armorResult = output.ArmorResult;
            bool poison = false;
            if (bodyResult != null && bodyResult.Source?.DefinitionID == GetID() && bodyResult.HasEffect(VanillaDamageEffects.ENEMY_MELEE))
            {
                poison = !entity.IsSpider();
            }
            if (armorResult != null && armorResult.Source?.DefinitionID == GetID() && armorResult.HasEffect(VanillaDamageEffects.ENEMY_MELEE))
            {
                poison = !entity.IsSpider();
            }
            if (poison)
            {
                entity.InflictPoison(150, bodyResult?.Source ?? armorResult?.Source);
            }
        }
    }
}
