#nullable enable // autogenerated

using MVZ2.GameContent.Entities;
using PVZEngine.Definitions;

namespace MVZ2.GameContent.Enemies
{
    [AutoEntityBehaviourDefinition(VanillaEnemyNames.silverfish)]
    public class Silverfish : AIEntityBehaviour
    {
        public Silverfish(string nsp, string name) : base(nsp, name)
        {
        }
    }
}