#nullable enable // autogenerated

using MVZ2.Vanilla.Entities;
using PVZEngine.Entities;
using PVZEngine.Level;

namespace MVZ2.GameContent.Enemies
{
    [EntityBehaviourDefinition(VanillaEnemyNames.silverfish)]
    public class Silverfish : AIEntityBehaviour
    {
        public Silverfish(string nsp, string name) : base(nsp, name)
        {
        }
    }
}