#nullable enable // autogenerated

using MVZ2.GameContent.Contraptions;
using MVZ2.GameContent.Effects;
using MVZ2.Vanilla.Audios;
using MVZ2.Vanilla.Callbacks;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Projectiles;
using MVZ2.Vanilla.Properties;
using MVZ2Logic.Entities;
using MVZ2Logic.Level;
using PVZEngine.Callbacks;
using PVZEngine.Definitions;
using PVZEngine.Entities;
using UnityEngine;

namespace MVZ2.GameContent.Projectiles
{
    [AutoEntityBehaviourDefinition(VanillaProjectileNames.iceBall)]
    public class IceBall : EntityBehaviourDefinition, IHellfireIgniteBehaviour
    {
        public IceBall(string nsp, string name) : base(nsp, name)
        {
            AddTrigger(VanillaLevelCallbacks.POST_PROJECTILE_HIT, PostHitEntityCallback);
        }
        private void PostHitEntityCallback(VanillaLevelCallbacks.PostProjectileHitParams param, CallbackResult result)
        {
            var hitResult = param.hit;
            var projectile = hitResult.Projectile;
            if (!projectile.Definition.HasBehaviour(this))
                return;
            var damageOutput = param.damage;
            if (damageOutput == null)
                return;
            var entity = hitResult.Projectile;
            var other = hitResult.Other;

            if (!IsSplited(entity) && !hitResult.Pierce)
            {
                for (int i = 0; i < 2; i++)
                {
                    var direction = Quaternion.Euler(0, 45 - i * 90, 0) * entity.Velocity.normalized;
                    var velocity = direction * entity.Velocity.magnitude;
                    var shootParam = entity.GetShootParams();
                    shootParam.projectileID = VanillaProjectileID.iceBall;
                    shootParam.position = entity.GetCenter();
                    shootParam.pivot = VanillaEntityProps.SHOT_PIVOT_BOTTOM;
                    shootParam.velocity = velocity;
                    shootParam.faction = entity.GetFaction();
                    shootParam.damage = entity.GetDamage() / 2;
                    var projectile_split = other.ShootProjectile(shootParam);
                    if (projectile_split != null)
                    {
                        projectile_split.SetScale(Vector3.one * 0.5f);
                        projectile_split.SetDisplayScale(Vector3.one * 0.5f);
                        projectile_split.SetShadowScale(Vector3.one * 0.5f);
                        SetSplited(projectile_split, true);
                    }
                }
            }
        }
        public void Ignite(Entity entity, Entity hellfire, bool cursed)
        {
            var param = entity.GetSpawnParams();
            param.SetProperty(EngineEntityProps.SIZE, entity.GetScaledSize());
            entity.Spawn(VanillaEffectID.smoke, entity.Position, param);
            entity.Die();
            entity.PlaySound(VanillaSoundID.fizz);
        }
        public static void SetSplited(Entity entity, bool value)
        {
            entity.SetBehaviourField(PROP_SPLIT, value);
        }

        public static bool IsSplited(Entity entity)
        {
            return entity.GetBehaviourField<bool>(PROP_SPLIT);
        }
        public static readonly VanillaEntityPropertyMeta<bool> PROP_SPLIT = new VanillaEntityPropertyMeta<bool>("Split");
    }
}
