#nullable enable // autogenerated

using System.Linq;
using MVZ2.GameContent.Buffs.Projectiles;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Properties;
using MVZ2.Vanilla.Shells;
using PVZEngine;
using PVZEngine.Buffs;
using PVZEngine.Damages;
using PVZEngine.Entities;
using PVZEngine.Level;
using Tools;
using UnityEngine;

namespace MVZ2.GameContent.Projectiles
{
    [EntityBehaviourDefinition(VanillaProjectileNames.knife)]
    public class Knife : ProjectileBehaviour
    {
        public Knife(string nsp, string name) : base(nsp, name)
        {
        }
        public override void Init(Entity projectile)
        {
            base.Init(projectile);
            SetWaitTimer(projectile, new FrameTimer(30));
            SetNoDelay(projectile, true);
        }
        public override void Update(Entity projectile)
        {
            base.Update(projectile);
            var timer = GetWaitTimer(projectile);
            var shootPoint = projectile.Position;
            if (projectile.HasBuff<ProjectileWaitBuff>())
                return;

            if (!IsNoDelay(projectile))
            {
                if (timer.RunToExpiredOrNull())
                {
                    var shootDir = (GetDestination(projectile) - shootPoint).normalized;
                    {
                        projectile.Velocity = 10 * shootDir;
                        SetNoDelay(projectile, true);
                    }
                }
                else
                {
                    projectile.Velocity -= projectile.Velocity / 10;
                }
            }
        }
        protected override void PostHitEntity(ProjectileHitOutput hitResult, DamageOutput? damageOutput)
        {
            base.PostHitEntity(hitResult, damageOutput);
            if (damageOutput == null)
                return;
            var blocksSlice = damageOutput.GetAllResults().Any(e => e?.ShellDefinition?.BlocksSlice() ?? false);
            var reflectSlice = damageOutput.GetAllResults().Any(e => e?.ShellDefinition?.ReflectSlice() ?? false);
            if (!blocksSlice)
            {
                hitResult.Pierce = true;
            }
            else if (reflectSlice)
            {
                hitResult.Pierce = true;
                var projectile = hitResult.Projectile;
                var entity = hitResult.Other;
                Deflect(entity, projectile);
            }
        }
        public static Vector3 GetDestination(Entity entity)
        {
            return entity.GetBehaviourField<Vector3>(ID, PROP_DESTINATION);
        }
        public static void SetDestination(Entity entity, Vector3 target)
        {
            entity.SetBehaviourField(ID, PROP_DESTINATION, target);
        }
        public static bool IsNoDelay(Entity entity)
        {
            return entity.GetBehaviourField<bool>(ID, PROP_NO_DELAY);
        }
        public static void SetNoDelay(Entity entity, bool value)
        {
            entity.SetBehaviourField(ID, PROP_NO_DELAY, value);
        }
        public static FrameTimer? GetWaitTimer(Entity entity)
        {
            return entity.GetBehaviourField<FrameTimer>(ID, PROP_WAIT_TIMER);
        }
        public static void SetWaitTimer(Entity entity, FrameTimer value)
        {
            entity.SetBehaviourField(ID, PROP_WAIT_TIMER, value);
        }
        public static readonly NamespaceID ID = VanillaProjectileID.knife;
        public static readonly VanillaEntityPropertyMeta<Vector3> PROP_DESTINATION = new VanillaEntityPropertyMeta<Vector3>("Destination");
        public static readonly VanillaEntityPropertyMeta<bool> PROP_NO_DELAY = new VanillaEntityPropertyMeta<bool>("NoDelay");
        public static readonly VanillaEntityPropertyMeta<FrameTimer> PROP_WAIT_TIMER = new VanillaEntityPropertyMeta<FrameTimer>("WaitTimer");
        public static void Deflect(Entity self, Entity knife)
        {
            float thisX = self.Position.x;
            float thisZ = self.Position.z;
            float knifeX = knife.Position.x;
            float knifeZ = knife.Position.z;

            knife.Velocity = Vector3.Reflect(knife.Velocity, new Vector3(thisX - knifeX, 0, thisZ - knifeZ).normalized);
        }
    }
}
