#nullable enable // autogenerated

using System.Collections.Generic;
using MVZ2.GameContent.Contraptions;
using MVZ2.GameContent.Damages;
using MVZ2.GameContent.Detections;
using MVZ2.Vanilla.Audios;
using MVZ2.Vanilla.Detections;
using MVZ2.Vanilla.Entities;
using MVZ2Logic.Entities;
using PVZEngine.Collisions;
using PVZEngine.Damages;
using PVZEngine.Definitions;
using PVZEngine.Entities;
using Tools;

namespace MVZ2.GameContent.Projectiles
{
    [AutoEntityBehaviourDefinition(VanillaProjectileNames.lightningBall)]
    public class LightningBall : EntityBehaviourDefinition
    {
        public LightningBall(string nsp, string name) : base(nsp, name)
        {
            zapDetector = new SphereDetector(120);
        }
        public override void Update(Entity entity)
        {
            base.Update(entity);
            if (entity.IsTimeInterval(5))
            {
                zapDetectBuffer.Clear();
                zapDetector.DetectMultiple(entity, zapDetectBuffer);
                var results = zapDetectBuffer.RandomTake(3, entity.RNG);
                bool playSound = false;
                foreach (var target in results)
                {
                    target.TakeDamage(entity.GetDamage() / 4, new DamageEffectList(VanillaDamageEffects.LIGHTNING, VanillaDamageEffects.MUTE), entity);
                    TeslaCoil.CreateArc(entity, entity.Position, target.Entity.Position, 10, 15);
                    playSound = true;
                }
                if (playSound)
                    entity.PlaySound(VanillaSoundID.redLightning);
            }
        }
        private Detector zapDetector;
        private List<IEntityCollider> zapDetectBuffer = new List<IEntityCollider>();
    }
}
