#nullable enable // autogenerated

using PVZEngine.Entities;
using PVZEngine.Level;

namespace MVZ2.GameContent.Projectiles
{
    [EntityBehaviourDefinition(VanillaProjectileNames.miniTNT)]
    public class MiniTNT : FlyingTNT
    {
        public MiniTNT(string nsp, string name) : base(nsp, name)
        {
        }
    }
}
