#nullable enable // autogenerated

using System.Linq;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Properties;
using MVZ2.Vanilla.Shells;
using PVZEngine.Damages;
using PVZEngine.Entities;
using PVZEngine.Level;
using UnityEngine;

namespace MVZ2.GameContent.Projectiles
{
    [EntityBehaviourDefinition(VanillaProjectileNames.shuriken)]
    public class Shuriken : ProjectileBehaviour
    {
        public Shuriken(string nsp, string name) : base(nsp, name)
        {
        }
        public override void Update(Entity entity)
        {
            base.Update(entity);
            entity.RenderRotation += Vector3.back * 30f;
            SetNoDeflect(entity, false);
        }
        protected override void PostHitEntity(ProjectileHitOutput hitResult, DamageOutput? damageOutput)
        {
            base.PostHitEntity(hitResult, damageOutput);
            if (damageOutput == null)
                return;
            var reflectSlice = damageOutput.GetAllResults().Any(e => e?.ShellDefinition?.ReflectSlice() ?? false);
            if (reflectSlice)
            {
                hitResult.Pierce = true;
                var projectile = hitResult.Projectile;
                var otherCollider = hitResult.Collider;
                if (IsNoDeflect(projectile))
                    return;
                Knife.Deflect(projectile, otherCollider);
                SetNoDeflect(projectile, true);
            }
        }
        public static bool IsNoDeflect(Entity entity)
        {
            return entity.GetBehaviourField<bool>(PROP_NO_DEFLECT);
        }
        public static void SetNoDeflect(Entity entity, bool value)
        {
            entity.SetBehaviourField(PROP_NO_DEFLECT, value);
        }
        public static readonly VanillaEntityPropertyMeta<bool> PROP_NO_DEFLECT = new VanillaEntityPropertyMeta<bool>("no_deflect");
    }
}
