#nullable enable // autogenerated

using MVZ2.GameContent.Damages;
using MVZ2.GameContent.Effects;
using MVZ2.Vanilla.Callbacks;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Properties;
using PVZEngine.Callbacks;
using PVZEngine.Damages;
using PVZEngine.Definitions;
using PVZEngine.Entities;
using Tools;

namespace MVZ2.GameContent.Projectiles
{
    [AutoEntityBehaviourDefinition(VanillaProjectileNames.soulfireSaw)]
    public class SoulfireSaw : EntityBehaviourDefinition
    {
        public SoulfireSaw(string nsp, string name) : base(nsp, name)
        {
            AddTrigger(VanillaLevelCallbacks.POST_PROJECTILE_HIT, PostHitEntityCallback);
        }
        public override void Init(Entity projectile)
        {
            base.Init(projectile);
            SetPiercedTimeout(projectile, new FrameTimer(3));
        }
        public override void Update(Entity projectile)
        {
            base.Update(projectile);
            if (IsPierced(projectile))
            {
                var timeout = GetPiercedTimeout(projectile);
                timeout?.Run();
            }
        }
        private void PostHitEntityCallback(VanillaLevelCallbacks.PostProjectileHitParams param, CallbackResult result)
        {
            var hitResult = param.hit;
            var projectile = hitResult.Projectile;
            if (!projectile.Definition.HasBehaviour(this))
                return;

            var damageOutput = param.damage;
            if (damageOutput == null)
                return;

            bool blocksFire = damageOutput.WillDamageBlockFire();
            SetPierced(projectile, true);

            var timeout = GetPiercedTimeout(projectile);
            bool noPierce = IsPierced(projectile) && (timeout == null || timeout.Expired);
            if (noPierce)
                hitResult.Pierce = false;

            if (!blocksFire)
            {
                projectile.Level.Spawn(VanillaEffectID.soulfire, projectile.Position, projectile);
                if (noPierce)
                {
                    var damageEffects = new DamageEffectList(VanillaDamageEffects.FIRE, VanillaDamageEffects.MUTE);
                    projectile.SplashDamage(hitResult.Collider, projectile.Position, 48, projectile.GetFaction(), projectile.GetDamage() / 4f, damageEffects);
                }
            }
        }
        public static void SetPierced(Entity entity, bool value)
        {
            entity.SetBehaviourField(PROP_PIERCED, value);
        }
        public static bool IsPierced(Entity entity)
        {
            return entity.GetBehaviourField<bool>(PROP_PIERCED);
        }
        public static void SetPiercedTimeout(Entity entity, FrameTimer value)
        {
            entity.SetBehaviourField(PROP_PIERCED_TIMEOUT, value);
        }
        public static FrameTimer? GetPiercedTimeout(Entity entity)
        {
            return entity.GetBehaviourField<FrameTimer>(PROP_PIERCED_TIMEOUT);
        }
        public static readonly VanillaEntityPropertyMeta<bool> PROP_PIERCED = new VanillaEntityPropertyMeta<bool>("pierced");
        public static readonly VanillaEntityPropertyMeta<FrameTimer> PROP_PIERCED_TIMEOUT = new VanillaEntityPropertyMeta<FrameTimer>("pierced_timeout");
    }
}
