#nullable enable // autogenerated

using MVZ2.GameContent.Damages;
using MVZ2.GameContent.Effects;
using MVZ2.Vanilla.Audios;
using MVZ2.Vanilla.Callbacks;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Level;
using MVZ2.Vanilla.Projectiles;
using MVZ2.Vanilla.Properties;
using MVZ2Logic.Entities;
using MVZ2Logic.Level;
using PVZEngine.Callbacks;
using PVZEngine.Damages;
using PVZEngine.Definitions;
using PVZEngine.Entities;
using UnityEngine;

namespace MVZ2.GameContent.Projectiles
{
    [AutoEntityBehaviourDefinition(VanillaProjectileNames.soulfireBall)]
    public class SoulfireBall : EntityBehaviourDefinition
    {
        public SoulfireBall(string nsp, string name) : base(nsp, name)
        {
            AddTrigger(VanillaLevelCallbacks.POST_PROJECTILE_HIT, PostHitEntityCallback);
        }
        private void PostHitEntityCallback(VanillaLevelCallbacks.PostProjectileHitParams param, CallbackResult result)
        {
            var hitResult = param.hit;
            var projectile = hitResult.Projectile;
            if (!projectile.Definition.HasBehaviour(this))
                return;
            var damageOutput = param.damage;
            if (damageOutput == null)
                return;
            var other = hitResult.Other;

            bool blocksFire = damageOutput.WillDamageBlockFire();

            var blast = IsBlast(projectile);
            if (blast)
            {
                projectile.PlaySound(VanillaSoundID.darkSkiesImpact);
                projectile.Level.ShakeScreen(3, 3, 3);
                projectile.Level.Spawn(VanillaEffectID.soulfireBlast, projectile.Position, projectile);
            }
            else if (!blocksFire)
            {
                projectile.Level.Spawn(VanillaEffectID.soulfire, projectile.Position, projectile);
            }
            if (!IsSplited(projectile) && !hitResult.Pierce)
            {
                for (int i = 0; i < 4; i++)
                {
                    var direction = Quaternion.Euler(0, 45 - i * 30, 0) * projectile.Velocity.normalized;
                    var velocity = direction * projectile.Velocity.magnitude;
                    var shootParam = projectile.GetShootParams();
                    shootParam.projectileID = VanillaProjectileID.soulfireBall;
                    shootParam.position = projectile.GetCenter();
                    shootParam.pivot = VanillaEntityProps.SHOT_PIVOT_BOTTOM;
                    shootParam.velocity = velocity;
                    shootParam.faction = projectile.GetFaction();
                    shootParam.damage = projectile.GetDamage() / 4;
                    var projectile_split = other.ShootProjectile(shootParam);
                    if (projectile_split != null)
                    {
                        projectile_split.SetScale(projectile.GetScale() * 0.5f);
                        projectile_split.SetDisplayScale(projectile.GetDisplayScale() * 0.5f);
                        projectile_split.SetLightRange(projectile.GetLightRange() * 0.5f);
                        projectile_split.SetShadowScale(projectile.GetShadowScale() * 0.5f);
                        SetSplited(projectile_split, true);
                    }
                }
            }

            if (!blocksFire || blast)
            {
                var damageEffects = new DamageEffectList(VanillaDamageEffects.FIRE, VanillaDamageEffects.EXPLOSION, VanillaDamageEffects.MUTE);
                projectile.SplashDamage(hitResult.Collider, projectile.Position, 40, projectile.GetFaction(), projectile.GetDamage() / 4f, damageEffects);
            }
        }
        public static void SetBlast(Entity entity, bool value)
        {
            entity.SetBehaviourField(PROP_BLAST, value);
        }
        public static void SetSplited(Entity entity, bool value)
        {
            entity.SetBehaviourField(PROP_SPLIT, value);
        }
        public static bool IsBlast(Entity entity)
        {
            return entity.GetBehaviourField<bool>(PROP_BLAST);
        }
        public static bool IsSplited(Entity entity)
        {
            return entity.GetBehaviourField<bool>(PROP_SPLIT);
        }
        public static readonly VanillaEntityPropertyMeta<bool> PROP_BLAST = new VanillaEntityPropertyMeta<bool>("Blast");
        public static readonly VanillaEntityPropertyMeta<bool> PROP_SPLIT = new VanillaEntityPropertyMeta<bool>("Split");
    }
}
