#nullable enable // autogenerated

using MVZ2.GameContent.Damages;
using MVZ2.Vanilla.Audios;
using MVZ2.Vanilla.Entities;
using MVZ2Logic.Level;
using PVZEngine.Damages;
using PVZEngine.Entities;
using PVZEngine.Level;
using UnityEngine;

namespace MVZ2.GameContent.Effects
{
    [EntityBehaviourDefinition(VanillaEffectNames.combatSliding)]
    public class CombatSliding : EffectBehaviour
    {
        public CombatSliding(string nsp, string name) : base(nsp, name)
        {
        }
        public override void Init(Entity entity)
        {
            base.Init(entity);
            entity.CollisionMaskHostile |= EntityCollisionHelper.MASK_VULNERABLE;
            entity.Velocity = entity.GetFacingDirection() * 32;
            entity.Spawn(VanillaEffectID.combatSlidingTrail, entity.Position)?.Let(e =>
            {
                e.SetParent(entity);
            });
        }
        public override void PostRemove(Entity entity)
        {
            base.PostRemove(entity);
            var level = entity.Level;
            var param = new SpawnParams();
            param.SetProperty(EngineEntityProps.FACTION, entity.GetFaction());
            param.SetProperty(VanillaEntityProps.DAMAGE, 1800f);
            param.SetProperty(VanillaEntityProps.RANGE, 40f);
            level.Spawn(VanillaEffectID.combatFlyKick, entity.Position, entity, param);
        }
        public override void PostCollision(EntityCollision collision, int state)
        {
            base.PostCollision(collision, state);
            var entity = collision.Entity;
            var collider = collision.OtherCollider;
            var other = collision.Other;
            if (state != EntityCollisionHelper.STATE_EXIT)
            {
                if (entity.IsHostile(other) && other.IsVulnerableEntity())
                {
                    if (!entity.IsProjectileColliderIgnored(collider))
                    {
                        entity.AddIgnoredProjectileCollider(collider);

                        var faction = entity.GetFaction();
                        var damage = entity.GetDamage();
                        var damageEffects = new DamageEffectList(VanillaDamageEffects.IMPACT, VanillaDamageEffects.DAMAGE_BODY_AFTER_ARMOR_BROKEN);
                        collider.TakeDamage(damage, damageEffects, entity);
                        entity.PlaySound(VanillaSoundID.punch);
                        entity.PlaySound(VanillaSoundID.impact);

                        if (collider.IsForMain() && other.Type == EntityTypes.ENEMY)
                        {
                            var knockbackMultiplier = other.GetStrongKnockbackMultiplier();
                            other.Velocity += entity.GetFacingDirection() * (20f * knockbackMultiplier) + Vector3.up * (10 * knockbackMultiplier);

                            other.ApplyStrongImpact();
                        }
                    }
                }
            }
            else
            {
                entity.RemoveIgnoredProjectileCollider(collider);
            }
        }
    }
}