#nullable enable // autogenerated

using MVZ2.Vanilla.Entities;
using PVZEngine.Damages;
using PVZEngine.Entities;
using PVZEngine.Level;

namespace MVZ2.GameContent.Effects
{
    [EntityBehaviourDefinition(VanillaEffectNames.dragonFireBreathDOT)]
    public class DragonFireBreathDOT : DragonFireBreath
    {
        public DragonFireBreathDOT(string nsp, string name) : base(nsp, name)
        {
        }
        public override void Init(Entity entity)
        {
            base.Init(entity);
            var collisionMask = EntityCollisionHelper.MASK_VULNERABLE;
            entity.CollisionMaskFriendly = collisionMask;
            entity.CollisionMaskHostile = collisionMask;
        }
        public override void PostCollision(EntityCollision collision, int state)
        {
            base.PostCollision(collision, state);
            var other = collision.Other;
            var self = collision.Entity;
            if (!other.IsVulnerableEntity())
                return;
            if (state == EntityCollisionHelper.STATE_EXIT)
                return;

            var damage = self.GetDamage();
            var damageEffects = self.GetDamageEffects();
            DamageEffectList effects;
            if (damageEffects != null)
            {
                effects = new DamageEffectList(damageEffects);
            }
            else
            {
                effects = new DamageEffectList();
            }
            collision.OtherCollider.TakeDamage(damage, effects, self);
        }
    }
}