#nullable enable // autogenerated

using System.Collections.Generic;
using MVZ2.GameContent.Detections;
using MVZ2.GameContent.Effects;
using MVZ2.GameContent.Projectiles;
using MVZ2.Vanilla.Audios;
using MVZ2.Vanilla.Detections;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Grids;
using MVZ2.Vanilla.Properties;
using PVZEngine.Entities;
using PVZEngine.Grids;
using PVZEngine.Level;
using PVZEngine.Modifiers;
using Tools;
using UnityEngine;

namespace MVZ2.GameContent.Contraptions
{
    [EntityBehaviourDefinition(VanillaEffectNames.fireWall)]
    public class FireWall : EntityBehaviourDefinition, IBeBlownBehaviour
    {
        public FireWall(string nsp, string name) : base(nsp, name)
        {
            detector = new HellfireIgniteDetector(0)
            {
                factionTarget = FactionTarget.Any,
                mask = EntityCollisionHelper.MASK_PROJECTILE,
            };
            AddModifier(new Vector3Modifier(EngineEntityProps.DISPLAY_SCALE, NumberOperator.Multiply, PROP_SCALE_MULTIPLIER));
            AddModifier(new Vector3Modifier(EngineEntityProps.SCALE, NumberOperator.Multiply, PROP_SCALE_MULTIPLIER));
        }
        public override void Init(Entity entity)
        {
            base.Init(entity);
            entity.SetProperty(PROP_TIMER, new FrameTimer(10));
        }
        public override void Update(Entity entity)
        {
            base.Update(entity);
            UpdateModel(entity);
            UpdateIgnite(entity);
        }
        private void UpdateModel(Entity entity)
        {
            var timer = entity.GetProperty<FrameTimer>(PROP_TIMER);
            if (timer == null || timer.Expired)
            {
                entity.SetProperty(PROP_SCALE_MULTIPLIER, Vector3.one);
            }
            else
            {
                timer.Run();
                var scaleMultiplier = new Vector3(1, 1 - timer.GetTimeoutPercentage(), 1);
                entity.SetProperty(PROP_SCALE_MULTIPLIER, scaleMultiplier);
            }
        }
        private void UpdateIgnite(Entity hellfire)
        {
            igniteBuffer.Clear();
            detector.DetectEntities(hellfire, igniteBuffer);
            foreach (Entity target in igniteBuffer)
            {
                var behaviour = target.Definition?.GetBehaviour<IHellfireIgniteBehaviour>();
                if (behaviour == null)
                    return;
                target.PlaySound(VanillaSoundID.fire);
                if (target.IsEntityOf(VanillaProjectileID.log))
                {
                    behaviour.Ignite(target, hellfire, false);
                }
                else
                    target.Remove();
            }
        }
        public void BeBlown(Entity entity, Entity source)
        {
            entity.Timeout -= 2;
            entity.Timeout = Mathf.Max(entity.Timeout, 0);
        }
        public static Entity? Spawn(LawnGrid grid, Entity source, SpawnParams spawnParam)
        {
            if (!grid.IsLand())
                return null;
            var level = source.Level;
            foreach (var gridFire in level.FindEntities(e => e.IsEntityOf(VanillaEffectID.gridFire) && e.GetGrid() == grid))
            {
                gridFire.Remove();
            }
            if (level.EntityExists(e => e.IsEntityOf(VanillaEffectID.fireWall) && e.GetGrid() == grid))
                return null;
            var position = grid.GetEntityPosition();

            return source.Spawn(VanillaEffectID.fireWall, position, spawnParam);
        }
        private Detector detector;
        private List<Entity> igniteBuffer = new List<Entity>();
        public static readonly VanillaEntityPropertyMeta<FrameTimer> PROP_TIMER = new VanillaEntityPropertyMeta<FrameTimer>("timer");
        public static readonly VanillaEntityPropertyMeta<Vector3> PROP_SCALE_MULTIPLIER = new VanillaEntityPropertyMeta<Vector3>("scale_multiplier", Vector3.right);

    }
}
