#nullable enable // autogenerated

using MVZ2.Vanilla;
using PVZEngine;

namespace MVZ2.GameContent.Seeds
{
    public static class VanillaBlueprintFunctions
    {
        public static readonly NamespaceID undefined = Get("undefined");
        public static readonly NamespaceID shooter = Get("shooter");
        public static readonly NamespaceID producer = Get("producer");
        public static readonly NamespaceID defender = Get("defender");
        public static readonly NamespaceID assistance = Get("assistance");
        public static readonly NamespaceID melee = Get("melee");
        public static readonly NamespaceID bomb = Get("bomb");
        public static readonly NamespaceID combustor = Get("combustor");
        public static readonly NamespaceID sharpener = Get("sharpener");
        public static readonly NamespaceID enchanted = Get("enchanted");
        public static readonly NamespaceID potion = Get("potion");
        public static readonly NamespaceID armed = Get("armed");
        public static readonly NamespaceID buzzer = Get("buzzer");
        public static readonly NamespaceID frosty = Get("frosty");
        public static readonly NamespaceID flourish = Get("flourish");
        public static readonly NamespaceID monster = Get("monster");
        private static NamespaceID Get(string name)
        {
            return new NamespaceID(VanillaMod.spaceName, name);
        }
    }
}
