#nullable enable // autogenerated

using System.Collections.Generic;
using MVZ2.GameContent.Enemies;
using MVZ2Logic.Blueprints;
using PVZEngine;
using PVZEngine.Level;

namespace MVZ2.GameContent.Stages
{
    public class IZombieEndlessBehaviour : IZombieEndlessBaseBehaviour
    {
        public IZombieEndlessBehaviour(StageDefinition stageDef) : base(stageDef)
        {
        }
        protected override IEnumerable<IZELayoutItem> GetNormalLayouts()
        {
            // A����
            yield return new IZELayoutItem(VanillaIZombieLayoutID.izeComposite, 1.5f); // �ۺ�
            yield return new IZELayoutItem(VanillaIZombieLayoutID.izeControl, 1.5f); // ����
            yield return new IZELayoutItem(VanillaIZombieLayoutID.izeInstakill, 1f); // ����

            // B����
            yield return new IZELayoutItem(VanillaIZombieLayoutID.izeSpikes, 0.2f); // ľͶ���
            yield return new IZELayoutItem(VanillaIZombieLayoutID.izeDispensers, 0.2f); // ������
            yield return new IZELayoutItem(VanillaIZombieLayoutID.izeExplosives, 0.2f); // ��ը
            yield return new IZELayoutItem(VanillaIZombieLayoutID.izeFire, 0.2f); // ����
            yield return new IZELayoutItem(VanillaIZombieLayoutID.izeAwards, 0.2f); // �ָ�
        }
        protected override IEnumerable<IZELayoutItem> GetAwardLayouts()
        {
            yield return new IZELayoutItem(VanillaIZombieLayoutID.izeAwards);
            yield return new IZELayoutItem(VanillaIZombieLayoutID.izeError, 0.2f);
        }
        protected override NamespaceID GetFirstLayoutID()
        {
            return VanillaIZombieLayoutID.izeComposite;
        }
        protected override IEnumerable<NamespaceID> GetBlueprints()
        {
            yield return LogicBlueprintID.FromEntity(VanillaEnemyID.imp);
            yield return LogicBlueprintID.FromEntity(VanillaEnemyID.leatherCappedZombie);
            yield return LogicBlueprintID.FromEntity(VanillaEnemyID.skeletonHorse);
            yield return LogicBlueprintID.FromEntity(VanillaEnemyID.ghost);
            yield return LogicBlueprintID.FromEntity(VanillaEnemyID.gargoyle);
            yield return LogicBlueprintID.FromEntity(VanillaEnemyID.ironHelmettedZombie);
            yield return LogicBlueprintID.FromEntity(VanillaEnemyID.reflectiveBarrierZombie);
            yield return LogicBlueprintID.FromEntity(VanillaEnemyID.wickedHermitZombie);
            yield return LogicBlueprintID.FromEntity(VanillaEnemyID.skeletonWarrior);
            yield return LogicBlueprintID.FromEntity(VanillaEnemyID.dullahan);
        }
    }
}
