#nullable enable // autogenerated

using System.Collections.Generic;
using MVZ2.GameContent.Buffs;
using MVZ2.GameContent.Seeds;
using MVZ2Logic.Artifacts;
using MVZ2Logic.Definitions;
using MVZ2Logic.Entities;
using PVZEngine.Auras;
using PVZEngine.Buffs;
using PVZEngine.Entities;

namespace MVZ2.GameContent.Artifacts
{
    [AutoArtifactDefinition(VanillaArtifactNames.miracleMalletReplica)]
    public class MiracleMalletReplica : ArtifactDefinition
    {
        public MiracleMalletReplica(string nsp, string name) : base(nsp, name)
        {
            AddAura(new DamageAura());
            AddAura(new ContactDamageAura());
        }
        public override void PostUpdate(Artifact artifact)
        {
            base.PostUpdate(artifact);
            artifact.SetGlowing(true);
        }
        public class DamageAura : AuraEffectDefinition
        {
            public DamageAura() : base(VanillaBuffID.Contraption.miracleMalletReplicaDamage)
            {
            }

            public override void GetAuraTargets(AuraEffect auraEffect, List<IBuffTarget> results)
            {
                var level = auraEffect.Source.GetLevel();
                results.AddRange(level.FindEntities(e => e.Type == EntityTypes.PLANT && e.IsFriendlyEntity()));
            }
        }
        public class ContactDamageAura : AuraEffectDefinition
        {
            public ContactDamageAura() : base(VanillaBuffID.Contraption.miracleMalletReplicaDamage)
            {
            }
            public override void GetAuraTargets(AuraEffect auraEffect, List<IBuffTarget> results)
            {
                var level = auraEffect.Source.GetLevel();
                foreach (var target in level.FindEntities(e => e.Type == EntityTypes.PLANT && e.IsFriendlyEntity()))
                {
                    if (target.Definition.GetFunction() == VanillaBlueprintFunctions.melee)
                        results.Add(target);
                }
            }
        }
    }
}
