#nullable enable // autogenerated

using MVZ2.GameContent.Buffs.Enemies;
using MVZ2.GameContent.Detections;
using MVZ2.GameContent.Effects;
using MVZ2.GameContent.Entities;
using MVZ2.GameContent.Models;
using MVZ2.Vanilla.Audios;
using MVZ2.Vanilla.Detections;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Properties;
using MVZ2Logic.Entities;
using MVZ2Logic.Level;
using PVZEngine.Buffs;
using PVZEngine.Damages;
using PVZEngine.Definitions;
using PVZEngine.Entities;
using PVZEngine.Modifiers;
using UnityEngine;

namespace MVZ2.GameContent.Enemies
{
    [AutoEntityBehaviourDefinition(VanillaEnemyNames.flyingPirate)]
    public class FlyingPirate : AIEntityBehaviour
    {
        public FlyingPirate(string nsp, string name) : base(nsp, name)
        {
            blocksJumpDetector = new SkeletonHorseBlocksJumpDetector();
            AddModifier(new FloatModifier(VanillaEntityProps.DAMAGE, NumberOperator.Multiply, 2f));
        }
        public override void Init(Entity entity)
        {
            base.Init(entity);
            var buff = entity.AddBuff<FlyBuff>();
            buff.SetProperty(FlyBuff.PROP_TARGET_HEIGHT, 60f);
            if (!entity.IsPreviewEnemy())
            {
                entity.PlaySound(VanillaSoundID.wind, volume: 0.5f);
                var speedBuff = entity.AddBuff<FlyingPirateGlideBuff>();
                speedBuff.SetProperty(FlyingPirateGlideBuff.PROP_TARGET_COLUMN, TARGET_COLUMN);
            }
        }
        protected override void UpdateLogic(Entity entity)
        {
            base.UpdateLogic(entity);
            entity.SetModelProperty("HasBoat", entity.HasBuff<BoatBuff>());
            entity.SetModelProperty("Parachute", FlyingPirateGlideBuff.IsParachuting(entity));
        }
        protected override void UpdateAI(Entity entity)
        {
            base.UpdateAI(entity);


            bool parachute = FlyingPirateGlideBuff.IsParachuting(entity);
            if (!parachute)
            {
                DiscardParaglider(entity);
            }
            else if (blocksJumpDetector.DetectExists(entity))
            {
                DiscardParaglider(entity);
                var vel = entity.Velocity;
                vel.x = 0;
                entity.Velocity = vel;
                entity.Stun(30);
                entity.PlaySound(VanillaSoundID.bonk);
            }
        }
        public override void PostDeath(Entity entity, DeathInfo info)
        {
            base.PostDeath(entity, info);
            entity.RemoveBuffs<FlyingPirateGlideBuff>();
            if (entity.HasBuff<BoatBuff>())
            {
                entity.RemoveBuffs<BoatBuff>();
                // 掉落碎船掉落物
                entity.Level.Spawn(VanillaEffectID.brokenArmor, entity.GetCenter(), entity)?.Let(e =>
                {
                    e.Velocity = new Vector3(e.RNG.NextFloat() * 20 - 10, 5, 0);
                    e.ChangeModel(VanillaModelID.boatItem);
                    e.SetDisplayScale(entity.GetDisplayScale());
                });
            }
        }
        private void DiscardParaglider(Entity entity)
        {
            bool paragliderDiscard = entity.GetProperty<bool>(PROP_PARAGLIDER_DISCARDED);
            if (!paragliderDiscard)
            {
                entity.SetProperty(PROP_PARAGLIDER_DISCARDED, true);
                entity.Level.Spawn(VanillaEffectID.brokenArmor, entity.GetCenter() + Vector3.up * 60, entity)?.Let(e =>
                {
                    e.Velocity = entity.GetFacingDirection() * 10;
                    e.ChangeModel(VanillaModelID.flyingPirateParaglider);
                    e.SetDisplayScale(entity.GetDisplayScale());
                });
            }  
        }
        private Detector blocksJumpDetector;
        public const int TARGET_COLUMN = 4;
        public static readonly VanillaEntityPropertyMeta<bool> PROP_PARAGLIDER_DISCARDED = new VanillaEntityPropertyMeta<bool>("paraglider_discarded");
    }
}
